//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s8Payments18PaymentBaseHandlerCN.h"

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary36PaymentBRMerchantRegistrationHandler : _$s8Payments18PaymentBaseHandlerCN
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *currentHandler;
    MISSING_TYPE *currentErrorHandler;
    MISSING_TYPE *paymentMerchantManager;
    MISSING_TYPE *payoutBanks;
    MISSING_TYPE *taxID;
    MISSING_TYPE *merchantDetails;
    MISSING_TYPE *ownerDetails;
    MISSING_TYPE *payoutDetails;
}

- (void).cxx_destruct;

@end

