//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCCCE14MainAppLibraryCC8Payments13PaymentString2BR8Merchant7Details6Status : _TtCs12_SwiftObject
{
}

@end

