//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAProfileConfiguration-Protocol.h"

@interface _TtC14MainAppLibrary28ConsumerProfileConfiguration : NSObject <WAProfileConfiguration>
{
}

- (id)init;
- (long long)maxNameLength;
- (id)prefilledName;

@end

