//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary43AppStateRemoteChangeSetMediaUploadOperation : NSObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *mutations;
    MISSING_TYPE *mediaUploader;
    MISSING_TYPE *queue;
    MISSING_TYPE *completion;
    MISSING_TYPE *mediaUploadTask;
    MISSING_TYPE *started;
}

- (void).cxx_destruct;
- (id)init;

@end

