//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary26AppStateSyncSessionManager : _TtCs12_SwiftObject
{
    MISSING_TYPE *currentSession;
    MISSING_TYPE *sessionFactory;
    MISSING_TYPE *ownDeviceManager;
    MISSING_TYPE *optInStateManager;
    MISSING_TYPE *fileManager;
    MISSING_TYPE *taskScheduler;
    MISSING_TYPE *metricsLogger;
    MISSING_TYPE *persistedSessionInfo;
    MISSING_TYPE *currentDateProvider;
    MISSING_TYPE *delegate;
    MISSING_TYPE *databaseDirectoryURL;
    MISSING_TYPE *currentDeviceJID;
    MISSING_TYPE *canSync;
    MISSING_TYPE *keepAliveDuration;
    MISSING_TYPE *keepAliveVerificationDelay;
    MISSING_TYPE *fatalErrorSoftModeDuration;
    MISSING_TYPE *fatalErrorSoftModeVerificationDelay;
}

@end

