//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC14MainAppLibrary25AppStateMutationProcessor19TransactionDelegate : _TtCs12_SwiftObject
{
    MISSING_TYPE *queue;
    MISSING_TYPE *store;
    MISSING_TYPE *configuration;
    MISSING_TYPE *mutationProcessTracker;
    MISSING_TYPE *criticalEventUploader;
    MISSING_TYPE *chatSessionTransactionListener;
    MISSING_TYPE *chatSessionTransactionTargetIDs;
    MISSING_TYPE *activeMutationTransactionState;
    MISSING_TYPE *pendingActions;
    MISSING_TYPE *mutationProcessor;
}

- (void)handleManagedObjectContextDidSave:(id)arg1;
- (void)handleManagedObjectContextWillSave:(id)arg1;

@end

