//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAPersistentRequest.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary25UserNoticeSetStageRequest : WAPersistentRequest
{
    MISSING_TYPE *log;
    MISSING_TYPE *ID;
    MISSING_TYPE *timestamp;
    MISSING_TYPE *stage;
}

- (void).cxx_destruct;
- (_Bool)canBegin;
- (void)encodeWithCoder:(id)arg1;
- (void)executeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithIdentifier:(id)arg1 input:(id)arg2;

@end

