//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibraryP33_0C9D65D8F508C78BF47C4464F75D533E14FloatingButton : UIButton
{
    MISSING_TYPE *backgroundView;
    MISSING_TYPE *overlayView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

