//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary14CatalogChanges : NSObject
{
    MISSING_TYPE *indexesDeleted;
    MISSING_TYPE *indexesInserted;
    MISSING_TYPE *indexesUpdated;
    MISSING_TYPE *cartEnabled;
    MISSING_TYPE *finishedUpdated;
}

- (void).cxx_destruct;
- (id)init;

@end

