//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibraryP33_14C6CF75F57CE2040D76863A81A5E60817CompressOperation : _TtCs12_SwiftObject
{
    MISSING_TYPE *dataInput;
    MISSING_TYPE *dataOutput;
    MISSING_TYPE *done;
    MISSING_TYPE *stream;
}

@end

