//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAPictureContainerViewController.h"

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary21CatalogViewController : WAPictureContainerViewController
{
    MISSING_TYPE *session;
    MISSING_TYPE *bag;
    MISSING_TYPE *showHeader;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *performanceLogger;
    MISSING_TYPE *catalogForwarder;
    MISSING_TYPE *$__lazy_storage_$_cartButton;
    MISSING_TYPE *$__lazy_storage_$_cartButtonItem;
    MISSING_TYPE *$__lazy_storage_$_moreButtonItem;
    MISSING_TYPE *$__lazy_storage_$_contentStackView;
    MISSING_TYPE *$__lazy_storage_$_landscapeHeaderContainerView;
    MISSING_TYPE *$__lazy_storage_$_catalogHeaderViewController;
    MISSING_TYPE *landscapeProfileHeaderSize;
    MISSING_TYPE *cartButtonItemCountUpdater;
}

- (void).cxx_destruct;
- (void)cartButtonDidTap;
- (id)initWithChatSession:(id)arg1 forJID:(id)arg2;
- (void)onCancelWithSender:(id)arg1;
- (void)openMoreMenu:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end

