//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary46WABizSMBUpsellBannerDebugOptionsViewController : UIViewController
{
    MISSING_TYPE *$__lazy_storage_$_expiryDateLabel;
    MISSING_TYPE *$__lazy_storage_$_datePicker;
    MISSING_TYPE *$__lazy_storage_$_triggerButton;
    MISSING_TYPE *$__lazy_storage_$_revokeButton;
    MISSING_TYPE *$__lazy_storage_$_bannerStateLabel;
}

- (void).cxx_destruct;
- (void)didTapTriggerButtonWithSender:(id)arg1;
- (void)didTapTriggerRevokeNotifButtonWithSender:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end

