//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary30HistorySyncChunkMessageHandler : _TtCs12_SwiftObject
{
    MISSING_TYPE *downloader;
    MISSING_TYPE *decompressor;
    MISSING_TYPE *handlersFactory;
}

@end

