//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WADraggablePopUpViewController.h"

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary23WAGimmickViewController : WADraggablePopUpViewController
{
    MISSING_TYPE *picker;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end

