//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary30NewContactPhoneNumberValidator : NSObject
{
    MISSING_TYPE *checkedPhoneNumber;
    MISSING_TYPE *timer;
    MISSING_TYPE *numberFormatter;
    MISSING_TYPE *delegate;
    MISSING_TYPE *waPhones;
    MISSING_TYPE *nonWAPhones;
}

- (void).cxx_destruct;
- (void)checkPhoneNumberWithTimer:(id)arg1;
- (id)init;

@end

