//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC14MainAppLibrary20GreenAlertFooterView6Action : _TtCs12_SwiftObject
{
    MISSING_TYPE *title;
    MISSING_TYPE *symbol;
    MISSING_TYPE *accessibilityLabel;
    MISSING_TYPE *automationIdentifier;
    MISSING_TYPE *isEnabled;
    MISSING_TYPE *handler;
}

@end

