//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC14MainAppLibrary40PaymentBRMerchantUpdatePayoutBankHandler.h"

@interface _TtC14MainAppLibrary40PaymentBRMerchantUpdatePayoutBankHandler (MainAppLibrary)
- (void)handler:(id)arg1 didFailWithError:(id)arg2;
- (void)handler:(id)arg1 didFailWithUserAction:(long long)arg2;
@end

