//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary23HistorySyncSessionChunk : _TtCs12_SwiftObject
{
    MISSING_TYPE *chunkInfo;
    MISSING_TYPE *state;
    MISSING_TYPE *retryCount;
    MISSING_TYPE *messageID;
}

@end

