//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV14MainAppLibrary6SQLite8Database : _TtCs12_SwiftObject
{
    MISSING_TYPE *pointer;
    MISSING_TYPE *$__lazy_storage_$_statementParser;
    MISSING_TYPE *$__lazy_storage_$_columnParser;
}

@end

