//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString;

@interface _TtC14MainAppLibraryP33_1AC0FA3501B13D90D86C0F6B9AA2BD0E16ReportReasonCell : UITableViewCell
{
}

@property(nonatomic, copy) NSString *accessibilityHint;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

