//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary13CatalogButton : UIButton
{
    MISSING_TYPE *fontMinder;
    MISSING_TYPE *style;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (_Bool)isHighlighted;
- (_Bool)isUserInteractionEnabled;
@property(nonatomic) _Bool highlighted;
@property(nonatomic) _Bool userInteractionEnabled;

@end

