//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC14MainAppLibrary43AppStateRemoteChangeSetMediaUploadOperation.h"

@interface _TtC14MainAppLibrary43AppStateRemoteChangeSetMediaUploadOperation (MainAppLibrary)
- (void)uploadTask:(id)arg1 didFinishWithResult:(id)arg2 uploadEvent:(id)arg3 error:(id)arg4 terminal:(_Bool)arg5;
- (void)uploadTask:(id)arg1 didUpdateProgress:(double)arg2;
- (void)uploadTask:(id)arg1 needUploadReadyAssetFromAsset:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)uploadTask:(id)arg1 willBeginUploadWithMediaKey:(id)arg2 asset:(id)arg3 reuseReason:(unsigned long long)arg4 plaintextHash:(id)arg5 ciphertextHash:(id)arg6;
- (void)uploadTask:(id)arg1 willRetryWithUploadEvent:(id)arg2;
@end

