//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary24HistorySyncMediaUploader : NSObject
{
    MISSING_TYPE *mediaUploadingQueue;
}

- (void).cxx_destruct;
- (id)init;

@end

