//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibraryP33_BB5A9413C308C6A39C7323608ED9C0B946UserSessionPreferencesBadgeStateMachineStorage : _TtCs12_SwiftObject
{
    MISSING_TYPE *internalO;
    MISSING_TYPE *userSessionPreferences;
}

@end

