//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE;

@interface _TtCC14MainAppLibrary48PaymentBRMerchantOnboardingOptionsViewController20OnboardingOptionCell : UITableViewCell
{
    MISSING_TYPE *option;
    MISSING_TYPE *$__lazy_storage_$_iconImageView;
    MISSING_TYPE *$__lazy_storage_$_titleLabel;
    MISSING_TYPE *$__lazy_storage_$_subtitleLabel;
    MISSING_TYPE *$__lazy_storage_$_textStackView;
    MISSING_TYPE *$__lazy_storage_$_contentStackView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutMarginsDidChange;

@end

