//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary46PaymentBRMerchantOwnerInformationConfiguration : _TtCs12_SwiftObject
{
    MISSING_TYPE *prefilledTaxID;
    MISSING_TYPE *navigationTitleView;
    MISSING_TYPE *$__lazy_storage_$_scrolledNavigationTitleView;
    MISSING_TYPE *$__lazy_storage_$_headerView;
    MISSING_TYPE *$__lazy_storage_$_footerView;
    MISSING_TYPE *$__lazy_storage_$_inputTitles;
    MISSING_TYPE *inputLabelWidthMultiplier;
    MISSING_TYPE *nameCell;
    MISSING_TYPE *dobCell;
    MISSING_TYPE *emailCell;
    MISSING_TYPE *cpfCell;
    MISSING_TYPE *leftBarButtonType;
    MISSING_TYPE *rightBarButtonType;
    MISSING_TYPE *prefilledData;
}

@end

