//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@interface _TtCC14MainAppLibrary38MessageProductListScreenViewControllerP33_AA345613933B408086A84CBCAC9DBD1610HeaderView : UITableViewHeaderFooterView
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

