//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary22CatalogToastController : _TtCs12_SwiftObject
{
    MISSING_TYPE *presentingView;
    MISSING_TYPE *currentToastView;
    MISSING_TYPE *dismissTimer;
}

- (void)dismissToast;

@end

