//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAPlaintextMediaDownloadManagerDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary19WAProductImageCache : NSObject <WAPlaintextMediaDownloadManagerDelegate>
{
    MISSING_TYPE *prefix;
    MISSING_TYPE *queue;
    MISSING_TYPE *downloader;
    MISSING_TYPE *downloadTasks;
    MISSING_TYPE *memoryCache;
}

- (void).cxx_destruct;
- (id)cachedImageForEnsemble:(id)arg1 wantFullSizeOriginal:(long long)arg2;
- (id)init;
- (void)plaintextMediaDownloader:(id)arg1 didFailToDownloadMediaForRequest:(id)arg2 error:(id)arg3;
- (void)plaintextMediaDownloader:(id)arg1 didFinishDownloadingMediaForRequest:(id)arg2 toPath:(id)arg3;
- (void)reset;

@end

