//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibraryP33_0AD6F5C9B8DFFAE956567D5580902B7C11SentMessage : _TtCs12_SwiftObject
{
    MISSING_TYPE *pendingUpdates;
    MISSING_TYPE *status;
    MISSING_TYPE *observer;
    MISSING_TYPE *isSendingFailed;
    MISSING_TYPE *stanzaID;
    MISSING_TYPE *peerDevice;
}

@end

