//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary39ProductImageCarouselScrollIndicatorView : UIView
{
    MISSING_TYPE *scrollView;
    MISSING_TYPE *observations;
    MISSING_TYPE *$__lazy_storage_$_trackView;
    MISSING_TYPE *thumbView;
    MISSING_TYPE *$__lazy_storage_$_thumbWidthConstraint;
    MISSING_TYPE *$__lazy_storage_$_thumbLeadingConstraint;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

