//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary10UserNotice : _TtCs12_SwiftObject
{
    MISSING_TYPE *ID;
    MISSING_TYPE *version;
    MISSING_TYPE *greenAlertDebugSettings;
    MISSING_TYPE *stage;
    MISSING_TYPE *timestamp;
    MISSING_TYPE *repeatIndex;
    MISSING_TYPE *repeatDate;
    MISSING_TYPE *noticeContent;
}

@end

