//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary31XMPPBRGetMerchantStatusResponse : _TtCs12_SwiftObject
{
    MISSING_TYPE *merchantExists;
    MISSING_TYPE *banksResponse;
    MISSING_TYPE *verificationType;
    MISSING_TYPE *verificationId;
    MISSING_TYPE *bankCode;
    MISSING_TYPE *bankName;
    MISSING_TYPE *maskedAccountNumber;
    MISSING_TYPE *last4;
    MISSING_TYPE *supportNumber;
}

@end

