//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary18HistorySyncSession : _TtCs12_SwiftObject
{
    MISSING_TYPE *requestFactory;
    MISSING_TYPE *chunkProvider;
    MISSING_TYPE *syncProgress;
    MISSING_TYPE *chunkOrder;
    MISSING_TYPE *config;
    MISSING_TYPE *lastChunkTimestamp;
    MISSING_TYPE *companionDevice;
    MISSING_TYPE *syncType;
    MISSING_TYPE *persistentStateProvider;
    MISSING_TYPE *bootstrapMetrics;
}

@end

