//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC14MainAppLibrary23ContactBlocklistManagerP33_FC2C11EC2E7D9C8DD53AF6AF192780065State : _TtCs12_SwiftObject
{
    MISSING_TYPE *Log;
    MISSING_TYPE *cachedActiveContactBlocklist;
    MISSING_TYPE *sessionPreferences;
    MISSING_TYPE *chatStorage;
    MISSING_TYPE *xmppConnectionMain;
    MISSING_TYPE *v2Enabled;
}

@end

