//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC14MainAppLibrary24PaymentMerchantRequester.h"

@interface _TtC14MainAppLibrary24PaymentMerchantRequester (MainAppLibrary)
- (void)registerHandlersForPersistentRequestManager:(id)arg1;
- (id)sharedObjectKeyForPersistentRequestManager:(id)arg1;
@end

