//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary25AppStatePeerMessageSender : _TtCs12_SwiftObject
{
    MISSING_TYPE *deviceObserver;
    MISSING_TYPE *messageSender;
}

@end

