//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary22ContentDescriptionView : UIView
{
    MISSING_TYPE *config;
    MISSING_TYPE *$__lazy_storage_$_imageView;
    MISSING_TYPE *$__lazy_storage_$_headingLabelView;
    MISSING_TYPE *$__lazy_storage_$_primaryTextLabelView;
    MISSING_TYPE *$__lazy_storage_$_secondaryTextLabelView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

