//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC14MainAppLibrary20GreenAlertFooterView : UIView
{
    MISSING_TYPE *primaryAction;
    MISSING_TYPE *alternativeButton;
    MISSING_TYPE *alternativeAction;
    MISSING_TYPE *showsAlternativeAction;
    MISSING_TYPE *updateButtonContentsInPlace;
    MISSING_TYPE *contentRectLayoutGuide;
    MISSING_TYPE *primaryButton;
    MISSING_TYPE *label;
    MISSING_TYPE *labelContainer;
    MISSING_TYPE *primaryButtonAction;
    MISSING_TYPE *alternativeButtonAction;
}

- (void).cxx_destruct;
- (void)alternativeButtonTapped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)primaryButtonTapped;

@end

