//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WABottomSheetViewController.h"

#import "WABottomSheetHeightChangingDelegate-Protocol.h"
#import "WABottomSheetScrollDelegate-Protocol.h"

@class MISSING_TYPE;
@protocol _TtP14MainAppLibrary35WAListMessageViewControllerDelegate_;

@interface _TtC14MainAppLibrary27WAListMessageViewController : WABottomSheetViewController <WABottomSheetScrollDelegate, WABottomSheetHeightChangingDelegate>
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *selectedItem;
    MISSING_TYPE *cellIdentifier;
    MISSING_TYPE *$__lazy_storage_$_headerView;
    MISSING_TYPE *$__lazy_storage_$_footerView;
    MISSING_TYPE *presentationComplete;
    MISSING_TYPE *delegate;
}

- (void).cxx_destruct;
- (void)bottomSheetViewController:(id)arg1 tableViewDidScrollWithContentOffset:(struct CGPoint)arg2 contentSize:(struct CGSize)arg3;
@property(nonatomic) __weak id <_TtP14MainAppLibrary35WAListMessageViewControllerDelegate_> delegate; // @synthesize delegate;
- (void)didChangeHeight:(double)arg1;
- (void)didFinishTransitionToExpandedHeight;
- (id)extraFooterView;
- (id)extraHeaderView;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(CDStruct_d56d45cf)arg1;
- (id)initWithViewModel:(id)arg1;
- (double)maximumHeight;
- (double)maximumWidth;
- (double)minimumHeight;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)presentFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)viewDidLoad;

@end

