//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol _TtP14MainAppLibrary12CatalogEvent_
@property(nonatomic) double cart_toggle;
@property(nonatomic) double is_order_msg_attached;
@property(nonatomic, copy) NSString *order_id;
@property(nonatomic, copy) NSString *product_id;
@property(nonatomic) double quantity;
@end

