//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WAMessage, _TtC14MainAppLibrary17WAListMessageItem, _TtC14MainAppLibrary27WAListMessageViewController;

@protocol _TtP14MainAppLibrary35WAListMessageViewControllerDelegate_
- (void)listMessageViewControllerWithVc:(_TtC14MainAppLibrary27WAListMessageViewController *)arg1 didTapSendItem:(_TtC14MainAppLibrary17WAListMessageItem *)arg2 fromListMessage:(WAMessage *)arg3;
@end

