//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (TimeShift_WADeviceDate)
- (id)wa_localizedSharingTimeLeftStringForAccessibilityLabel:(_Bool)arg1;
@end

