//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL;

@protocol QLPreviewItem <NSObject>
@property(readonly, nonatomic) NSURL *previewItemURL;

@optional
@property(readonly, nonatomic) NSString *previewItemTitle;
@end

