//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImagePickerController.h>

@interface RotatableImagePickerController : UIImagePickerController
{
}

- (unsigned long long)supportedInterfaceOrientations;

@end

