//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIBezierPath;

@protocol UIDynamicItem <NSObject>
@property(nonatomic, readonly) struct CGRect bounds;
@property(nonatomic) struct CGPoint center;
@property(nonatomic) struct CGAffineTransform transform;

@optional
@property(nonatomic, readonly) UIBezierPath *collisionBoundingPath;
@property(nonatomic, readonly) unsigned long long collisionBoundsType;
@end

