//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIMenuController.h>

@class NSString;

@interface UIMenuController (Actions)
@property(copy, nonatomic) NSString *wa_sendMessageItemTitle;
- (void)wa_installItems;
- (void)wa_reallyInstallItems;
@end

