//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIPickerView;

@protocol UIPickerViewDataSource <NSObject>
- (long long)numberOfComponentsInPickerView:(UIPickerView *)arg1;
- (long long)pickerView:(UIPickerView *)arg1 numberOfRowsInComponent:(long long)arg2;
@end

