//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITraitCollection.h>

@interface UITraitCollection (MainAppLibrary)
- (long long)waUserInterfaceStyle;
@end

