//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

#import "WAAboutTextEditControllerDelegate-Protocol.h"

@class NSIndexPath, UIBarButtonItem;

@interface WAAboutListViewController : WAStaticTableViewController <WAAboutTextEditControllerDelegate>
{
    UIBarButtonItem *_editButton;
    NSIndexPath *_editIndexPath;
}

- (void).cxx_destruct;
- (void)aboutTextEditController:(id)arg1 didFinishWithText:(id)arg2;
- (void)addSpinnerToTableViewCell:(id)arg1;
- (void)changeAbout:(id)arg1;
- (void)chatManagerDidUpdateStatus:(id)arg1;
- (void)doneAction:(id)arg1;
- (void)editAction:(id)arg1;
- (id)init;
- (void)presentStatusUpdateFailedAlert;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setUpTableView;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)updateNavigationBarButtons;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)wa_applicationDidEnterBackground;

@end

