//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, WAAboutTextEditController;

@protocol WAAboutTextEditControllerDelegate
- (void)aboutTextEditController:(WAAboutTextEditController *)arg1 didFinishWithText:(NSString *)arg2;
@end

