//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

#import "WANavigationDeepLinkHandler-Protocol.h"
#import "WARestorable-Protocol.h"

@class NSString;

@interface WAAccountViewController : WAStaticTableViewController <WARestorable, WANavigationDeepLinkHandler>
{
}

- (void)changeNumberAction;
- (void)deleteAccountAction;
- (void)handleDeepLinkAction:(unsigned long long)arg1;
- (id)init;
- (void)logoutAction;
- (void)openDataReportScreenAnimated:(_Bool)arg1;
- (void)setPrivacyAction;
- (void)setUpTableView;
- (void)show2FASettings;
- (void)showAccountSecuritySettings;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

