//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSSet;

@interface WAAccountSyncQuery : NSObject
{
    MISSING_TYPE *userJIDs;
    MISSING_TYPE *completions;
}

- (void).cxx_destruct;
- (id)addingUserJIDs:(id)arg1;
- (id)addingUserJIDs:(id)arg1 with:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (long long)completionCountWithDataType:(long long)arg1;
- (void)enumerateCompletionsWithDataType:(long long)arg1 handler:(CDUnknownBlockType)arg2;
- (id)init;
- (id)initWithUserJIDs:(id)arg1;
- (id)initWithUserJIDs:(id)arg1 dataType:(long long)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic, readonly) NSSet *userJIDs;

@end

