//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, WALinkLabel;

@interface WAAccountSecurityHeaderView : UIView
{
    WALinkLabel *_textLabel;
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)installLayoutConstraints;
@property(readonly, nonatomic) WALinkLabel *textLabel; // @synthesize textLabel=_textLabel;

@end

