//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WATableViewController.h>

@class NSArray, NSDictionary;
@protocol WAAddressBookCountryPickerDelegate;

@interface WAAddressBookCountryPicker : WATableViewController
{
    NSArray *_sectionTitles;
    NSDictionary *_countryMap;
    id <WAAddressBookCountryPickerDelegate> _delegate;
}

+ (id)pickerWithDelegate:(id)arg1;
- (void).cxx_destruct;
- (void)cancelAction:(id)arg1;
- (id)countryInfoForTableIndexPath:(id)arg1;
@property(nonatomic) __weak id <WAAddressBookCountryPickerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithStyle:(long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)wa_fontSizeDidChange;

@end

