//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

@class WATableRow;

@interface WAAllowedNetworkInterfacesPicker : WAStaticTableViewController
{
    WATableRow *_neverRow;
    WATableRow *_wifiRow;
    WATableRow *_cellularRow;
    unsigned long long _mediaType;
}

- (void).cxx_destruct;
- (id)initForMediaType:(unsigned long long)arg1 title:(id)arg2;
- (void)selectInterface:(long long)arg1;
- (void)setUpTableView;
- (id)uniqueIdentifier;
- (void)updateCheckMarks;
- (void)viewDidLoad;

@end

