//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAStorageManagedObject.h>

@class NSData, NSDate;

@interface WAAppStateEncryptionKeyEntity : WAStorageManagedObject
{
}

- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;

// Remaining properties
@property(nonatomic, copy) NSDate *creationDate; // @dynamic creationDate;
@property(nonatomic, copy) NSData *data; // @dynamic data;
@property(nonatomic) long long deviceID; // @dynamic deviceID;
@property(nonatomic) long long epoch; // @dynamic epoch;
@property(nonatomic, copy) NSData *fingerprint; // @dynamic fingerprint;
@property(nonatomic, copy) NSDate *staleSince; // @dynamic staleSince;

@end

