//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAAutoscrollingLabel;

@protocol WAAutoScrollingLabelDelegate <NSObject>
- (void)autoscrollingLabelDidFinishScrolling:(WAAutoscrollingLabel *)arg1;
@end

