//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageSlicer.h"

@interface WAAutoPlayVideoMessageSlicer : WAMessageSlicer
{
}

- (id)contentSlices:(id)arg1 isFirstSlice:(_Bool)arg2;

@end

