//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject, NSString;
@protocol OS_dispatch_queue, WABackgroundTaskDelegate;

@protocol WABackgroundTask <NSObject>
+ (NSString *)identifier;
+ (NSObject<OS_dispatch_queue> *)queue;
+ (_Bool)repeated;
@property(nonatomic) __weak id <WABackgroundTaskDelegate> delegate;
- (void)launchTask;
- (void)taskExpired;
@end

