//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSNumber;

@interface WABackupInformation : NSObject
{
    NSDictionary *_data;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *backupKeyType;
@property(copy, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(readonly, nonatomic) NSDate *date;
@property(readonly, nonatomic) _Bool exists;
@property(readonly, nonatomic) NSDictionary *fileSizes;
@property(readonly, nonatomic) NSNumber *includeVideos;
- (id)init;
- (id)initWithBackupInformation:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)logWithMessage:(id)arg1;
- (void)postUpdatedNotification;
- (_Bool)replaceData:(id)arg1;
@property(readonly, nonatomic) NSNumber *size;
@property(readonly, nonatomic) NSNumber *sizeOfMedia;
@property(readonly, nonatomic) NSNumber *sizeOfVideos;
@property(readonly, nonatomic) NSNumber *version;

@end

