//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WATarFile.h"

@class NSData, NSString, WAOffsetsFile;
@protocol WABackupTarFileEncryptionKey;

@interface WABackupChatMediaTarFile : WATarFile
{
    NSString *_prefix;
    unsigned long long _fileIndex;
    WAOffsetsFile *_offsets;
    NSData<WABackupTarFileEncryptionKey> *_encryptionKey;
    long long _suggestedMinimumTimestamp;
    long long _minimumCreationTimestamp;
    _Bool _eofWritten;
    NSString *_uniqueIdentifier;
}

+ (id)appendPath:(id)arg1 toURL:(id)arg2;
+ (id)indexPathForGroup:(unsigned long long)arg1 andFile:(unsigned long long)arg2;
+ (_Bool)isAuxiliaryFileAtPath:(id)arg1;
+ (id)recommendedAuxiliaryFileForPath:(id)arg1;
+ (unsigned long long)runWorkaroundForIdentifier:(id)arg1 fileList:(id)arg2 pathPrefix:(id)arg3 shouldCancel:(CDUnknownBlockType)arg4;
+ (unsigned long long)verifyTarFileForFileHandle:(id)arg1 usingEncryptionKey:(id)arg2 cancellationBlock:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (id)absolutePathForItem:(id)arg1;
- (_Bool)addEndOfFileMarker:(id *)arg1;
- (_Bool)addFileAtURL:(id)arg1 plaintextHashHint:(id)arg2 error:(id *)arg3;
- (unsigned long long)addFilesAtURLs:(id)arg1 toTarDirectoryPath:(id)arg2 plaintextHashHint:(id)arg3 withCancellationCheck:(CDUnknownBlockType)arg4 failedIndices:(id *)arg5 criticalError:(id *)arg6;
- (unsigned long long)addFilesAtURLs:(id)arg1 toTarDirectoryPath:(id)arg2 withCancellationCheck:(CDUnknownBlockType)arg3 failedIndices:(id *)arg4 criticalError:(id *)arg5;
- (_Bool)addLinkAtPath:(id)arg1 toRelativePath:(id)arg2 error:(id *)arg3;
- (id)buildPathsForFileList:(id)arg1 withCancellationCheck:(CDUnknownBlockType)arg2;
- (_Bool)canUseAuxiliaryFile;
- (void)closeFile;
- (_Bool)closeFile:(id *)arg1;
- (unsigned long long)extractFileWithMetadata:(id)arg1 atOffset:(unsigned long long)arg2 toURL:(id)arg3 usingRelativeURL:(id)arg4 temporaryURL:(id)arg5 withCancellationCheck:(CDUnknownBlockType)arg6;
- (unsigned long long)extractToDirectoryAtURL:(id)arg1 usingTemporaryURL:(id)arg2 startingAt:(id)arg3 withCancellationCheck:(CDUnknownBlockType)arg4;
- (unsigned long long)extractToPath:(id)arg1 withMetadata:(id)arg2 cancellationCheck:(CDUnknownBlockType)arg3;
- (_Bool)fileAlreadyExtractedForContentMetadata:(id)arg1 inDirectory:(id)arg2;
- (unsigned long long)findStartingGroupIndexForPaths:(id)arg1 withCancellationBlock:(CDUnknownBlockType)arg2;
- (id)headerForLinkAtPath:(id)arg1 toRelativePath:(id)arg2;
- (id)initWithHandle:(id)arg1 mode:(unsigned long long)arg2 commonPrefix:(id)arg3 encryptionKey:(id)arg4;
- (id)initWithPath:(id)arg1 mode:(unsigned long long)arg2 commonPrefix:(id)arg3 encryptionKey:(id)arg4;
- (id)initWithPath:(id)arg1 mode:(unsigned long long)arg2 encryptionKey:(id)arg3;
- (unsigned long long)internalExtractFileWithMetadata:(id)arg1 toURL:(id)arg2 usingRelativeURL:(id)arg3 temporaryURL:(id)arg4 withCancellationCheck:(CDUnknownBlockType)arg5;
- (id)nameForFilePath:(id)arg1 inTarDirectoryPath:(id)arg2;
- (id)nextCreationDate;
- (_Bool)setFileList:(id)arg1 plaintextHashCache:(id)arg2 error:(id *)arg3 shouldCancel:(CDUnknownBlockType)arg4;
- (void)setMinimumCreationTimestampSuggestion:(long long)arg1;
@property(copy, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(readonly, nonatomic) CDUnknownBlockType tarSearchContentMetadataProvider;
- (void)useAuxiliaryFileAtPath:(id)arg1;
- (void)useAuxiliaryFileAtPath:(id)arg1 withFileCount:(unsigned long long)arg2;

@end

