//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/XMPPRequest.h>

@class MISSING_TYPE;

@interface WABackupEncryptedBackupBeginLoginRequest : XMPPRequest
{
    MISSING_TYPE *completionHandler;
}

- (void).cxx_destruct;
- (void)didFailWithError:(id)arg1;
- (void)didSucceedWithResponse:(id)arg1;
- (id)initWithL1:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithTimeout:(double)arg1;

@end

