//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIActivity.h>

@interface WABaseShareActivity : UIActivity
{
}

+ (long long)activityCategory;
+ (void)initialize;
- (id)activityImage;
- (id)activitySettingsImage;
- (id)activityTitle;
- (id)wa_activitySettingsIcon;

@end

