//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface WABackupIcon : UIView
{
    unsigned long long _style;
    unsigned long long _state;
    UIImageView *_image;
    UIImageView *_backgroundImage;
}

+ (id)imageForState:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIImageView *image; // @synthesize image=_image;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithStyle:(unsigned long long)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_style;
- (void)updateAnimation;
- (void)updateIcon;

@end

