//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

@class NSArray, WABiometricPrivacy, WATableRow, WATableSection;

@interface WABiometrySettingsViewController : WAStaticTableViewController
{
    WATableSection *_timeoutSettingsSection;
    WATableRow *_switchRow;
    NSArray *_timeoutRows;
    _Bool _timeoutSettingsHidden;
    WABiometricPrivacy *_biometricPrivacy;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WABiometricPrivacy *biometricPrivacy; // @synthesize biometricPrivacy=_biometricPrivacy;
- (void)changeBiometricSetting:(id)arg1;
- (id)initWithBiometricPrivacy:(id)arg1;
@property(nonatomic, getter=isTimeoutSettingsHidden) _Bool timeoutSettingsHidden; // @synthesize timeoutSettingsHidden=_timeoutSettingsHidden;
- (void)selectRow:(id)arg1;
- (void)setCheckmarkHidden:(_Bool)arg1 forRow:(id)arg2;
- (void)setUpTableView;

@end

