//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "WAPopupActionMenuSupport-Protocol.h"

@class NSArray, NSString, UIColor, UILabel, _TtC14MainAppLibrary21WAMapPreviewImageView;

@interface WABizLocationTableViewCell : UITableViewCell <WAPopupActionMenuSupport>
{
    NSString *_placeholder;
    struct UIEdgeInsets _cellInsets;
    unsigned long long _style;
    UIColor *_placeholderTextColor;
    _TtC14MainAppLibrary21WAMapPreviewImageView *_mapImageView;
    UILabel *_addressLabel;
    NSArray *_currentConstraints;
    struct CLLocationCoordinate2D _coordinate;
}

+ (_Bool)isCoordinate:(struct CLLocationCoordinate2D)arg1 equalsToCoordinate:(struct CLLocationCoordinate2D)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)configureWithAddress:(id)arg1 coordinate:(struct CLLocationCoordinate2D)arg2;
@property(nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
@property(copy, nonatomic) NSArray *currentConstraints; // @synthesize currentConstraints=_currentConstraints;
- (void)disableEditing;
- (id)initWithAddress:(id)arg1 coordinate:(struct CLLocationCoordinate2D)arg2 style:(unsigned long long)arg3 placeholderText:(id)arg4;
- (id)initWithAddress:(id)arg1 coordinate:(struct CLLocationCoordinate2D)arg2 style:(unsigned long long)arg3 placeholderText:(id)arg4 placeholderTextColor:(id)arg5;
- (void)installConstraints;
@property(retain, nonatomic) _TtC14MainAppLibrary21WAMapPreviewImageView *mapImageView; // @synthesize mapImageView=_mapImageView;
- (double)mapPreviewVerticalMarginForCurrentStyle;
- (void)performAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)shouldShowPopupActionMenu;

@end

