//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAPersistentRequest.h>

@class WAUserJID;

@interface WABizVerifiedNamesRequest : WAPersistentRequest
{
    WAUserJID *_userJID;
    long long _counter;
}

+ (id)identifierPrefixForUserJID:(id)arg1;
- (void).cxx_destruct;
- (_Bool)canBegin;
@property(readonly, nonatomic) long long counter; // @synthesize counter=_counter;
- (void)encodeWithCoder:(id)arg1;
- (void)executeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)handleRequestError:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUserJID:(id)arg1 initialDelay:(double)arg2;
- (id)initWithUserJID:(id)arg1 initialDelay:(double)arg2 counter:(long long)arg3;
@property(readonly, nonatomic) WAUserJID *userJID; // @synthesize userJID=_userJID;

@end

