//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WABizProfilePresenter : NSObject
{
}

+ (void)presentBizProfileForContact:(id)arg1 presentingViewController:(id)arg2;
- (id)init;

@end

