//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WABloksEncActionProcessor;

@interface WABloksXMPPProcessor : NSObject
{
    WABloksEncActionProcessor *_actionProcessor;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WABloksEncActionProcessor *actionProcessor; // @synthesize actionProcessor=_actionProcessor;
- (void)chainNextStepWithOp:(int)arg1 data:(id)arg2 accessTokenData:(id)arg3 successHandler:(CDUnknownBlockType)arg4 errorHandler:(CDUnknownBlockType)arg5;
- (void)createFBID:(id)arg1 successHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;
- (void)deleteFBID:(id)arg1 callbackQueue:(id)arg2 successHandler:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4;
- (void)getCertificate:(id)arg1 successHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;
- (void)refreshFBID:(id)arg1 callbackQueue:(id)arg2 successHandler:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4;
- (void)responseDataHandlerForGetCertificate:(id)arg1 successHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;

@end

