//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WABloksKitActionHandler-Protocol.h"

@class NSString;

@interface WABloksActionHandlerImpl : NSObject <WABloksKitActionHandler>
{
}

- (void)acceptUserNoticeWithCurrentContext:(id)arg1;
- (void)applyNavigationBarConfiguration:(id)arg1 currentContext:(id)arg2;
- (void)assertNonNullBloksContext:(id)arg1;
- (void)closeScreenWithCurrentContext:(id)arg1;
- (void)dismissBottomSheetWithOnDismissAction:(CDUnknownBlockType)arg1 currentContext:(id)arg2;
- (void)displayBottomSheet:(id)arg1 currentContext:(id)arg2 navBarConfig:(id)arg3 onDismissAction:(CDUnknownBlockType)arg4;
- (void)displayModalWithTitle:(id)arg1 message:(id)arg2 currentContext:(id)arg3;
- (void)fetchAsyncActionWithAppID:(id)arg1 params:(id)arg2 callbackQueue:(id)arg3 currentContext:(id)arg4 successHandler:(CDUnknownBlockType)arg5 errorHandler:(CDUnknownBlockType)arg6;
- (void)invalidatePreloadWithAppID:(id)arg1 params:(id)arg2 options:(id)arg3 currentContext:(id)arg4;
- (void)logCriticalEventWithEnum:(long long)arg1 context:(id)arg2;
- (void)logEventWithName:(id)arg1 code:(id)arg2 channel:(id)arg3 sampleRate:(id)arg4 fields:(id)arg5 currentContext:(id)arg6;
- (void)openActionSheetWithConfiguration:(id)arg1 currentContext:(id)arg2;
- (void)openChatWithJIDString:(id)arg1 prefilledMessage:(id)arg2 currentContext:(id)arg3;
- (void)openContactInfoWithJIDString:(id)arg1 currentContext:(id)arg2;
- (void)openMediaBrowserWithMedia:(id)arg1 selectedIndex:(id)arg2 title:(id)arg3 subtitle:(id)arg4 currentContext:(id)arg5;
- (void)openScreenWithAppID:(id)arg1 params:(id)arg2 options:(id)arg3 currentContext:(id)arg4;
- (void)openURL:(id)arg1 currentContext:(id)arg2;
- (void)popBottomSheet:(id)arg1;
- (void)preloadWithAppID:(id)arg1 params:(id)arg2 options:(id)arg3 currentContext:(id)arg4;
- (void)presentFXWebAuthFlowWithInitialURL:(id)arg1 callbackURLScheme:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 currentContext:(id)arg4;
- (void)pushBottomSheet:(id)arg1 currentContext:(id)arg2 navBarConfig:(id)arg3 onDismissAction:(CDUnknownBlockType)arg4;
- (void)shareTextViaWhatsApp:(id)arg1 currentContext:(id)arg2;
- (void)shareViaSystemActivityWithConfiguration:(id)arg1 currentContext:(id)arg2;
- (void)userDidAcceptPrivacyNoticeVersion:(id)arg1 currentContext:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

