//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WABloksNavigationBarButtonConfigurationProxy : NSObject
{
}

+ (id)newWithTitle:(id)arg1 icon:(long long)arg2 action:(CDUnknownBlockType)arg3;

@end

