//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WABloksNavigationBarDefaultHandler.h"

@interface WABloksNavigationBarWithIconHandler : WABloksNavigationBarDefaultHandler
{
}

- (void)titleApplyNavigationBarConfiguration:(id)arg1 toViewController:(id)arg2;

@end

