//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WABloksMosaicDiskCacheProxy : NSObject
{
}

+ (id)newMosaicDiskCacheWithCacheName:(id)arg1 diskCacheSizeInBytes:(unsigned long long)arg2 backgroundManager:(id)arg3;

@end

