//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WABottomSheetViewController;

@protocol WABottomSheetScrollDelegate <NSObject>

@optional
- (void)bottomSheetViewController:(WABottomSheetViewController *)arg1 tableViewDidScrollWithContentOffset:(struct CGPoint)arg2 contentSize:(struct CGSize)arg3;
@end

