//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface WABottomSheetHandleImageView : UIImageView
{
    CDUnknownBlockType _closeAction;
}

- (void).cxx_destruct;
- (_Bool)accessibilityActivate;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)initWithCloseAction:(CDUnknownBlockType)arg1;
- (_Bool)isAccessibilityElement;

@end

