//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WACalloutViewPresenter;

@protocol WACalloutViewPresenterDelegate <NSObject>
- (void)calloutViewPresenterDidFinish:(WACalloutViewPresenter *)arg1;
- (struct UIEdgeInsets)overlayInsetsForCalloutViewPresenter:(WACalloutViewPresenter *)arg1;
@end

