//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol WACallSpamReportViewDelegate;

@interface WACallSpamReportView : UIView
{
    id <WACallSpamReportViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)blockButtonTapped:(id)arg1;
@property(nonatomic) __weak id <WACallSpamReportViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)notSpamButtonTapped:(id)arg1;
- (void)reportButtonTapped:(id)arg1;

@end

