//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImage, UIImageView, WAAutoscrollingLabel, WAGradientView;
@protocol WACallVideoOverlayViewDelegate;

@interface WACallVideoOverlayView : UIView
{
    UIView *_overlayDimmingView;
    WAGradientView *_muteIndicatorShadowView;
    UIImageView *_muteIndicatorImageView;
    UIView *_overlayInfoContainerView;
    WAAutoscrollingLabel *_overlayInfoLabelView;
    UIImageView *_overlayInfoImageView;
    UIButton *_cancelButton;
    double _borderMargin;
    double _currentAngle;
    long long _muteSide;
    _Bool _showActionView;
    id <WACallVideoOverlayViewDelegate> _delegate;
    long long _actionViewPosition;
    struct UIEdgeInsets _landscapeMargins;
}

- (void).cxx_destruct;
- (void)actionButtonPressed:(id)arg1;
@property(nonatomic) long long actionViewPosition; // @synthesize actionViewPosition=_actionViewPosition;
- (double)actualHeight;
- (struct UIEdgeInsets)actualLandscapeMarginsInset;
- (double)actualWidth;
- (struct CGSize)containerSize;
@property(nonatomic) __weak id <WACallVideoOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)hideMuteIndicator;
- (id)init;
- (_Bool)landscapeLeft;
@property(nonatomic) struct UIEdgeInsets landscapeMargins; // @synthesize landscapeMargins=_landscapeMargins;
- (_Bool)landscapeRight;
- (void)layoutMuteElements;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImage *overlayInfoImage;
- (_Bool)portrait;
- (void)positionCenterView:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)rotateToAngle:(double)arg1;
- (void)setOverlayDimmingViewAlpha:(double)arg1;
- (void)setOverlayInfoText:(id)arg1;
@property(nonatomic) _Bool showActionView; // @synthesize showActionView=_showActionView;
@property(nonatomic) _Bool showCancelButton;
- (void)showMuteIndicatorWithShadowType:(long long)arg1 side:(long long)arg2 intenseGradient:(_Bool)arg3 longMargin:(_Bool)arg4;
- (struct CGSize)sizeThatFitsTextLabel;
- (void)updateOverlayDimmingView;
- (_Bool)upsideDown;
- (double)yActionPosition;

@end

