//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSDate, NSDecimalNumber, NSString, WAUserJID;

@interface WACatalogOrder : NSObject
{
    MISSING_TYPE *orderID;
    MISSING_TYPE *creationDate;
    MISSING_TYPE *totalPrice;
    MISSING_TYPE *subtotalPrice;
    MISSING_TYPE *currencyCode;
    MISSING_TYPE *businessOwnerJID;
    MISSING_TYPE *items;
    MISSING_TYPE *$__lazy_storage_$_itemCount;
    MISSING_TYPE *$__lazy_storage_$_localizedSubtotalPrice;
    MISSING_TYPE *$__lazy_storage_$_localizedTotalPrice;
}

- (void).cxx_destruct;
@property(nonatomic, readonly) WAUserJID *businessOwnerJID; // @synthesize businessOwnerJID;
@property(nonatomic, readonly) NSDate *creationDate;
@property(nonatomic, readonly) NSString *currencyCode;
- (id)init;
- (id)initWithBusinessOwnerJID:(id)arg1 orderID:(id)arg2 totalPrice:(id)arg3 subtotalPrice:(id)arg4 currencyCode:(id)arg5 items:(id)arg6 creationDate:(id)arg7;
@property(nonatomic) long long itemCount;
@property(nonatomic, readonly) NSArray *items;
@property(nonatomic, copy) NSString *localizedSubtotalPrice;
@property(nonatomic, copy) NSString *localizedTotalPrice;
@property(nonatomic, readonly) NSString *orderID;
@property(nonatomic, readonly) NSDecimalNumber *subtotalPrice; // @synthesize subtotalPrice;
@property(nonatomic, readonly) NSDecimalNumber *totalPrice; // @synthesize totalPrice;

@end

