//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WABubbleTextView.h"

@class WACallParticipant;

@interface WACallVideoBubbleView : WABubbleTextView
{
    WACallParticipant *_selfParticipant;
    WACallParticipant *_peerParticipant;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WACallParticipant *peerParticipant; // @synthesize peerParticipant=_peerParticipant;
@property(retain, nonatomic) WACallParticipant *selfParticipant; // @synthesize selfParticipant=_selfParticipant;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateString;

@end

