//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString, UIView, WACallEvent, WACallInfo, WADeviceJID, WAUserJID, XMPPCallStanza;

@protocol WACallVoipBridgeDelegate <NSObject>
- (void)voipBridgeCallIsEndingWithCallEvent:(WACallEvent *)arg1 shouldAddEvent:(_Bool)arg2 showRatingInterval:(double)arg3 callID:(NSString *)arg4;
- (void)voipBridgeDidAckCallOffer;
- (void)voipBridgeDidChangeGroupInfo;
- (void)voipBridgeDidChangeToCallState:(int)arg1 fromCallState:(int)arg2 processedElsewhere:(_Bool)arg3;
- (void)voipBridgeDidChangeToCallWaitingState:(unsigned long long)arg1;
- (void)voipBridgeDidCreateSoundPort;
- (void)voipBridgeDidCreateVideoRenderView:(UIView *)arg1 forParticipantJID:(WAUserJID *)arg2;
- (void)voipBridgeDidFailRelayBindsWithBadASN:(_Bool)arg1;
- (void)voipBridgeDidFailToAcceptVideoUpgradeRequest;
- (void)voipBridgeDidFailToAddParticipantJID:(WAUserJID *)arg1 error:(unsigned long long)arg2;
- (void)voipBridgeDidFailToCancelVideoUpgradeRequest;
- (void)voipBridgeDidFailToChangeToCallWaitingState:(unsigned long long)arg1;
- (void)voipBridgeDidFailToCreateVideoRenderView;
- (void)voipBridgeDidFailToCreateVideoStream;
- (void)voipBridgeDidFailToDecryptWithPeerJID:(WADeviceJID *)arg1 callID:(NSString *)arg2 registrationID:(unsigned int)arg3 retryCount:(unsigned char)arg4;
- (void)voipBridgeDidFailToEndCall;
- (void)voipBridgeDidFailToProcessAcceptAckWithCode:(int)arg1 rawJid:(WAUserJID *)arg2;
- (void)voipBridgeDidFailToProcessOfferAck;
- (void)voipBridgeDidFailToProcessPreaccept;
- (void)voipBridgeDidFailToRejectVideoUpgradeRequest;
- (void)voipBridgeDidFailToRejoinCall;
- (void)voipBridgeDidFinishProcessOffer;
- (void)voipBridgeDidNackCallOfferWithGenericError;
- (void)voipBridgeDidNackCallOfferWithGroupCallError:(unsigned long long)arg1 withJIDs:(NSArray *)arg2;
- (void)voipBridgeDidNackCallOfferWithNackError:(unsigned long long)arg1 withJIDs:(NSArray *)arg2;
- (void)voipBridgeDidReceiveAutoRejectCallWithCallID:(NSString *)arg1;
- (void)voipBridgeDidReceiveByeSignal;
- (void)voipBridgeDidReceiveGenericMediaFailure;
- (void)voipBridgeDidReceiveLowBatteryWarning;
- (void)voipBridgeDidReceiveLowBatteryWarningForPeerJID:(WAUserJID *)arg1;
- (void)voipBridgeDidReceiveMissedCallFromJID:(WAUserJID *)arg1 videoCall:(_Bool)arg2 timeIntervalSinceCallOffer:(double)arg3 participantInfos:(NSArray *)arg4 abTestBucket:(NSString *)arg5 groupCall:(_Bool)arg6 callID:(NSString *)arg7 isJoinableCall:(_Bool)arg8;
- (void)voipBridgeDidReceivePreaccept;
- (void)voipBridgeDidReceiveTerminateForCall:(NSString *)arg1 fromCarrierBlock:(_Bool)arg2;
- (void)voipBridgeDidRequestDeviceSyncWithUsers:(NSDictionary *)arg1;
- (void)voipBridgeDidRequestGroupUpdateJoinableCallLogWithCallID:(NSString *)arg1 participantJIDs:(NSArray *)arg2;
- (void)voipBridgeDidRequestTerminateJoinableCallLogWithCallID:(NSString *)arg1;
- (void)voipBridgeDidRequestToPlaySoundOfType:(unsigned long long)arg1;
- (void)voipBridgeDidRequestVoipParamsProcessForStanza:(XMPPCallStanza *)arg1;
- (void)voipBridgeDidSwitchFromWiFiToCellular;
- (void)voipBridgeDidTimeoutPacketStream;
- (void)voipBridgeDidUpdateToCallInfo:(WACallInfo *)arg1;
- (void)voipBridgeHandleCallFatal:(int)arg1;
- (void)voipBridgeParticipantJID:(WAUserJID *)arg1 didLeaveGroupCallWithReason:(unsigned long long)arg2;
- (void)voipBridgeParticipantJID:(WAUserJID *)arg1 didRejectWithReason:(unsigned long long)arg2;
- (void)voipBridgePeerDidChangeToVideoState:(unsigned long long)arg1;
- (void)voipBridgePreprocessStanza:(XMPPCallStanza *)arg1 completion:(void (^)(_Bool, _Bool, int))arg2;
- (void)voipBridgeSelfDidChangeToVideoState:(unsigned long long)arg1;
- (_Bool)voipBridgeShouldPreprocessStanza:(XMPPCallStanza *)arg1;
- (void)voipBridgeVideoCodecMismatch;
@end

