//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WACallInfoView;

@protocol WACallInfoViewDelegate
- (void)callInfoViewInfoButtonPressed:(WACallInfoView *)arg1;
@end

