//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WACardNavigationController;

@protocol WACardNavigationControllerDelegate <NSObject>
- (void)cardNavigationController:(WACardNavigationController *)arg1 opaqueFrameDidChange:(struct CGRect)arg2;
- (void)cardNavigationControllerDidPopLastViewController:(WACardNavigationController *)arg1;

@optional
- (void)cardNavigationControllerStatusSelected:(WACardNavigationController *)arg1;
@end

