//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, WAUserJID;

@interface WACallParticipantInfo : NSObject
{
    MISSING_TYPE *jid;
    MISSING_TYPE *state;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithJID:(id)arg1 participantState:(unsigned long long)arg2;
@property(nonatomic, readonly) WAUserJID *jid; // @synthesize jid;
@property(nonatomic, readonly) unsigned long long state; // @synthesize state;

@end

