//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WACameraHardwareButtonController;

@protocol WACameraHardwareButtonControllerDelegate
- (void)cameraHardwareButtonControllerDidBeginLongPress:(WACameraHardwareButtonController *)arg1;
- (void)cameraHardwareButtonControllerDidBeginPress:(WACameraHardwareButtonController *)arg1;
- (void)cameraHardwareButtonControllerDidEndPress:(WACameraHardwareButtonController *)arg1;
- (_Bool)shouldCameraHardwareButtonControllerHandleButtonEvent:(WACameraHardwareButtonController *)arg1;
@end

