//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, WATableRow, WATableSection;
@protocol WACatalogSectionHandlerDelegate;

@interface WACatalogSectionHandler : NSObject
{
    MISSING_TYPE *sectionBizCatalog;
    MISSING_TYPE *rowBizCatalog;
    MISSING_TYPE *delegate;
    MISSING_TYPE *bizProfile;
    MISSING_TYPE *headerView;
    MISSING_TYPE *catalogPresenter;
    MISSING_TYPE *$__lazy_storage_$_catalogSectionVC;
    MISSING_TYPE *hostingViewController;
    MISSING_TYPE *session;
    MISSING_TYPE *performanceLogger;
}

- (void).cxx_destruct;
- (void)addBizCatalogSectionIfNeeded;
- (id)catalogSectionHeaderView;
@property(nonatomic) __weak id <WACatalogSectionHandlerDelegate> delegate; // @synthesize delegate;
- (id)init;
- (id)initWithBusinessProfile:(id)arg1 hostingViewController:(id)arg2 delegate:(id)arg3 session:(id)arg4 entryPoint:(long long)arg5;
- (void)resetSection;
@property(nonatomic, retain) WATableRow *rowBizCatalog; // @synthesize rowBizCatalog;
@property(nonatomic, retain) WATableSection *sectionBizCatalog; // @synthesize sectionBizCatalog;
- (void)seeAll;

@end

