//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSMutableArray, UILabel;

@interface WACallEventsTableViewCell : UITableViewCell
{
    NSMutableArray *_customConstraints;
    UILabel *_dateLabel;
    NSMutableArray *_timeLabels;
    NSMutableArray *_eventLabels;
    NSMutableArray *_durationLabels;
}

- (void).cxx_destruct;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (void)addCustomConstraints:(id)arg1;
- (void)configureWithAggregateCallEvent:(id)arg1;
- (id)descriptionAttributedStringForCallEvent:(id)arg1;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (_Bool)requiresTwoLines;
- (void)updateConstraints;

@end

