//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol MTLBuffer, MTLTexture;

@interface WACallMetalRenderBufElem : NSObject
{
    MISSING_TYPE *_frameSize;
    unsigned int _fmt_id;
    id <MTLBuffer> _texture_buf;
    id <MTLTexture> _textures[3];
    int stride[3];
}

- (void).cxx_destruct;

@end

