//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSNumber, NSString, WAGroupJID, WAUserJID;

@interface WACallOfferInfo : NSObject
{
    MISSING_TYPE *callID;
    MISSING_TYPE *groupJID;
    MISSING_TYPE *fromJID;
    MISSING_TYPE *callPeerParticipantInfos;
    MISSING_TYPE *callPeerParticipantJIDs;
    MISSING_TYPE *isGroupCall;
    MISSING_TYPE *isVideoCall;
    MISSING_TYPE *isJoinable;
    MISSING_TYPE *isResuming;
    MISSING_TYPE *creatorJID;
    MISSING_TYPE *isOffline;
    MISSING_TYPE *receivedFromPush;
    MISSING_TYPE *pushName;
    MISSING_TYPE *secondsSinceCallOffer;
    MISSING_TYPE *peerPlatform;
    MISSING_TYPE *peerVersion;
    MISSING_TYPE *abTestBucket;
}

- (void).cxx_destruct;
@property(nonatomic, copy) NSString *abTestBucket;
@property(nonatomic, readonly) NSString *callID;
@property(nonatomic, readonly) NSArray *callPeerParticipantInfos;
@property(nonatomic, readonly) NSArray *callPeerParticipantJIDs;
@property(nonatomic, retain) WAUserJID *creatorJID; // @synthesize creatorJID;
@property(nonatomic, readonly) WAUserJID *fromJID; // @synthesize fromJID;
@property(nonatomic, readonly) WAGroupJID *groupJID; // @synthesize groupJID;
- (id)init;
- (id)initWithCallID:(id)arg1 groupJID:(id)arg2 fromJID:(id)arg3 callPeerParticipantInfos:(id)arg4 callPeerParticipantJIDs:(id)arg5 isGroupCall:(_Bool)arg6 isVideoCall:(_Bool)arg7 isJoinable:(_Bool)arg8 isResuming:(_Bool)arg9;
@property(nonatomic, readonly) _Bool isGroupCall; // @synthesize isGroupCall;
@property(nonatomic, readonly) _Bool isJoinable; // @synthesize isJoinable;
@property(nonatomic) _Bool isOffline; // @synthesize isOffline;
@property(nonatomic, readonly) _Bool isResuming; // @synthesize isResuming;
@property(nonatomic, readonly) _Bool isVideoCall; // @synthesize isVideoCall;
@property(nonatomic, copy) NSString *peerPlatform;
@property(nonatomic, copy) NSString *peerVersion;
@property(nonatomic, copy) NSString *pushName;
@property(nonatomic) _Bool receivedFromPush; // @synthesize receivedFromPush;
@property(nonatomic, retain) NSNumber *secondsSinceCallOffer; // @synthesize secondsSinceCallOffer;

@end

