//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WAUserJID;

@interface WACallCommonInfo : NSObject
{
    NSString *_callID;
    WAUserJID *_peerJID;
    _Bool _startedByMe;
    _Bool _videoEnabled;
    _Bool _endedByMe;
    int _duration;
    double _activeTime;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double activeTime; // @synthesize activeTime=_activeTime;
@property(readonly, nonatomic) NSString *callID; // @synthesize callID=_callID;
@property(readonly, nonatomic) int duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) _Bool endedByMe; // @synthesize endedByMe=_endedByMe;
@property(readonly, nonatomic) WAUserJID *peerJID; // @synthesize peerJID=_peerJID;
@property(readonly, nonatomic) _Bool startedByMe; // @synthesize startedByMe=_startedByMe;
@property(readonly, nonatomic) _Bool videoEnabled; // @synthesize videoEnabled=_videoEnabled;

@end

