//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WATableViewController.h>

#import "WACallHistoryParticipantTableViewCellDelegate-Protocol.h"

@class NSMutableArray, WAAggregateCallEventOld, WACallEventParticipant, WACallEventsTableViewCell;

@interface WACallHistoryGroupInfoTableViewController : WATableViewController <WACallHistoryParticipantTableViewCellDelegate>
{
    WAAggregateCallEventOld *_aggregateEvent;
    WACallEventsTableViewCell *_eventsCell;
    NSMutableArray *_completedParticipants;
    NSMutableArray *_failedParticipants;
    WACallEventParticipant *_callerParticipant;
}

- (void).cxx_destruct;
- (void)callDidEnd:(id)arg1;
- (void)callDidStart:(id)arg1;
- (void)callHistoryParticipantCellDidTapVideo:(id)arg1;
- (void)callHistoryParticipantCellDidTapVoice:(id)arg1;
- (void)callJID:(id)arg1 videoCall:(_Bool)arg2;
- (long long)callerSection;
- (long long)completedParticipantsSection;
- (long long)failedParticipantsSection;
- (id)initWithAggregateEvent:(id)arg1;
- (void)nameDirectoryDidInvalidateSomeNames:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)participantForIndexPath:(id)arg1;
- (void)setupParticipants;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)textForCallFailureOutcome:(short)arg1;
- (void)viewDidLoad;

@end

