//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WACallVoiceButtonDelegate-Protocol.h"

@class UIImageView, WACallAcceptRejectButton, WACallButton, WACallVideoButton, WACallVoiceButton, WAGradientView;
@protocol WACallButtonsViewDelegate;

@interface WACallButtonsView : UIView <WACallVoiceButtonDelegate>
{
    WAGradientView *_gradient;
    WACallAcceptRejectButton *_rejectCallButton;
    WACallAcceptRejectButton *_acceptOrEndCallButton;
    WACallButton *_remindButton;
    WACallButton *_incomingMessageButton;
    WACallVoiceButton *_muteButton;
    WACallVoiceButton *_speakerButton;
    WACallVideoButton *_muteVideoButton;
    WACallVideoButton *_switchCameraButton;
    WACallButton *_toggleVideoButton;
    UIView *_hideOptionsView;
    double _callButtonWidth;
    double _controlButtonWidth;
    double _controlButtonHorizontalMargin;
    double _controlButtonVerticalMargin;
    double _bottomMargin;
    _Bool _enableAudioVideoSwitch;
    _Bool _isIncomingCall;
    _Bool _cameraSwitcherIsFrontFacing;
    _Bool _isGroupCall;
    _Bool _oneRow;
    _Bool _videoCall;
    _Bool _hideOptionsEnabled;
    id <WACallButtonsViewDelegate> _delegate;
    UIImageView *_backgroundImageView;
}

- (void).cxx_destruct;
- (void)acceptOrEndCall:(id)arg1;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (void)cancelCallAndAddReminder:(id)arg1;
- (void)cancelCallAndSendMessage:(id)arg1;
- (void)configure;
@property(nonatomic) __weak id <WACallButtonsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disableButtons;
@property(readonly, nonatomic) double edgeMargin;
- (void)enableButtons;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)imageViewForBlurForVoiceCallButton:(id)arg1;
- (id)initWithVideoCall:(_Bool)arg1 backgroundImageView:(id)arg2;
@property(nonatomic, getter=isGroupCall) _Bool isGroupCall; // @synthesize isGroupCall=_isGroupCall;
@property(nonatomic, getter=isHideOptionsEnabled) _Bool hideOptionsEnabled; // @synthesize hideOptionsEnabled=_hideOptionsEnabled;
@property(nonatomic, getter=isMuteButtonSelected) _Bool muteButtonSelected;
@property(readonly, nonatomic, getter=isOneRow) _Bool oneRow; // @synthesize oneRow=_oneRow;
@property(nonatomic, getter=isSpeakerButtonEnabled) _Bool speakerButtonEnabled;
@property(nonatomic, getter=isSpeakerButtonSelected) _Bool speakerButtonSelected;
@property(nonatomic, getter=isSpeakerButtonUserInteractionEnabled) _Bool speakerButtonUserInteractionEnabled;
@property(nonatomic, getter=isSwitchButtonEnabled) _Bool switchButtonEnabled;
@property(nonatomic, getter=isVideoCall) _Bool videoCall; // @synthesize videoCall=_videoCall;
@property(nonatomic, getter=isVideoToggleButtonEnabled) _Bool videoToggleButtonEnabled;
- (void)layoutLegacyControlButtons;
- (void)layoutSubviews;
- (void)muteVideoButtonRoute:(int)arg1 routingAllowed:(_Bool)arg2 callMuted:(_Bool)arg3;
@property(readonly, nonatomic) double oneRowHeight;
@property(readonly, nonatomic) double preferredHeight;
- (void)rejectCall:(id)arg1;
- (void)rotateButtons:(double)arg1;
- (void)selectAcceptOrDeclineButton;
- (void)setAcceptRejectButtonState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)showButtonsForConnectedScreen;
- (void)showButtonsForIncomingCallScreenForPendingCall:(_Bool)arg1;
- (void)showButtonsForVideoCallUpgradeRequest;
- (void)speakerVoiceButtonRoutingAllowed:(_Bool)arg1 route:(int)arg2;
- (void)toggleMute:(id)arg1;
- (void)toggleSpeaker:(id)arg1;
- (void)toggleSwitchCamera:(id)arg1;
- (void)toggleVideoButtonPressed:(id)arg1;
- (void)updateButtonsSize;
- (void)updateLayoutForState:(int)arg1;

@end

