//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WACallHistoryParticipantTableViewCell;

@protocol WACallHistoryParticipantTableViewCellDelegate
- (void)callHistoryParticipantCellDidTapVideo:(WACallHistoryParticipantTableViewCell *)arg1;
- (void)callHistoryParticipantCellDidTapVoice:(WACallHistoryParticipantTableViewCell *)arg1;
@end

