//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, WAGroupJID, WAUserJID;

@interface WACallNotificationInfo : NSObject
{
    NSArray *_participantJIDs;
    _Bool _videoEnabled;
    int _scheduledCount;
    unsigned long long _notificationType;
    NSString *_callID;
    WAUserJID *_callerJID;
    WAGroupJID *_groupJID;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *callID; // @synthesize callID=_callID;
@property(readonly, nonatomic) WAUserJID *callerJID; // @synthesize callerJID=_callerJID;
- (id)description;
@property(readonly, nonatomic) WAGroupJID *groupJID; // @synthesize groupJID=_groupJID;
- (id)initWithCallID:(id)arg1 callerJID:(id)arg2 groupJID:(id)arg3 participantJIDs:(id)arg4 videoEnabled:(_Bool)arg5 notificationType:(unsigned long long)arg6;
@property(readonly, nonatomic) _Bool isGroupCall;
@property(readonly, nonatomic) _Bool isJoinable;
@property(readonly, nonatomic) unsigned long long notificationType; // @synthesize notificationType=_notificationType;
@property(readonly, copy, nonatomic) NSArray *participantJIDsOrderedByCallerJID;
@property(nonatomic) int scheduledCount; // @synthesize scheduledCount=_scheduledCount;
@property(readonly, nonatomic) _Bool shouldReschedule;
@property(readonly, nonatomic) _Bool videoEnabled; // @synthesize videoEnabled=_videoEnabled;

@end

