//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAChatBarMenuPlugin-Protocol.h"

@class NSString, UIViewController;
@protocol WAGimmickPickerViewDelegate;

@interface WAChatBarGifPlugin : NSObject <WAChatBarMenuPlugin>
{
    UIViewController *_viewController;
    id <WAGimmickPickerViewDelegate> _delegate;
}

+ (_Bool)shouldShowInMenuForChatSession:(id)arg1;
- (void).cxx_destruct;
- (void)addMenuItemToActionSheet:(id)arg1 withChatSession:(id)arg2;
@property(readonly, nonatomic) __weak id <WAGimmickPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithHostViewController:(id)arg1 pickerDelegate:(id)arg2;
- (void)showGifSearchFromChatSession:(id)arg1;
@property(readonly, nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

