//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol WAChatBarMenuPlugin;

@protocol WAChatBarMenuPluginDelegate
- (void)chatBarMenuPluginDisableShareTooltips:(id <WAChatBarMenuPlugin>)arg1;
- (void)chatBarMenuPluginDismissKeyboardIfNeeded:(id <WAChatBarMenuPlugin>)arg1;
- (void)chatBarMenuPluginStartPaymentFlow:(id <WAChatBarMenuPlugin>)arg1;
@end

