//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, WADeviceJID, WAPhoneNumber, WAUserJID;

@interface WAChangeNumberSource : NSObject
{
    WADeviceJID *_deviceJID;
    WAPhoneNumber *_phoneNumber;
    NSArray *_jidsToNotify;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WADeviceJID *deviceJID; // @synthesize deviceJID=_deviceJID;
- (id)initWithDeviceJID:(id)arg1 phoneNumber:(id)arg2 jidsToNotify:(id)arg3;
@property(readonly, nonatomic) NSArray *jidsToNotify; // @synthesize jidsToNotify=_jidsToNotify;
@property(readonly, nonatomic) WAPhoneNumber *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, nonatomic) WAUserJID *userJID;

@end

