//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableArray;
@protocol WAServerDate;

@interface WAChatMessagesSection : NSObject
{
    NSMutableArray *_rows;
    long long _day;
    long long _month;
    long long _year;
    NSDate<WAServerDate> *_earliestDate;
}

+ (id)albumifiableMessageObjectIDsInMessages:(id)arg1 firstUnreadMessage:(id)arg2;
- (void).cxx_destruct;
- (id)albumifiableMessageMap;
@property(nonatomic) long long day; // @synthesize day=_day;
@property(retain, nonatomic) NSDate<WAServerDate> *earliestDate; // @synthesize earliestDate=_earliestDate;
- (id)init;
@property(nonatomic) long long month; // @synthesize month=_month;
- (_Bool)needsRebuild;
- (_Bool)rebuildIfNeeded;
@property(readonly, nonatomic) long long rowCount;
@property(retain, nonatomic) NSMutableArray *rows; // @synthesize rows=_rows;
@property(nonatomic) long long year; // @synthesize year=_year;

@end

