//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;

@protocol WAChatSessionPersistentNotificationContentViewLayoutDelegate <NSObject>
- (void)persistentNotificationContentViewNeedsDismissedKeyboard:(UIView *)arg1;
- (void)persistentNotificationContentViewNeedsUpdatedHeight:(UIView *)arg1;
@end

