//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton;

@interface WAChatListHeaderCell : UITableViewCell
{
    UIButton *_broadcastButton;
    UIButton *_groupButton;
}

- (void).cxx_destruct;
- (id)init;
- (void)layoutMarginsDidChange;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

