//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WAChatButtonAction : NSObject
{
    NSString *_title;
    CDUnknownBlockType _handler;
    unsigned long long _style;
}

+ (id)actionWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)actionWithTitle:(id)arg1 style:(unsigned long long)arg2 handler:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (id)initWithTitle:(id)arg1 style:(unsigned long long)arg2 handler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_style;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;

@end

