//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WASpotlightIndexer.h"

@interface WAChatSessionSpotlightIndexer : WASpotlightIndexer
{
}

- (id)initWithStorage:(id)arg1;
- (id)internalChatPresenterForItemIdentifier:(id)arg1;
- (id)searchableItemForIndexableItem:(id)arg1 usingItemIdentifier:(id)arg2;

@end

