//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WAChatCellData, WAMessage;

@interface WAChatCellDataMessagePair : NSObject
{
    WAMessage *_message;
    WAChatCellData *_cellData;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WAChatCellData *cellData; // @synthesize cellData=_cellData;
- (id)initWithMessage:(id)arg1 inCellData:(id)arg2;
@property(readonly, nonatomic) WAMessage *message; // @synthesize message=_message;

@end

