//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAHistoricalDatePicker.h"

@class UIView;

@interface WAChatSearchPickerView : WAHistoricalDatePicker
{
    UIView *_topBorderView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;

@end

