//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAChatBarMenuPluginDelegate-Protocol.h"

@class NSDate, WAChatBarShareLocationPlugin, WAPlace;
@protocol WAServerDate;

@protocol WAChatBarShareLocationPluginDelegate <WAChatBarMenuPluginDelegate>
- (void)chatBarShareLocationPlugin:(WAChatBarShareLocationPlugin *)arg1 sendMessageContainingPlace:(WAPlace *)arg2 liveLocationEndDate:(NSDate<WAServerDate> *)arg3 completion:(void (^)(WAMessage *))arg4;
@end

