//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAChatBarMenuPluginDelegate-Protocol.h"

@class NSArray, WAChatBarCameraPlugin, WAMediaPickerStats;

@protocol WAChatBarCameraPluginDelegate <WAChatBarMenuPluginDelegate>
- (void)chatBarCameraPlugin:(WAChatBarCameraPlugin *)arg1 sendMediaItems:(NSArray *)arg2 pickerStatistics:(WAMediaPickerStats *)arg3;
@end

