//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIColor, WAChatListSearchBarTokenView;

@protocol WAChatListSearchBarTokenViewDelegate
- (void)chatListSearchBarTokenViewSelected:(WAChatListSearchBarTokenView *)arg1;
- (UIColor *)chatListSearchBarTokenViewTintColorForSelection:(WAChatListSearchBarTokenView *)arg1;
@end

