//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAPhoneConfirmationController.h"

@interface WAClearConversationsPhoneConfirmationViewController : WAPhoneConfirmationController
{
}

- (id)buttonTitle;
- (_Bool)networkAccessRequired;
- (id)title;
- (id)warningBulletPoints;
- (id)warningText;

@end

