//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WACloudInteractionOperation.h"

@class NSString, WAActionManager, WACloudStatus;

@interface WACloudInteractionBackupOperation_Documents : WACloudInteractionOperation
{
    _Bool _didStopListening;
    WACloudStatus *_capturedCloudStatus;
    id _cloudStatusListener;
    _Bool _failed;
    WAActionManager *_actionManager;
    NSString *_remoteBackupPath;
}

- (void).cxx_destruct;
@property(readonly) WAActionManager *actionManager; // @synthesize actionManager=_actionManager;
- (void)cancel;
- (id)cloudStatusToObserve;
- (void)cloudStatusUpdated:(id)arg1;
- (unsigned long long)completedSteps;
@property _Bool failed; // @synthesize failed=_failed;
- (void)finish;
- (id)initWithActionManager:(id)arg1;
- (void)listenForCloudStatus;
- (id)pathForRemoteFile:(id)arg1;
- (void)performTaskWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) NSString *remoteBackupPath; // @synthesize remoteBackupPath=_remoteBackupPath;
- (_Bool)succeeded;
- (unsigned long long)totalSteps;

@end

