//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface WAClosureButton : UIButton
{
    CDUnknownBlockType _closure;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType closure; // @synthesize closure=_closure;
- (void)handleClosure;

@end

