//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAClusterUtilities : NSObject
{
}

+ (id)computeIDToClusterMapForClusters:(id)arg1;
+ (id)computeJIDToIDMapForClusters:(id)arg1;
+ (id)keyForCluster:(id)arg1;

@end

