//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSSet;

@interface WAClusterTransitions : NSObject
{
    NSSet *_JIDsOfNewSingletons;
    NSSet *_oldSingletonJIDs;
    NSSet *_oldGroupedJIDs;
    NSSet *_newGroupedJIDs;
    NSSet *_newGroupIDs;
    NSSet *_oldGroupIDs;
    NSDictionary *_newGroupMembershipMap;
    NSDictionary *_oldGroupMembershipMap;
    NSSet *_createSingleton;
    NSSet *_moveSingleton;
    NSSet *_destroySingleton;
    NSSet *_destroyGroup;
    NSSet *_createGroup;
    NSSet *_singletonJoinGroup;
    NSSet *_singletonSplitFromGroup;
    NSSet *_groupSplitFromGroup;
    NSSet *_groupJoinGroup;
    NSDictionary *_groupMap;
    NSDictionary *_reverseGroupMap;
}

+ (id)computeCreateGroupFromNewGroupIDs:(id)arg1 reverseGroupMap:(id)arg2;
+ (id)computeCreateSingletonWithJIDsOfNewSingletons:(id)arg1 oldSingletonJIDs:(id)arg2 oldGroupedJIDs:(id)arg3;
+ (id)computeDestroyedGroupFromGroupMap:(id)arg1 oldGroupedIDs:(id)arg2;
+ (id)computeDestroyedSingletonsFromOldSingletonJIDs:(id)arg1 newGroupedJIDs:(id)arg2 jidsOfNewSingletons:(id)arg3;
+ (id)computeGroupIDsFromClusters:(id)arg1;
+ (id)computeGroupJoinGroupWithOldGroupIDs:(id)arg1 newGroupIDs:(id)arg2 destroyedJIDs:(id)arg3 groupSplitFromGroup:(id)arg4 singletonSplitFromGroup:(id)arg5 groupMap:(id)arg6 newGroupMembershipMap:(id)arg7;
+ (id)computeGroupMapWithNewGroupIDs:(id)arg1 oldGroupIDs:(id)arg2;
+ (id)computeGroupMembershipMapWithGroupIDs:(id)arg1;
+ (id)computeGroupSplitFromGroupWithOldGroupedJIDs:(id)arg1 jidsOfNewSingletons:(id)arg2 groupMap:(id)arg3 oldGroupMembershipMap:(id)arg4 newGroupMembershipMap:(id)arg5;
+ (id)computeGroupedJIDsFromClusters:(id)arg1;
+ (id)computeMovedSingletonsWithOldSingletonJIDs:(id)arg1 jidsOfNewSingletons:(id)arg2;
+ (id)computeReverseGroupMapFromGroupMap:(id)arg1;
+ (id)computeSingletonJoinGroupWithOldSingletonJIDs:(id)arg1 newGroupedJIDs:(id)arg2;
+ (id)computeSingletonSplitFromGroupWithOldGroupedJIDs:(id)arg1 jidsOfNewSingletons:(id)arg2;
+ (id)computeSingletonSplitFromGroupWithOldGroupedJIDs:(id)arg1 jidsOfNewSingletons:(id)arg2 oldGroupMembershipMap:(id)arg3 newGroupMembershipMap:(id)arg4;
+ (id)computeSingletonsFromClusters:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSSet *createGroup; // @synthesize createGroup=_createGroup;
@property(readonly, nonatomic) NSSet *createSingleton; // @synthesize createSingleton=_createSingleton;
@property(readonly, nonatomic) NSSet *destroyGroup; // @synthesize destroyGroup=_destroyGroup;
@property(readonly, nonatomic) NSSet *destroySingleton; // @synthesize destroySingleton=_destroySingleton;
@property(readonly, nonatomic) NSSet *groupJoinGroup; // @synthesize groupJoinGroup=_groupJoinGroup;
@property(readonly, nonatomic) NSDictionary *groupMap; // @synthesize groupMap=_groupMap;
@property(readonly, nonatomic) NSSet *groupSplitFromGroup; // @synthesize groupSplitFromGroup=_groupSplitFromGroup;
- (id)initWithOldClusters:(id)arg1 newClusters:(id)arg2;
@property(readonly, nonatomic) NSSet *moveSingleton; // @synthesize moveSingleton=_moveSingleton;
@property(readonly, nonatomic) NSDictionary *reverseGroupMap; // @synthesize reverseGroupMap=_reverseGroupMap;
@property(readonly, nonatomic) NSSet *singletonJoinGroup; // @synthesize singletonJoinGroup=_singletonJoinGroup;
@property(readonly, nonatomic) NSSet *singletonSplitFromGroup; // @synthesize singletonSplitFromGroup=_singletonSplitFromGroup;

@end

