//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAContextMenuPresenter.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@interface WAContextMenuPresenter (MainAppLibrary) <UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
@end

