//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "WALinkLabelDelegate-Protocol.h"
#import "WAWelcomeViewController-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, WALinkLabel;
@protocol WAWelcomeViewControllerDelegate;

@interface WAConsumerWelcomeViewController : WAViewController <WALinkLabelDelegate, WAWelcomeViewController>
{
    UIImageView *_imageView;
    UILabel *_titleLabel;
    WALinkLabel *_helperTextLabel;
    UIButton *_acceptButton;
    id <WAWelcomeViewControllerDelegate> delegate;
}

- (void).cxx_destruct;
- (void)acceptAction:(id)arg1;
- (id)addSpacerView;
- (void)createViews;
@property(nonatomic) __weak id <WAWelcomeViewControllerDelegate> delegate; // @synthesize delegate;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (void)reloadFonts;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)wa_fontSizeDidChange;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

