//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAContactsStorage.h>

@class NSDate, NSString, WAContactSpotlightIndexer;

@interface WAContactsStorage (Analysis)
+ (id)fullNotificationHashFromString:(id)arg1;
+ (id)notificationHashDataFromString:(id)arg1 length:(unsigned long long)arg2;
- (void)MAIN_APP_performAfterInitWithConnection:(id)arg1;
- (id)addNewContactFromContactProxy:(id)arg1 inContext:(id)arg2;
- (id)addressBookPhoneNumberForUserJID:(id)arg1;
- (id)allContactsDeduped;
- (id)allContactsMatchingPhoneNumbers:(id)arg1 inContext:(id)arg2;
- (void)analyzeContainersInContactStore:(id)arg1;
@property(retain, nonatomic) NSDate *contactsDeletedEventTimestamp;
- (id)contactsWithIdentifier:(id)arg1 inContext:(id)arg2;
- (unsigned long long)countOfContactsForPredicate:(id)arg1 inContext:(id)arg2;
- (void)deleteContactsDeletedEvent;
- (void)deleteDatabase;
@property(readonly, copy, nonatomic) NSString *eTag;
- (void)handleDatabaseContext:(id)arg1 operation:(long long)arg2 error:(id)arg3;
- (id)identifiersFromContactStore:(id)arg1 error:(out id *)arg2;
- (id)inNetworkContactsForJID:(id)arg1 inContext:(id)arg2;
- (id)inNetworkContactsForJIDs:(id)arg1 inContext:(id)arg2;
- (_Bool)internalProcessIncomingStatusNotification:(id)arg1;
- (void)markJIDAsOutOfNetwork:(id)arg1;
- (_Bool)mergeStatusV2Results:(id)arg1 intoContext:(id)arg2;
- (void)notifyUpdatedContactsIfNecessary;
- (void)notifyUpdatedStatusIfNecessary;
- (unsigned long long)numberOfContacts;
- (id)phoneNumbersForFullSync:(_Bool)arg1;
- (void)processContactAddedNotificationWithHash:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)processIncomingStatusNotification:(id)arg1;
- (void)processResultsOfFullSync:(_Bool)arg1 listContacts:(id)arg2 sidelistContacts:(id)arg3 statusEntries:(id)arg4;
- (void)queryAboutTextForJIDs:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)recordContactsDeletedEvent;
- (id)refetchDataForContact:(id)arg1;
- (void)refreshETag;
- (void)registerDailyStatsCallback:(id)arg1;
- (void)registerSpotlightIndexingWithManager:(id)arg1;
- (void)reloadContactsUsingContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reloadDataFromCNContact:(id)arg1 userJID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reloadDataFromContactModifiedInApp:(id)arg1 userJID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (struct WAContactProxyReloadResult)reloadDataFromContactProxyObject:(id)arg1 managedObjectContext:(id)arg2 usingExistingContacts:(id)arg3 uniqueContactKeys:(id)arg4;
- (void)requestStatusMessagesForJIDs:(id)arg1;
- (void)saveContactContainersSnapshot:(id)arg1;
- (_Bool)saveDatabase:(id *)arg1;
- (void)setAboutText:(id)arg1 withTimestamp:(id)arg2 forUserJID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)sidelistJIDsMatchingHash:(id)arg1;
@property(readonly, nonatomic) WAContactSpotlightIndexer *spotlightIndexer;
- (id)statusRecipientJIDs;
- (id)statusTimestampsForUserJIDs:(id)arg1 contactStatus:(short)arg2;
- (void)syncStatusRecipientsWithContacts;
- (id)unsyncedSidelistJIDsFromJIDs:(id)arg1;
- (id)whatsAppAbleContactsWithABID:(id)arg1;
- (id)whatsAppableJIDsFromContactsExcludingBlocked;
- (_Bool)willSaveDatabaseContext:(id)arg1;
@end

