//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSDate, NSString;

@interface WAContactContainerSnapshot : NSObject <NSSecureCoding>
{
    NSString *_identifier;
    NSString *_name;
    long long _type;
    long long _numberOfContacts;
    NSDate *_timestamp;
}

+ (id)stringFromCNContainerType:(long long)arg1;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithContainer:(id)arg1;
@property(readonly, nonatomic, getter=isExchangeContainer) _Bool exchangeContainer;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long numberOfContacts; // @synthesize numberOfContacts=_numberOfContacts;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

