//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WACoreContactBlocklistDelegate.h>

@interface WACoreContactBlocklistDelegate (MainApp)
- (void)insertSystemEvent:(int)arg1 inSessionWithJIDIfExists:(id)arg2;
- (void)insertUnblockSystemEventIfNecessary:(id)arg1;
- (_Bool)permanentlySaveJIDs:(id)arg1 error:(id *)arg2;
@end

