//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSArray, NSSet;

@interface WAContactGridFlowLayout : UICollectionViewFlowLayout
{
    NSArray *_indexPathsForTemporarilyHiddenCells;
    NSSet *_insertedIndexPaths;
    NSSet *_deletedIndexPaths;
    struct UIEdgeInsets _defaultInsets;
    struct UIEdgeInsets _extraInsets;
}

- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets defaultInsets; // @synthesize defaultInsets=_defaultInsets;
@property(copy, nonatomic) NSSet *deletedIndexPaths; // @synthesize deletedIndexPaths=_deletedIndexPaths;
@property(nonatomic) struct UIEdgeInsets extraInsets; // @synthesize extraInsets=_extraInsets;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (void)finalizeCollectionViewUpdates;
@property(copy, nonatomic) NSArray *indexPathsForTemporarilyHiddenCells; // @synthesize indexPathsForTemporarilyHiddenCells=_indexPathsForTemporarilyHiddenCells;
- (id)init;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
@property(copy, nonatomic) NSSet *insertedIndexPaths; // @synthesize insertedIndexPaths=_insertedIndexPaths;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (void)setInsets;

@end

