//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "WAContactCallButtonsViewDelegate-Protocol.h"
#import "WAContactGridCellDelegate-Protocol.h"

@class NSString, WAContactCallButtonsView, WAContactGridCellConfiguration, WAContactGridFlowLayout;
@protocol WAContactGridViewControllerDataSource, WAContactGridViewControllerDelegate;

@interface WAContactGridViewController : UICollectionViewController <WAContactGridCellDelegate, WAContactCallButtonsViewDelegate, UICollectionViewDelegateFlowLayout>
{
    WAContactCallButtonsView *_callButtonsView;
    double _previousViewWidth;
    int _deleteAnimationCount;
    id <WAContactGridViewControllerDelegate> _delegate;
    id <WAContactGridViewControllerDataSource> _dataSource;
    WAContactGridCellConfiguration *_cellConfiguration;
}

- (void).cxx_destruct;
- (void)callButtonTapped:(id)arg1 video:(_Bool)arg2;
@property(retain, nonatomic) WAContactGridCellConfiguration *cellConfiguration; // @synthesize cellConfiguration=_cellConfiguration;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (id)collectionViewIndexPathForContactIndex:(unsigned long long)arg1;
- (id)collectionViewIndexPathsAtIndexes:(id)arg1;
- (void)contactGridCell:(id)arg1 didUpdateLayoutWithProfilePictureBottomDistance:(double)arg2;
@property(readonly, nonatomic) WAContactGridFlowLayout *contactGridFlowLayout;
- (long long)contactIndexForCollectionViewIndexPath:(id)arg1;
@property(nonatomic) __weak id <WAContactGridViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <WAContactGridViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int deleteAnimationCount; // @synthesize deleteAnimationCount=_deleteAnimationCount;
- (void)deleteButtonTappedInContactGridCell:(id)arg1;
- (void)deleteContactsAtIndexes:(id)arg1;
- (struct UIEdgeInsets)extraInsetsWithSideInset:(double)arg1 originalInsets:(struct UIEdgeInsets)arg2 rtl:(_Bool)arg3;
- (long long)indexOfContactsSection;
- (id)initWithScrollDirection:(long long)arg1;
- (id)initWithScrollDirection:(long long)arg1 callingEnabled:(_Bool)arg2;
- (id)initWithScrollDirection:(long long)arg1 cellConfiguration:(id)arg2 callingEnabled:(_Bool)arg3;
- (void)insertContactsAtIndexes:(id)arg1;
- (double)insetForProfilePictureCutoff;
- (long long)numberOfSections;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (double)preferredHeightForNumberOfRows:(long long)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)setupCallView;
- (void)showCallButtons:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

