//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAContactQRViewController;

@protocol WAContactQRViewControllerDelegate <NSObject>
- (void)contactQRViewControllerDidRequestQRScanner:(WAContactQRViewController *)arg1;
@end

