//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAQRHelpView.h"

@class UIImageView, UIView;

@interface WAContactQRHelpView : WAQRHelpView
{
    UIImageView *_qrCode;
    UIView *_qrCodeFrame;
}

- (void).cxx_destruct;
- (void)setupBackgroundQRCodeImage;
- (void)setupTitle;

@end

