//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WAAutoScrollingLabelDelegate-Protocol.h"
#import "WANavigationBarTitleViewFillsAvailableSpace-Protocol.h"
#import "WANavigationBarTitleViewLeftAlign-Protocol.h"

@class NSAttributedString, NSString, UIButton, UIFont, UIImage, UIImageView, UILabel, WAActivityIndicatorView, WAAutoscrollingLabel, WABadgedLabel;
@protocol WAConversationHeaderViewDelegate;

@interface WAConversationHeaderView : UIView <WAAutoScrollingLabelDelegate, WANavigationBarTitleViewFillsAvailableSpace, WANavigationBarTitleViewLeftAlign>
{
    _Bool _groupLayout;
    _Bool _profilePictureHidden;
    _Bool _picturePlaceholderAllowed;
    _Bool _callButtonHidden;
    _Bool _videoCallButtonHidden;
    _Bool _groupCallButtonHidden;
    _Bool _catalogButtonHidden;
    _Bool _shopsButtonHidden;
    _Bool _businessCallButtonHidden;
    _Bool _pictureTappable;
    _Bool _tappable;
    _Bool _editMode;
    _Bool _ephemeralIconHidden;
    _Bool _individualChat;
    _Bool _compactHeight;
    _Bool _fadingCaptionLabel;
    _Bool _animating;
    id <WAConversationHeaderViewDelegate> _delegate;
    UIImage *_profilePicture;
    NSString *_title;
    NSAttributedString *_caption;
    NSString *_captionTextForVoiceOver;
    NSString *_activityText;
    WABadgedLabel *_titleLabel;
    WAAutoscrollingLabel *_captionLabel;
    UILabel *_activityLabel;
    WAActivityIndicatorView *_activityIndicator;
    UIButton *_headerViewButton;
    UIButton *_profilePictureButton;
    UIImageView *_ephemeralIconImageView;
    UIButton *_callButton;
    UIButton *_videoCallButton;
    UIButton *_groupCallButton;
    UIButton *_catalogButton;
    UIButton *_shopsButton;
    UIButton *_businessCallButton;
    CDUnknownBlockType _captionScrollCompletion;
}

+ (id)headerViewWithDelegate:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) WAActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
@property(copy, nonatomic) NSString *activityText; // @synthesize activityText=_activityText;
- (void)autoscrollingLabelDidFinishScrolling:(id)arg1;
@property(nonatomic) unsigned long long badgeType;
@property(retain, nonatomic) UIButton *businessCallButton; // @synthesize businessCallButton=_businessCallButton;
- (void)businessCallButtonTapped:(id)arg1;
@property(retain, nonatomic) UIButton *callButton; // @synthesize callButton=_callButton;
- (void)callButtonTapped:(id)arg1;
@property(copy, nonatomic) NSAttributedString *caption; // @synthesize caption=_caption;
@property(readonly, nonatomic) UIFont *captionFont;
- (id)captionFontForCompactHeight:(_Bool)arg1;
@property(retain, nonatomic) WAAutoscrollingLabel *captionLabel; // @synthesize captionLabel=_captionLabel;
@property(copy, nonatomic) CDUnknownBlockType captionScrollCompletion; // @synthesize captionScrollCompletion=_captionScrollCompletion;
@property(copy, nonatomic) NSString *captionTextForVoiceOver; // @synthesize captionTextForVoiceOver=_captionTextForVoiceOver;
@property(retain, nonatomic) UIButton *catalogButton; // @synthesize catalogButton=_catalogButton;
- (void)catalogButtonTapped:(id)arg1;
@property(nonatomic) _Bool compactHeight; // @synthesize compactHeight=_compactHeight;
- (void)configureAccessibility;
- (void)configureTitleAndCaption;
@property(nonatomic) __weak id <WAConversationHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didMoveToSuperview;
@property(nonatomic) _Bool editMode; // @synthesize editMode=_editMode;
@property(retain, nonatomic) UIImageView *ephemeralIconImageView; // @synthesize ephemeralIconImageView=_ephemeralIconImageView;
@property(nonatomic) _Bool fadingCaptionLabel; // @synthesize fadingCaptionLabel=_fadingCaptionLabel;
@property(retain, nonatomic) UIButton *groupCallButton; // @synthesize groupCallButton=_groupCallButton;
- (void)groupCallButtonTapped:(id)arg1;
@property(retain, nonatomic) UIButton *headerViewButton; // @synthesize headerViewButton=_headerViewButton;
- (void)headerViewButtonAnyTouch:(id)arg1;
- (void)headerViewTapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (_Bool)isAccessibilityElement;
@property(nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic, getter=isBusinessCallButtonEnabled) _Bool businessCallButtonEnabled;
@property(nonatomic, getter=isBusinessCallButtonHidden) _Bool businessCallButtonHidden; // @synthesize businessCallButtonHidden=_businessCallButtonHidden;
@property(nonatomic, getter=isCallButtonEnabled) _Bool callButtonEnabled;
@property(nonatomic, getter=isCallButtonHidden) _Bool callButtonHidden; // @synthesize callButtonHidden=_callButtonHidden;
@property(nonatomic, getter=isCatalogButtonEnabled) _Bool catalogButtonEnabled;
@property(nonatomic, getter=isCatalogButtonHidden) _Bool catalogButtonHidden; // @synthesize catalogButtonHidden=_catalogButtonHidden;
@property(nonatomic, getter=isEphemeralIconHidden) _Bool ephemeralIconHidden; // @synthesize ephemeralIconHidden=_ephemeralIconHidden;
@property(nonatomic, getter=isGroupCallButtonEnabled) _Bool groupCallButtonEnabled;
@property(nonatomic, getter=isGroupCallButtonHidden) _Bool groupCallButtonHidden; // @synthesize groupCallButtonHidden=_groupCallButtonHidden;
@property(nonatomic, getter=isGroupLayout) _Bool groupLayout; // @synthesize groupLayout=_groupLayout;
@property(nonatomic, getter=isIndividualChat) _Bool individualChat; // @synthesize individualChat=_individualChat;
@property(nonatomic, getter=isPicturePlaceholderAllowed) _Bool picturePlaceholderAllowed; // @synthesize picturePlaceholderAllowed=_picturePlaceholderAllowed;
@property(nonatomic, getter=isPictureTappable) _Bool pictureTappable; // @synthesize pictureTappable=_pictureTappable;
@property(nonatomic, getter=isProfilePictureHidden) _Bool profilePictureHidden; // @synthesize profilePictureHidden=_profilePictureHidden;
- (_Bool)isShopsButtonEnabled;
@property(nonatomic, getter=isShopsButtonHidden) _Bool shopsButtonHidden; // @synthesize shopsButtonHidden=_shopsButtonHidden;
@property(nonatomic, getter=isTappable) _Bool tappable; // @synthesize tappable=_tappable;
@property(nonatomic, getter=isVideoCallButtonEnabled) _Bool videoCallButtonEnabled;
@property(nonatomic, getter=isVideoCallButtonHidden) _Bool videoCallButtonHidden; // @synthesize videoCallButtonHidden=_videoCallButtonHidden;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImage *profilePicture; // @synthesize profilePicture=_profilePicture;
@property(retain, nonatomic) UIButton *profilePictureButton; // @synthesize profilePictureButton=_profilePictureButton;
@property(readonly, nonatomic) UIImageView *profilePictureImageView;
- (void)profilePictureTapped:(id)arg1;
@property(readonly, nonatomic) UIView *profilePictureViewForPreviewing;
- (void)setCaption:(id)arg1 animated:(_Bool)arg2 autoscroll:(_Bool)arg3 scrollCompletion:(CDUnknownBlockType)arg4;
- (void)setEphemeralIconBackgroundColor:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setProfilePicture:(id)arg1 animated:(_Bool)arg2;
- (void)setProfilePictureElementsAlpha:(double)arg1;
@property(retain, nonatomic) UIButton *shopsButton; // @synthesize shopsButton=_shopsButton;
- (void)setShopsButtonEnabled:(_Bool)arg1;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) WABadgedLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *videoCallButton; // @synthesize videoCallButton=_videoCallButton;
- (void)shopsButtonTapped:(id)arg1;
- (_Bool)shouldLeftAlign;
- (void)startAnimating;
- (void)stopAnimating;
- (id)titleFontForCompactHeight:(_Bool)arg1;
- (void)videoCallButtonTapped:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

