//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WACustomSwipeActionTableViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString;
@protocol WACustomSwipeActionControllerDelegate, WACustomSwipeActionsProvider;

@interface WACustomSwipeActionController : NSObject <WACustomSwipeActionTableViewControllerDelegate>
{
    NSMutableArray *_tableViewControllers;
    id <WACustomSwipeActionControllerDelegate> _delegate;
    id <WACustomSwipeActionsProvider> _actionsProvider;
}

- (void).cxx_destruct;
- (void)accessibilityVoiceOverStatusChanged;
@property(nonatomic) __weak id <WACustomSwipeActionsProvider> actionsProvider; // @synthesize actionsProvider=_actionsProvider;
- (void)collapseActionsInTableView:(id)arg1;
- (void)configureCell:(id)arg1 forTableView:(id)arg2;
- (id)controller:(id)arg1 leadingSwipeActionsConfigurationForCell:(id)arg2;
- (id)controller:(id)arg1 trailingSwipeActionsConfigurationForCell:(id)arg2;
- (void)controllerDidUpdateActive:(id)arg1;
- (id)controllerForTableView:(id)arg1;
@property(nonatomic) __weak id <WACustomSwipeActionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)hasActiveCustomActionsInTableView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

