//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, UIColor;

@interface WACustomSwipeActionsConfiguration : NSObject
{
    _Bool _performsFirstActionWithFullSwipe;
    _Bool _destructiveFullSwipe;
    NSArray *_actions;
    UIColor *_backgroundColor;
}

+ (id)configurationWithActions:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) _Bool destructiveFullSwipe; // @synthesize destructiveFullSwipe=_destructiveFullSwipe;
- (id)init;
@property(nonatomic) _Bool performsFirstActionWithFullSwipe; // @synthesize performsFirstActionWithFullSwipe=_performsFirstActionWithFullSwipe;

@end

