//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UITableView, WACustomSwipeActionController, WACustomSwipeActionTableViewCell, WACustomSwipeActionsConfiguration;

@protocol WACustomSwipeActionsProvider <NSObject>
- (WACustomSwipeActionsConfiguration *)controller:(WACustomSwipeActionController *)arg1 leadingSwipeActionsConfigurationForCell:(WACustomSwipeActionTableViewCell *)arg2 inTableView:(UITableView *)arg3;
- (WACustomSwipeActionsConfiguration *)controller:(WACustomSwipeActionController *)arg1 trailingSwipeActionsConfigurationForCell:(WACustomSwipeActionTableViewCell *)arg2 inTableView:(UITableView *)arg3;
@end

