//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WATableViewController.h>

@class NSArray, NSString, UIDatePicker, UIView;

@interface WADebugDateInputViewController : WATableViewController
{
    UIView *_viewHeader;
    NSString *_navigationTitle;
    NSString *_noDateButtonTitle;
    NSArray *_possibleValues;
    CDUnknownBlockType _completionHandler;
    UIDatePicker *_datePicker;
}

- (void).cxx_destruct;
- (void)cancelAction:(id)arg1;
@property(readonly, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
- (void)doneAction:(id)arg1;
- (id)initWithNavTitle:(id)arg1 noDateButtonTitle:(id)arg2 initialDate:(id)arg3 possibleValues:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)noDateAction:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;

@end

