//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAPhoneConfirmationControllerDelegate-Protocol.h"

@class WADeleteAccountPhoneConfirmationViewController;

@protocol WADeleteAccountPhoneConfirmationViewControllerDelegate <WAPhoneConfirmationControllerDelegate>
- (void)deleteAccountPhoneConfirmationViewControllerDidTapChangeNumberInsteadButton:(WADeleteAccountPhoneConfirmationViewController *)arg1;
@end

