//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WADeprecation : NSObject
{
}

+ (_Bool)isDeprecatedPhone;
+ (_Bool)presentNagScreenIfNecessaryFromViewController:(id)arg1;
+ (_Bool)shouldShowNagScreen;
+ (void)showDeprecatedAlertViewWithMessage:(id)arg1 fromViewController:(id)arg2;
+ (void)updateNagLastShownTime:(id)arg1;

@end

