//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WADependencyProvider-Protocol.h"

@class NSArray, NSString, NSURL, OS_dispatch_queue, UIAccessibilityCustomAction, UITableViewCell, UIViewController, WAActionSheetPresenter, WAAppStateSyncRegistrationWrapper, WAChatBar, WAChatJID, WAChatListViewController, WAChatMessagesViewController, WAChatSession, WAChatSessionsViewController, WAChatViewController, WAContactViewController, WAGroupInfoViewController, WAMessage, WAProductDescriptor, WASettingsViewController, WASupportDebugFields, WATableSection, WAViewController, XMPPNotificationStanza, XMPPStanzaElement, _TtC14MainAppLibrary16WACatalogSession;
@protocol WACatalogManager, WAPaymentFactoryDependencyProvider, WAPaymentSettingsServiceSectionProvider, WAProfileBaseViewControllerDelegate, WAProfileConfiguration, WAQuickReplyHelper, WASMBExploreBusinessToolsViewControllerDelegate, WASMBLabelsStorageHelper, WAWelcomeViewController;

@protocol WADependencyProviderMain <WADependencyProvider>
- (void)addLabelDataChangeNotificationObserverForChatMessaagesViewController:(WAChatMessagesViewController *)arg1;
- (void)addLabelElementsToChatElement:(XMPPStanzaElement *)arg1 forChatSession:(WAChatSession *)arg2;
- (void)addLabelElementsToUserElement:(XMPPStanzaElement *)arg1 forChatJID:(WAChatJID *)arg2;
- (void)addLabelsChecksumToResumeQuery:(XMPPStanzaElement *)arg1;
- (void)addLabelsRowToContactView:(WAContactViewController *)arg1 section:(WATableSection *)arg2;
- (void)addLabelsRowToGroupInfoView:(WAGroupInfoViewController *)arg1 section:(WATableSection *)arg2;
- (void)appendSMBDebugFields:(WASupportDebugFields *)arg1;
- (void)handleAddQuickReplyWithMessage:(WAMessage *)arg1 viewController:(UIViewController *)arg2;
- (void)handleAddSMBOptionsForChatSession:(WAChatSession *)arg1 chatSessionsViewController:(WAChatSessionsViewController *)arg2 tableViewCell:(UITableViewCell *)arg3 actionSheet:(WAActionSheetPresenter *)arg4;
- (void)handleRemoveQuickReplyAttachmentMediaItemAtURL:(NSURL *)arg1;
- (void)handleResetSMBRegistration;
- (_Bool)handleSMBNotification:(XMPPNotificationStanza *)arg1 onQueue:(OS_dispatch_queue *)arg2 success:(void (^)(XMPPStanzaHandlingResult *))arg3;
- (void)handleSetLabelsForMessage:(WAMessage *)arg1 viewController:(UIViewController *)arg2;
- (UIViewController *)provideAddItemsToCollectionViewControllerWithSession:(_TtC14MainAppLibrary16WACatalogSession *)arg1;
- (id <WACatalogManager>)provideCatalogManager;
- (WAChatBar *)provideChatBarWithFrame:(struct CGRect)arg1 mode:(unsigned long long)arg2;
- (NSArray *)provideChatJIDsForChatsWithLabelsThatMatchSearchQuery:(NSString *)arg1;
- (WAChatViewController *)provideChatViewControllerWithChatSession:(WAChatSession *)arg1;
- (WAChatViewController *)provideChatViewControllerWithChatSession:(WAChatSession *)arg1 options:(int)arg2;
- (UIViewController *)provideExploreBusinessToolsViewControllerWithDelegate:(id <WASMBExploreBusinessToolsViewControllerDelegate>)arg1;
- (NSArray *)provideLabelIDsForMessage:(WAMessage *)arg1;
- (void)provideLabelIDsThatMatchSearchQuery:(NSString *)arg1 completion:(void (^)(NSArray *))arg2;
- (NSArray *)provideLabelVoiceOverStringsForMesage:(WAMessage *)arg1;
- (id <WASMBLabelsStorageHelper>)provideLabelsStorageHelper;
- (UIAccessibilityCustomAction *)provideMessageLabelAccessiblityAction:(id)arg1;
- (void)provideMessagesForLabelID:(long long)arg1 offset:(unsigned long long)arg2 limit:(unsigned long long)arg3 completion:(void (^)(long long, NSArray *, _Bool))arg4;
- (id <WAPaymentFactoryDependencyProvider>)providePaymentFactoryDependencyProvider;
- (id <WAPaymentSettingsServiceSectionProvider>)providePaymentSettingsServiceSectionProvider;
- (id <WAProfileConfiguration>)provideProfileConfiguration;
- (id <WAQuickReplyHelper>)provideQuickReplyHelperWithViewController:(WAChatViewController *)arg1;
- (NSArray *)provideSMBChatListSupplementaryActions:(WAChatListViewController *)arg1;
- (UIViewController *)provideSMBHomeViewController;
- (NSArray *)provideSMBLabelsForChatSession:(WAChatSession *)arg1;
- (NSArray *)provideSMBLabelsForMessage:(WAMessage *)arg1;
- (UIViewController *)provideSMBProductViewControllerWithProduct:(WAProductDescriptor *)arg1 storeName:(NSString *)arg2 session:(_TtC14MainAppLibrary16WACatalogSession *)arg3;
- (WASettingsViewController *)provideSettingsViewController;
- (UIViewController *)provideVerificationProfileViewControllerWithDelegate:(id <WAProfileBaseViewControllerDelegate>)arg1;
- (WAViewController<WAWelcomeViewController> *)provideWelcomeViewController;
- (void)registerAppSyncProviders:(WAAppStateSyncRegistrationWrapper *)arg1;
- (void)showBusinessToolsSection:(int)arg1 entryPoint:(long long)arg2;
- (void)showCurrentUserProfileViewControllerWithHostingViewController:(UIViewController *)arg1 delegate:(id <WAProfileBaseViewControllerDelegate>)arg2;
- (unsigned long long)unexpiredNUXNotificationsCount;
@end

