//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WADecryptedMessagePayloadProcessor.h"

@interface WADecryptedMessagePayloadProcessorHSM : WADecryptedMessagePayloadProcessor
{
}

- (void)processEnvelopeMarkedHSMMessageStanza:(id)arg1 outputs:(id)arg2;
- (void)processHSMWithCertificateSerial:(id)arg1 messageStanza:(id)arg2 preExistingMessage:(id)arg3 protobufMessage:(id)arg4 notificationBehavior:(unsigned long long)arg5 bizRole:(id)arg6 outputs:(id)arg7;
- (id)processPayload:(id)arg1;

@end

