//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAFoundationDependencyProviding-Protocol.h"

@class NSAttributedString, WAContactsSearchFactory, WAMessage;

@protocol WADependencyProvider <WAFoundationDependencyProviding>
- (WAContactsSearchFactory *)provideContactsSearchFactory;
- (NSAttributedString *)provideStatusLabelStringForMessage:(WAMessage *)arg1 isRTL:(_Bool)arg2;
@end

