//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WADecryptedMessagePayloadMessageProcessor.h"

@class NSMutableDictionary, WADecryptedMessagePayloadProcessorOutputs, WAMessage;

@interface WADecryptedMessagePayloadMessageProcessorRevoke : WADecryptedMessagePayloadMessageProcessor
{
    NSMutableDictionary *_revokedMessageSignals;
    WAMessage *_messageToRevoke;
    WAMessage *_messageRevocationSignal;
    _Bool _revokeMessageOutOfOrder;
    _Bool _revokeTooOld;
    _Bool _revokePayment;
    WADecryptedMessagePayloadProcessorOutputs *_outputs;
}

- (void).cxx_destruct;
- (void)complainAboutRevokingDeletedMessage;
- (void)initializeWithMessage:(id)arg1 payload:(id)arg2;
- (void)initializeWithNonrevokedMessage:(id)arg1;
- (void)initializeWithRevokeSignal:(id)arg1 payload:(id)arg2;
- (_Bool)isRevokeTooOld;
- (id)processPayload:(id)arg1 message:(id)arg2;
- (void)quietlyIgnoreDisallowedRevokeMessage:(id)arg1 payload:(id)arg2;
- (void)revokeMessage:(id)arg1;
- (_Bool)shouldQuietlyIgnoreDisallowedRevoke;
- (_Bool)shouldRevokePayment;
- (_Bool)tryingToRevokeDeletedMessage;

@end

