//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSString, UIImage, WAChatManager, WADeviceJID;
@protocol WADeviceDate, WAOwnDeviceManaging, WAServerDate;

@protocol WADeviceListDevice <NSObject>
@property(readonly, nonatomic) NSString *activeDetails;
@property(readonly, nonatomic) NSString *browserID;
@property(readonly, nonatomic) WADeviceJID *deviceJID;
@property(readonly, nonatomic) NSString *displayName;
@property(readonly, nonatomic) UIImage *iconImage;
@property(readonly, nonatomic) _Bool isActiveNow;
@property(readonly, nonatomic) _Bool isMD;
@property(readonly, nonatomic) _Bool isRemoved;
@property(readonly, nonatomic) NSDate<WAServerDate> *lastSeenDate;
@property(readonly, nonatomic) NSString *locationDetails;
@property(readonly, nonatomic) NSDate<WADeviceDate> *pairDate;
@property(readonly, nonatomic) NSDate<WADeviceDate> *removeDate;
- (void)removeFromDeviceManager:(id <WAOwnDeviceManaging>)arg1 chatManager:(WAChatManager *)arg2 withCompletion:(void (^)(_Bool, NSError *))arg3;
@property(readonly, nonatomic) long long syncState;
@end

