//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class WADiskUsageSummaryBarView;

@interface WADiskUsageCalculatingSummaryTableViewCell : UITableViewCell
{
    WADiskUsageSummaryBarView *_barView;
}

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

