//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UILabel;

@interface WADirectionsButtonContentView : UIView
{
    UILabel *_labelETA;
    NSLayoutConstraint *_iconTopMargin;
    NSLayoutConstraint *_iconTextVerticalSpacing;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setETADurationString:(id)arg1;

@end

