//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WASavedContentListViewController.h"

#import "WADocumentTableViewCellDelegate-Protocol.h"

@class NSString;

@interface WADocumentsBrowserViewController : WASavedContentListViewController <WADocumentTableViewCellDelegate>
{
}

+ (id)localizedStringForItemCount:(long long)arg1;
+ (id)tableViewCellNibName;
+ (double)tableViewCellPreferredHeight;
- (void)configureCell:(id)arg1 withItem:(id)arg2 searchTerm:(id)arg3;
- (void)deselectAllRowsForMessage:(id)arg1;
- (id)itemPreviewViewControllerForItem:(id)arg1 location:(struct CGPoint)arg2 inTableViewCell:(id)arg3 tableView:(id)arg4 returningSourceRect:(struct CGRect *)arg5;
- (id)itemsInMessage:(id)arg1;
- (id)messageForItem:(id)arg1;
- (id)newFetchedResultsController;
- (id)newSearchResultsController;
- (id)noItemsViewHeading;
- (id)noItemsViewImage;
- (id)noItemsViewSubheading;
- (void)prepareTableViewCellForFirstUse:(id)arg1;
- (void)presentItemOnSelection:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (void)selectAllRowsForMessage:(id)arg1;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

