//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WADraggableInputContainerViewDelegate-Protocol.h"

@class NSArray, NSLayoutConstraint, NSString, UIResponder, WADraggableInputContainerView;
@protocol WADraggableInputViewDelegate;

@interface WADraggableInputView : UIView <WADraggableInputContainerViewDelegate>
{
    WADraggableInputContainerView *_containerView;
    double _previousHeight;
    _Bool _ignoreKeyboardNotifications;
    _Bool _ignoreKeyboardNotifications_internal;
    double _animationDurationForHeightUpdate;
    _Bool _inputViewResponderIsBecomingFirstResponder;
    _Bool _updateHeightScheduled;
    UIView *_backgroundExtensionView;
    NSLayoutConstraint *_backgroundExtensionViewHeightConstraint;
    NSLayoutConstraint *_containerViewLeadingEdgeConstraint;
    _Bool _usingAlternativeInput;
    id <WADraggableInputViewDelegate> _delegate;
    double _bottomInset;
    unsigned long long _keyboardState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double bottomInset; // @synthesize bottomInset=_bottomInset;
- (_Bool)canViewControllerBecomeFirstResponder:(id)arg1;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) struct CGRect containerViewLayoutBounds;
@property(readonly, nonatomic) UIResponder *currentFirstResponder;
@property(readonly, nonatomic) double currentLayoutWidth;
- (double)currentLayoutWidthForDraggableInputContainerView:(id)arg1;
@property(nonatomic) __weak id <WADraggableInputViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didAppearInViewController:(id)arg1;
- (double)draggableInputContainerView:(id)arg1 preferredHeightForLayoutWidth:(double)arg2;
- (void)hideKeyboard;
- (_Bool)ignoreKeyboardNotifications;
- (void)ignoreKeyboardNotifications:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)inputViewResponderToBecomeFirstResponder;
@property(readonly, nonatomic) NSArray *inputViewResponders;
- (struct CGSize)intrinsicContentSize;
- (void)invalidateLayout;
@property(readonly, nonatomic, getter=isKeyboardVisible) _Bool keyboardVisible;
@property(nonatomic, getter=isUsingAlternativeInput) _Bool usingAlternativeInput; // @synthesize usingAlternativeInput=_usingAlternativeInput;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
@property(readonly, nonatomic) unsigned long long keyboardState; // @synthesize keyboardState=_keyboardState;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (double)preferredHeightForLayoutWidth:(double)arg1;
- (void)resignFirstResponderOnDisappearInViewController:(id)arg1;
- (void)safeAreaInsetsDidChange;
- (void)setBounds:(struct CGRect)arg1;
- (void)setNeedsUpdateHeight;
- (void)setNeedsUpdateHeightWithAnimationDuration:(double)arg1;
- (void)showKeyboardFromViewController:(id)arg1;
- (void)updateBottomInsetFromKeyboardFrame:(struct CGRect)arg1;
- (void)updateContainerViewLeadingEdgeConstraint;
- (void)updateHeight;
- (void)updateInitialWidth;
- (void)willAppearInViewController:(id)arg1;
- (void)willDisappearInViewController:(id)arg1;
- (void)willHideKeyboardWithAnimationDuration:(double)arg1 animationCurve:(long long)arg2 beginFrame:(struct CGRect)arg3 endFrame:(struct CGRect)arg4;
- (void)willMoveToWindow:(id)arg1;
- (void)willShowKeyboardWithAnimationDuration:(double)arg1 animationCurve:(long long)arg2 beginFrame:(struct CGRect)arg3 endFrame:(struct CGRect)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

