//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAEmptyCallListView;

@protocol WAEmptyCallListViewDelegate <NSObject>
- (void)emptyCallListViewDidRequestEnterRoomsFlow:(WAEmptyCallListView *)arg1;
@end

