//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAEphemeralMessagesUIUtil : NSObject
{
}

+ (unsigned long long)ephemeralDurationRepresentationFromDuration:(unsigned int)arg1;
+ (id)localizedEphemeralChatVoiceoverTextWithDuration:(unsigned int)arg1;
+ (id)localizedEphemeralInfoTitleWithDuration:(unsigned int)arg1;
+ (id)localizedEphemeralSettingChangeByExternalContactSystemMessageWithDuration:(unsigned int)arg1 externalContactName:(id)arg2 shouldShowTapCTA:(_Bool)arg3;
+ (id)localizedEphemeralSettingChangeByYouSystemMessageWithDuration:(unsigned int)arg1 shouldShowTapCTA:(_Bool)arg2;
+ (id)localizedEphemeralSettingChangeToOffByExternalContactName:(id)arg1 shouldShowTapCTA:(_Bool)arg2;
+ (id)localizedEphemeralSettingChangeToOffByYouWithTapCTA:(_Bool)arg1;
+ (id)localizedEphemeralSettingDurationUpdateByExternalContactWithTapCTASystemMessageWithDuration:(unsigned int)arg1 externalContactName:(id)arg2;
+ (id)localizedEphemeralSettingTurnedOnByYouWithTapCTASystemMessageWithDuration:(unsigned int)arg1;
+ (id)localizedErrorAlertForTurningOffIndividualChatSettingForBlockedUser;
+ (id)localizedErrorAlertForTurningOnIndividualChatSettingForBlockedUser;
+ (id)localizedNoContactEphemeralSettingChangeSystemMessageWithDuration:(unsigned int)arg1 shouldShowTapCTA:(_Bool)arg2;
+ (id)localizedNoContactEphemeralSettingChangeToOffWithTapCTA:(_Bool)arg1;
+ (id)localizedNoContactEphemeralSettingChangeWithTapCTASystemMessageWithDuration:(unsigned int)arg1;

@end

