//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WADialogViewController.h>

@class UITextView;

@interface WAEphemeralNUXViewController : WADialogViewController
{
    UITextView *_bodyView;
    CDUnknownBlockType _completion;
}

+ (double)contentLayoutWidth;
- (void).cxx_destruct;
- (void)addLearnMoreButton;
- (void)assembleContentViewIfNeeded;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (id)headerViewWithTitle:(id)arg1 bodyText:(id)arg2;
- (id)initWithProactiveNUXCompletion:(CDUnknownBlockType)arg1;
- (id)initWithSettingsNUXCompletion:(CDUnknownBlockType)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;

@end

