//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WADeepLink.h"

@class NSURL;

@interface WAFileDeepLink : WADeepLink
{
    NSURL *_sourceURL;
}

- (void).cxx_destruct;
- (id)createForwardPicker;
- (void)forwardFileWithRootVC:(id)arg1;
- (void)logDeepLinkEvent;
- (void)openURLDeferredWithRootVC:(id)arg1 showAppSwitcher:(_Bool)arg2;
- (_Bool)parseURL:(id)arg1 context:(id)arg2;
- (void)removeFileAtURL:(id)arg1;
- (void)sendExternalAudioFileAtURL:(id)arg1 toContacts:(id)arg2 chatVC:(id)arg3;
- (id)urlForAppScheme:(id)arg1;

@end

