//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAGDPRReportMetadata-Protocol.h"
#import "WAMMSMediaDownloadOperationDelegate-Protocol.h"
#import "WBMMSDownloadOperationDelegate-Protocol.h"

@class NSString, WAMMSMediaDownloadOperation, WAMMSTimer, WAPBMessage_DocumentMessage;

@interface WAGDPRReportDownloadHelper : NSObject <WAMMSMediaDownloadOperationDelegate, WBMMSDownloadOperationDelegate, WAGDPRReportMetadata>
{
    WAMMSMediaDownloadOperation *_downloadTask;
    WAMMSTimer *_downloadTimer;
    WAPBMessage_DocumentMessage *_reportMetadata;
    CDUnknownBlockType _completion;
}

- (void).cxx_destruct;
- (id)ciphertextHash;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (id)directPath;
- (void)downloadOperation:(id)arg1 didFinishWithResult:(id)arg2 error:(id)arg3;
- (void)downloadOperation:(id)arg1 didRequestEndpointInformation:(CDUnknownBlockType)arg2;
- (void)downloadOperation:(id)arg1 didUpdateProgress:(double)arg2;
- (void)downloadTask:(id)arg1 assetForDecryptedFile:(CDUnknownBlockType)arg2;
- (void)downloadTask:(id)arg1 didFinishWithAsset:(id)arg2 assetType:(unsigned long long)arg3 error:(id)arg4 terminal:(_Bool)arg5 bytesTransferred:(unsigned long long)arg6;
- (void)downloadTask:(id)arg1 didUpdateProgress:(double)arg2;
- (void)downloadTask:(id)arg1 populatedDownloadEvent:(id)arg2 shouldSubmit:(_Bool)arg3 isRetry:(_Bool)arg4;
- (void)downloadTaskDidDecryptPartialMedia:(id)arg1 toFilePath:(id)arg2;
- (unsigned long long)fileLength;
- (id)fileName;
- (id)initWithReportMetadata:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)mediaKey;
- (id)mimeType;
- (id)plaintextHash;
@property(readonly, nonatomic) WAPBMessage_DocumentMessage *reportMetadata; // @synthesize reportMetadata=_reportMetadata;
- (void)startDownload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

