//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "WAGimmickPickerViewConfiguring-Protocol.h"

@class NSArray, NSDictionary, NSIndexPath, NSMutableDictionary, NSMutableSet, NSString, UICollectionView, UIColor, WAGIFSearch, WAPersistentKeyValueStoreCursor;
@protocol WAGIFPickerManagerDelegate><UIScrollViewDelegate;

@interface WAGIFPickerManager : NSObject <UICollectionViewDelegateFlowLayout, WAGimmickPickerViewConfiguring, UICollectionViewDelegate, UICollectionViewDataSource>
{
    NSMutableDictionary *_contentCollectionViewMap;
    NSMutableDictionary *_contentBackgroundViewMap;
    UICollectionView *_categoryCollectionView;
    NSArray *_localCategories;
    NSArray *_remoteCategories;
    NSIndexPath *_currentCategory;
    WAGIFSearch *_search;
    NSDictionary *_categoryToGIFsMap;
    NSMutableSet *_playingGIFCells;
    WAPersistentKeyValueStoreCursor *_recentGIFCursor;
    WAPersistentKeyValueStoreCursor *_starredGIFCursor;
    _Bool _loadingMoreStarredGIFs;
    _Bool _loadingMoreGIFs;
    id <WAGIFPickerManagerDelegate><UIScrollViewDelegate> _delegate;
}

+ (id)pagingCollectionViewCellReuseIdentifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIColor *GIFButtonTintColor;
@property(readonly, nonatomic) NSString *accessibilityLabelForLeftButton;
@property(readonly, nonatomic) NSString *accessibilityLabelForRightButton;
- (void)appendMoreStarredGIFsWithCursor:(id)arg1 updateCollectionView:(id)arg2;
- (id)categoryCollectionViewCellForItemAtIndexPath:(id)arg1;
- (void)categoryCollectionViewDidSelectItemAtIndexPath:(id)arg1;
- (long long)categoryCollectionViewNumberOfItemsInSection:(long long)arg1;
- (id)categoryForCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionViewLayoutForCategoryCollectionView;
@property(readonly, nonatomic) NSString *configurationIdentifier;
- (void)configureContentCollectionView:(id)arg1;
- (id)contentBackgroundViewForCategory:(id)arg1;
- (id)contentCollectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)contentCollectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)contentCollectionView:(id)arg1 didLongPressAtIndexPath:(id)arg2;
- (void)contentCollectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)contentCollectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)contentCollectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)contentCollectionViewBackgroundViewForCategory:(id)arg1;
- (void)contentCollectionViewDidEndDisplaying:(id)arg1;
@property(readonly, nonatomic) NSIndexPath *currentCategory;
- (id)currentGIFCollection;
@property(nonatomic) __weak id <WAGIFPickerManagerDelegate><UIScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didUpdateRecentGIFs:(id)arg1;
- (void)didUpdateStarredGIFs:(id)arg1;
- (_Bool)indexPathIsCloseToEndOfGIFContent:(id)arg1;
- (id)initWithCategoryCollectionView:(id)arg1 contentCollectionViewMap:(id)arg2;
- (void)initializeLocalGIFs;
- (void)initializeRecentGIFs;
- (void)initializeRemoteGIFsForIndexPath:(id)arg1;
- (void)initializeStarredGIFs;
- (void)loadNextBatchForCategory:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadNextBatchIfNecessaryForIndexPath:(id)arg1;
- (id)loadingView;
@property(readonly, nonatomic) long long numberOfCategorySections;
- (long long)numberOfItemsInPagingCollectionViewSection:(long long)arg1;
- (long long)numberOfSectionsInCategoryCollectionView;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)numberOfSectionsInContentCollectionView:(id)arg1;
@property(readonly, nonatomic) long long numberOfSectionsInPagingCollectionView;
- (id)placeholderViewForLocalCategoryItem:(unsigned long long)arg1;
- (_Bool)reachedMaximumNumberOfBatches;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setDefaultGIFCategory;
@property(readonly, nonatomic) _Bool shouldShowLeftButton;
@property(readonly, nonatomic) _Bool shouldShowRightButton;
@property(readonly, nonatomic) _Bool shouldShowRightButtonUpdateIndicator;
- (_Bool)shouldTriggerLoadingNextBatchForIndexPath:(id)arg1;
- (void)showStarredCategory;
- (void)startPlaybackInGIFCollectionViewCell:(id)arg1;
@property(readonly, nonatomic) UIColor *stickerButtonTintColor;
- (void)stopPlaybackInGIFCollectionViewCell:(id)arg1;
- (void)updateCurrentCategoryTo:(id)arg1;
- (_Bool)userScrolledToCategory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

