//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WAMediaActivityManager;

@interface WAGIFActivityManager : NSObject
{
    WAMediaActivityManager *_activityManager;
    NSString *_gifAssetPath;
}

+ (id)namespaceForGIFActivityType:(long long)arg1;
- (void).cxx_destruct;
- (_Bool)activityExistsForGIFAsset:(id)arg1 activityType:(long long)arg2;
- (id)allGIFFilePathsSortedByNameReturningPlaintextHashCache:(out id *)arg1;
- (id)assetForActivityWithGIFAsset:(id)arg1 activityType:(long long)arg2;
- (void)createActivityForGIFAsset:(id)arg1 activityType:(long long)arg2;
- (void)deleteActivityForGIFAsset:(id)arg1 activityType:(long long)arg2;
- (void)deleteAllState;
- (id)initWithMediaActivityManager:(id)arg1 gifAssetPath:(id)arg2;
- (void)internalCreateActivityForGIFAsset:(id)arg1 activityType:(long long)arg2;
- (id)notificationNameForActivityType:(long long)arg1;
- (void)postNotificationForCreatedActivityOfType:(long long)arg1;
- (void)removeOldRecentGIFActivities;
- (id)someGIFsForCursor:(id)arg1;

@end

