//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UICollectionView;

@interface WAGimmickPageCell : UICollectionViewCell
{
    UICollectionView *_contentCollectionView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UICollectionView *contentCollectionView; // @synthesize contentCollectionView=_contentCollectionView;

@end

