//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@class UIView;

@interface WAGimmickPageCollectionView : UICollectionView
{
    UIView *_topBorder;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;
- (void)installTopBorder;
- (void)layoutSubviews;

@end

