//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAGIFQuery.h"

@class NSURL;

@interface WAGIPHYQuery : WAGIFQuery
{
    NSURL *_url;
}

- (void).cxx_destruct;
- (id)language;
- (id)url;

@end

