//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAQRViewController.h"

@class NSData, WAGroupJID;

@interface WAGroupQRViewController : WAQRViewController
{
    NSData *_qrCode;
    WAGroupJID *_groupJID;
}

- (void).cxx_destruct;
- (void)commonInit;
- (_Bool)enableStatusSelectionInForwardActivity;
- (void)groupQRDidChange:(id)arg1;
- (id)initWithQRCode:(id)arg1 groupJID:(id)arg2;
- (void)installLayoutConstraints;
- (void)prepareSharingView;
- (void)prepareSharingViewCaption;
- (void)revokeCode:(id)arg1;
- (void)rightBarButtonTapped:(id)arg1;
- (void)setupUIComponents;
- (void)viewDidLoad;

@end

