//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface WAGroupCreationFooterView : UIView
{
    UILabel *_textLabel;
}

- (void).cxx_destruct;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isAccessibilityElement;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;

@end

