//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

#import "WAGroupParticipantPickerViewControllerDelegate-Protocol.h"

@class NSString, WAChatSession, WAGroupJID, WAGroupMember, WAGroupParticipantsController, WATableRow;

@interface WAGroupSettingsTableViewController : WAStaticTableViewController <WAGroupParticipantPickerViewControllerDelegate>
{
    WAChatSession *_chatSession;
    WAGroupParticipantsController *_participantsController;
    WATableRow *_rowGroupAnnouncementOnly;
    WATableRow *_rowGroupEditingPermission;
    WATableRow *_rowGroupFrequentlyForwarded;
    WATableRow *_rowManageAdmins;
    WAGroupMember *_myGroupMember;
}

- (void).cxx_destruct;
- (void)addIcon:(id)arg1 toTableViewCell:(id)arg2;
- (void)addRequestActivityIndicatorInRow:(id)arg1;
@property(readonly, nonatomic) _Bool canChangeSettings;
@property(readonly, nonatomic) WAGroupJID *chatSessionJID;
- (void)chatStorageDidUpdateChatSessions:(id)arg1;
- (void)dealloc;
- (void)dismissIfNecessary;
- (id)groupAdminSettingTitleForAdminOnlyBool:(_Bool)arg1 shortVersion:(_Bool)arg2;
- (id)initWithChatSession:(id)arg1 participantsController:(id)arg2;
@property(readonly, nonatomic, getter=isAnnouncementOnly) _Bool announcementOnly;
@property(readonly, nonatomic, getter=isFrequentlyForwardedRestricted) _Bool frequentlyForwardedRestricted;
@property(readonly, nonatomic, getter=isLocked) _Bool locked;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)participantPicker:(id)arg1 didSelectContacts:(id)arg2;
- (void)participantPickerDidCancel:(id)arg1;
- (void)promptToChangeGroupAnnouncementOnlySetting;
- (void)promptToChangeGroupEditabilitySetting;
- (void)promptToChangeGroupFrequentlyForwarded;
- (void)requestGroupAnnouncementOnlyStateChange:(_Bool)arg1;
- (void)requestGroupFrequentlyForwardedChange:(_Bool)arg1;
- (void)requestGroupLockedStateChange:(_Bool)arg1;
- (void)setUpTableView;
- (void)setUpdatedGroupAdmins:(id)arg1;
- (void)showAdminManagementScreen;
- (void)showAlertMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showErrorMessageForAdminSettingsChangeError:(id)arg1;
- (void)updateCells;
- (void)updateGroupAnnouncementOnlyCell;
- (void)updateGroupEditabilityCell;
- (void)updateGroupFrequentlyForwardedCell;
- (void)viewDidAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

