//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAHideableMapAnnotation-Protocol.h"
#import "WAMapAnnotationWithCount-Protocol.h"

@class NSArray, NSSet, NSString, WAClusterableAnnotation, WAHideableMapAnnotationIdentifier;

@interface WAGroupedAnnotation : NSObject <WAHideableMapAnnotation, WAMapAnnotationWithCount>
{
    _Bool hidden;
    _Bool _dimmed;
    _Bool _highlightDot;
    _Bool _focused;
    _Bool _pendingBounce;
    WAHideableMapAnnotationIdentifier *_opaqueIdentifier;
    long long _level;
    NSArray *_members;
    struct CLLocationCoordinate2D _coordinate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSSet *constituentJIDs;
@property(nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
@property(readonly, nonatomic) long long count;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool dimmed; // @synthesize dimmed=_dimmed;
@property(nonatomic) _Bool focused; // @synthesize focused=_focused;
@property(nonatomic) _Bool hidden; // @synthesize hidden;
@property(nonatomic) _Bool highlightDot; // @synthesize highlightDot=_highlightDot;
- (id)initWithMembers:(id)arg1;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(copy, nonatomic) NSArray *members; // @synthesize members=_members;
@property(readonly, nonatomic) WAHideableMapAnnotationIdentifier *opaqueIdentifier; // @synthesize opaqueIdentifier=_opaqueIdentifier;
@property(nonatomic) _Bool pendingBounce; // @synthesize pendingBounce=_pendingBounce;
@property(readonly, nonatomic) WAClusterableAnnotation *representativeAnnotation;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

