//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WATextInputViewController.h"

@interface WAGroupTextEditController : WATextInputViewController
{
}

- (id)initWithDelegate:(id)arg1 preloadedText:(id)arg2 placeholderText:(id)arg3 helperText:(id)arg4;

@end

