//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSString;

@interface WAGraphQLClientConfiguration : NSObject
{
    MISSING_TYPE *userAgent;
    MISSING_TYPE *overriddenHostName;
    MISSING_TYPE *urlQueryItems;
    MISSING_TYPE *shouldCompressPostData;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithUserAgent:(id)arg1 overriddenHostName:(id)arg2 urlQueryItems:(id)arg3 shouldCompressPostData:(_Bool)arg4;
@property(nonatomic, readonly) NSString *overriddenHostName;
@property(nonatomic, readonly) _Bool shouldCompressPostData; // @synthesize shouldCompressPostData;
@property(nonatomic, readonly) NSArray *urlQueryItems;
@property(nonatomic, readonly) NSString *userAgent;

@end

