//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, WACaptionBar, WAGroupSendInviteGroupInfoView;

@interface WAGroupSendInviteCaptionView : UIView
{
    UIView *_contactsGridView;
    UIView *_separator;
    WAGroupSendInviteGroupInfoView *_groupInfoView;
    WACaptionBar *_captionBar;
    NSLayoutConstraint *_bottomConstraint;
    double _bottomMargin;
}

- (void).cxx_destruct;
- (id)accessibilityElements;
- (double)bottomConstraintConstant;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
- (void)didMoveToSuperview;
- (void)fontSizeDidChange;
- (void)hideKeyboard;
- (id)initWithContactsGridView:(id)arg1 groupName:(id)arg2 groupPicture:(id)arg3 captionBarDelegate:(id)arg4;
- (void)layoutSubviews;
- (void)setupCaptionBarInsets;
- (void)setupConstraints;

@end

