//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, WADeviceJID;

@interface WAHistorySyncDevice : NSObject
{
    MISSING_TYPE *deviceJID;
    MISSING_TYPE *currentState;
}

- (void).cxx_destruct;
@property(nonatomic, readonly) WADeviceJID *deviceJID; // @synthesize deviceJID;
- (id)init;
@property(nonatomic, readonly) _Bool isSyncing;

@end

