//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface WAHSMMetadata : NSObject <NSSecureCoding, NSCopying>
{
    NSString *_ns;
    NSString *_elementName;
    NSString *_language;
    NSString *_locale;
    NSString *_templateID;
}

+ (id)retrieveMetadataForKey:(id)arg1;
+ (void)storeMetadata:(id)arg1 forKey:(id)arg2;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSString *elementName; // @synthesize elementName=_elementName;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNamespace:(id)arg1 elementName:(id)arg2 language:(id)arg3 locale:(id)arg4;
- (id)initWithNamespace:(id)arg1 elementName:(id)arg2 language:(id)arg3 locale:(id)arg4 templateID:(id)arg5;
@property(readonly, nonatomic) NSString *language; // @synthesize language=_language;
@property(readonly, nonatomic) NSString *languageLocale;
@property(readonly, nonatomic) NSString *locale; // @synthesize locale=_locale;
@property(readonly, nonatomic) NSString *ns; // @synthesize ns=_ns;
@property(readonly, nonatomic) NSString *templateID; // @synthesize templateID=_templateID;

@end

