//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIView;

@protocol WAIconTextCellSeparatorSupport
@property(retain, nonatomic) UIView *bottomSeparator;
@property(retain, nonatomic) UIView *topSeparator;
@end

