//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSMutableDictionary, UIViewController, WAImageToImageTransitionView;

@protocol WAImageToImageTransitioning <NSObject>
- (void)finishTransitionWithContext:(NSMutableDictionary *)arg1;
- (void)prepareForTransitionWithContext:(NSMutableDictionary *)arg1;
- (_Bool)shouldUseImageToImageTransitionForOperation:(long long)arg1 fromViewController:(UIViewController *)arg2 toViewController:(UIViewController *)arg3 context:(NSMutableDictionary *)arg4;
- (WAImageToImageTransitionView *)viewForTransitionAnimationWithContext:(NSMutableDictionary *)arg1;
@end

