//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WARankingEvent.h"

@interface WAIndividualRankingEvents_incomingGroupMention : WARankingEvent
{
}

- (long long)eventID;
- (long long)family;
- (Class)metricDecayClass;
- (_Bool)metricExistsInMetricSet:(id)arg1;
- (id)name;
- (id)rankingMetricInMetricSet:(id)arg1;

@end

