//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

@class UISwitch, WATableRow;

@interface WAInAppNotificationsViewController : WAStaticTableViewController
{
    UISwitch *_switchInAppVibrate;
    UISwitch *_switchInAppSounds;
    WATableRow *_rowInAppAlerts;
}

+ (id)controller;
- (void).cxx_destruct;
- (void)inAppSoundsAction:(id)arg1;
- (void)inAppVibrateAction:(id)arg1;
- (id)init;
- (void)reloadData;
- (void)setUpTableView;
- (void)viewDidLoad;

@end

