//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAUpgradeCallback-Protocol.h"

@class NSCache, NSString, WABiometricPrivacy, WAChatStorage, WAContactsStorage, WAProfilePictureManager;
@protocol OS_dispatch_queue;

@interface WAIntentDonationManager : NSObject <WAUpgradeCallback>
{
    NSObject<OS_dispatch_queue> *_donation_queue;
    WABiometricPrivacy *_biometricPrivacy;
    WAChatStorage *_chatStorage;
    WAContactsStorage *_contactStorage;
    WAProfilePictureManager *_profilePictureManager;
    NSCache *_profilePictureDataCache;
}

+ (void)wa_didUpgradeFrom:(id)arg1 to:(id)arg2;
- (void).cxx_destruct;
- (void)biometricPrivacyEnabledDidChange:(id)arg1;
- (void)deleteAllDonatedInteractions;
- (void)didBlockUserJID:(id)arg1;
- (void)didDeleteChatSession:(id)arg1;
- (void)donateSendMessageIntentForChatJID:(id)arg1;
- (void)donateStartVideoCallIntentForUserJIDs:(id)arg1;
- (void)donateStartVoiceCallIntentForUserJIDs:(id)arg1;
- (id)initWithBiometricPrivacy:(id)arg1 chatStorage:(id)arg2 contactStorage:(id)arg3 profilePictureManager:(id)arg4;
- (void)userDidLeaveGroup:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

