//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WACalloutViewPresenter.h>

@class WAInteractiveAnnotationView, WAPBInteractiveAnnotation;

@interface WAInteractiveAnnotationPresenter : WACalloutViewPresenter
{
    struct CGPoint _normalizedTargetPoint;
    WAPBInteractiveAnnotation *_annotation;
    WAInteractiveAnnotationView *_annotationView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WAPBInteractiveAnnotation *annotation; // @synthesize annotation=_annotation;
@property(readonly, nonatomic) WAInteractiveAnnotationView *annotationView; // @synthesize annotationView=_annotationView;
- (void)configureCalloutView:(id)arg1;
- (void)dismissFromMapView:(id)arg1;
- (id)initWithAnnotation:(id)arg1 atPoint:(struct CGPoint)arg2 inAnnotationView:(id)arg3;
- (id)newCalloutView;
- (void)performDefaultActionForCalloutView:(id)arg1;
- (struct CGPoint)targetPointInView:(id)arg1;

@end

