//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface WAItemViewEvent : NSObject <NSCopying>
{
    _Bool _replied;
    int _unread;
    int _messageType;
    int _listMessageType;
    int _viewCount;
    double _loadTime;
    double _viewTime;
    double _presentationTime;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) int listMessageType; // @synthesize listMessageType=_listMessageType;
@property(nonatomic) double loadTime; // @synthesize loadTime=_loadTime;
@property(nonatomic) int messageType; // @synthesize messageType=_messageType;
@property(nonatomic) double presentationTime; // @synthesize presentationTime=_presentationTime;
@property(nonatomic) _Bool replied; // @synthesize replied=_replied;
@property(nonatomic) int unread; // @synthesize unread=_unread;
@property(nonatomic) int viewCount; // @synthesize viewCount=_viewCount;
@property(nonatomic) double viewTime; // @synthesize viewTime=_viewTime;

@end

