//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAJID.h>

@class NSString;

@interface WAJID (SearchEngine)
@property(readonly, copy) NSString *searchEngineStringRepresentation;
- (id)searchEngineStringRepresentationForSearchingContacts;
- (id)searchEngineStringRepresentationWithContactType:(long long)arg1;
@end

