//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WALayoutBoundsManager;

@protocol WALayoutBoundsManagerDelegate <NSObject>
- (void)layoutBoundsManagerChangedBounds:(WALayoutBoundsManager *)arg1;
@end

