//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL, WALinkLabel;

@protocol WALinkLabelDelegate <NSObject>

@optional
- (void)handleOpenURL:(NSURL *)arg1 fromLinkLabel:(WALinkLabel *)arg2;
@end

