//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MapKit/MKMapView.h>

#import "MKMapViewDelegate-Protocol.h"

@class MKCompassButton, NSArray, NSMutableArray, NSObject, NSString, WACachedCopyMutableArray, WAFriendLiveLocationAnnotation, WAMutableDictionary, WAStickyClusterCollection;
@protocol MKMapViewDelegate, WALiveLocationMapViewDelegate;

@interface WALiveLocationMapView : MKMapView <MKMapViewDelegate>
{
    _Bool _needsUpdate;
    WAStickyClusterCollection *_clusterCollection;
    double _previousZoomScale;
    NSArray *_clusters;
    NSMutableArray *_animatingAnnotations;
    NSMutableArray *_groupsToBounce;
    NSMutableArray *_movingAnnotations;
    WAMutableDictionary *_hiddenAnnotations;
    WACachedCopyMutableArray *_unfilteredAnnotations;
    CDStruct_951efa70 _previousSpan;
    MKMapView *_shadowMap;
    NSObject *_setRegionRequest;
    struct CGPoint _groupAnnotationViewHotspotOffset;
    MKCompassButton *_compass;
    _Bool _animating;
    _Bool _updateWhenAnimationCompletes;
    _Bool _hideUserLocation;
    _Bool _disableUpdates;
    _Bool _animationsCanceled;
    id <WALiveLocationMapViewDelegate> _liveMapViewDelegate;
    WAFriendLiveLocationAnnotation *_ungroupableAnnotation;
    id <MKMapViewDelegate> _realDelegate;
    CDUnknownBlockType _postUpdateBlock;
    long long _retriesLeft;
    struct CLLocationCoordinate2D _autoscaleAnchor;
    struct CGPoint _annotationCenterOffset;
    struct UIEdgeInsets _edgePadding;
}

- (void).cxx_destruct;
- (void)addAnnotation:(id)arg1;
- (void)addAnnotations:(id)arg1;
- (void)addSingleton:(id)arg1 cluster:(id)arg2;
- (void)addUnfilteredAnnotation:(id)arg1;
- (void)animateUpdatesWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(readonly, nonatomic) _Bool animationsCanceled; // @synthesize animationsCanceled=_animationsCanceled;
@property(nonatomic) struct CGPoint annotationCenterOffset; // @synthesize annotationCenterOffset=_annotationCenterOffset;
- (id)annotationForGroupMostSimilarTo:(id)arg1;
- (id)annotationMapForClusters:(id)arg1;
- (void)assertDoNotHaveAnnotationLike:(id)arg1;
@property(nonatomic) struct CLLocationCoordinate2D autoscaleAnchor; // @synthesize autoscaleAnchor=_autoscaleAnchor;
- (void)cancelAnimations;
- (id)clusterableAnnotationForJID:(id)arg1;
- (void)createGroupsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 jidToOldIDMap:(id)arg3 idToOldClusterMap:(id)arg4 idToNewClusterMap:(id)arg5;
- (void)createNewSingletonsWithTransitions:(id)arg1 newAnnotationMap:(id)arg2 existingAnnotationMap:(id)arg3 idToNewClusterMap:(id)arg4;
- (void)destroyExistingSingletonsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2;
- (void)destroyGroupsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2;
@property(nonatomic) _Bool disableUpdates; // @synthesize disableUpdates=_disableUpdates;
@property(nonatomic) struct UIEdgeInsets edgePadding; // @synthesize edgePadding=_edgePadding;
- (struct UIEdgeInsets)effectiveInsets;
- (id)existingAnnotationMap;
- (void)forceUpdateWithCompletion:(CDUnknownBlockType)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)groupIDsForClusters:(id)arg1;
- (void)hideGroupedAnnotation:(id)arg1;
@property(nonatomic) _Bool hideUserLocation; // @synthesize hideUserLocation=_hideUserLocation;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)jidIsGrouped:(id)arg1;
- (void)joinGroupToGroupWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 jidToNewIDMap:(id)arg3 idToNewClusterMap:(id)arg4;
- (void)joinSingletonToGroupWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 jidToNewIDMap:(id)arg3 idToNewClusterMap:(id)arg4;
@property(nonatomic) __weak id <WALiveLocationMapViewDelegate> liveMapViewDelegate; // @synthesize liveMapViewDelegate=_liveMapViewDelegate;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)moveAndUpdateSurvivingGroupsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 jidToOldIDMap:(id)arg3 jidToNewIDMap:(id)arg4 idToNewClusterMap:(id)arg5;
- (void)moveAnnotations;
- (void)moveExistingSingletonsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 idToNewClusterMap:(id)arg3;
- (void)moveSingletonAnnotation:(id)arg1 toCoordinate:(struct CLLocationCoordinate2D)arg2 existingAnnotationMap:(id)arg3 idToNewClusterMap:(id)arg4;
@property(copy, nonatomic) CDUnknownBlockType postUpdateBlock; // @synthesize postUpdateBlock=_postUpdateBlock;
@property(nonatomic) __weak id <MKMapViewDelegate> realDelegate; // @synthesize realDelegate=_realDelegate;
- (void)refreshUnfilteredAnnotation:(id)arg1;
- (_Bool)regionIsCloseTo:(CDStruct_d53ed6ef)arg1;
- (void)removeAnnotation:(id)arg1;
- (void)removeAnnotations:(id)arg1;
- (void)removeOrHideAnnotations:(id)arg1;
- (void)removeUnfilteredAnnotation:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
@property(nonatomic) long long retriesLeft; // @synthesize retriesLeft=_retriesLeft;
- (void)sanityCheckAddAnnotation:(id)arg1;
- (void)selectUnfilteredAnnotation:(id)arg1;
- (void)setHighlightedAnnotation:(id)arg1;
- (void)setInsetRegion:(CDStruct_d53ed6ef)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setInsetRegion:(CDStruct_1f1f9651)arg1 minimumSize:(double)arg2 mayZoomOut:(_Bool)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)setLayoutMargins:(struct UIEdgeInsets)arg1;
- (void)setNeedsUpdate:(_Bool)arg1;
@property(retain, nonatomic) WAFriendLiveLocationAnnotation *ungroupableAnnotation; // @synthesize ungroupableAnnotation=_ungroupableAnnotation;
@property(nonatomic) _Bool updateWhenAnimationCompletes; // @synthesize updateWhenAnimationCompletes=_updateWhenAnimationCompletes;
- (_Bool)shouldRetryRequest:(id)arg1 withDesiredRegion:(CDStruct_d53ed6ef)arg2;
- (void)showAnnotationCleverly:(id)arg1;
- (void)showAnnotations:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showAnnotations:(id)arg1 minimumSize:(double)arg2 mayZoomOut:(_Bool)arg3 excludeHidden:(_Bool)arg4 animated:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;
- (void)showUnfilteredAnnotations:(id)arg1 animated:(_Bool)arg2;
- (void)splitGroupsFromGroupsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 jidToOldIDMap:(id)arg3 jidToNewIDMap:(id)arg4 idToOldClusterMap:(id)arg5 idToNewClusterMap:(id)arg6;
- (void)splitSingletonsFromGroupsWithTransitions:(id)arg1 existingAnnotationMap:(id)arg2 idToNewClusterMap:(id)arg3;
- (_Bool)tryToUnhideAnnotation:(id)arg1;
- (id)unfilteredAnnotationForUserJID:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *unfilteredAnnotations;
- (void)updateAnnotationsForRegionChangeIfNeeded;
- (void)updateCoordinateOfCluster:(id)arg1;
- (void)updateIfNeeded;
- (void)updateIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateShadowMap;
- (void)wa_commonInit;
- (void)willMoveUnfilteredAnnotation:(id)arg1;
@property(readonly, nonatomic) double zoomScale;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

