//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol WALiveLocationMenuTableViewControllerDelegate <NSObject>
- (void)liveLocationMenuDidEnableTraffic:(_Bool)arg1;
- (void)liveLocationMenuMapTypeDidChange:(unsigned long long)arg1;
- (void)liveLocationMenuWillDismiss;
@end

