//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WABaseNotification.h>

@class CLLocation, WAUserJID;

@interface WALiveLocationUpdateNotification : WABaseNotification
{
    WAUserJID *_userJID;
    CLLocation *_location;
    double _elapsedTimeInterval;
}

- (void).cxx_destruct;
@property(nonatomic) double elapsedTimeInterval; // @synthesize elapsedTimeInterval=_elapsedTimeInterval;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) WAUserJID *userJID; // @synthesize userJID=_userJID;

@end

