//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, WamEventLocationPicker;

@protocol WALocationSearchDelegate <NSObject>
- (void)locationSearchCommitFieldStats;
- (void)locationSearchDidCompleteWithAdditions:(NSArray *)arg1 removals:(NSArray *)arg2 previousCount:(unsigned long long)arg3 moreAvailable:(_Bool)arg4;
- (void)locationSearchDidSelectSearchHistoryEntry:(NSString *)arg1;
- (WamEventLocationPicker *)locationSearchFieldStats;
- (CDStruct_d53ed6ef)locationSearchRegion;
- (void)locationSearchSetAttribution:(unsigned long long)arg1;
@end

