//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAAutoMigratingStorage.h>

@class WAMutableDictionary;

@interface WALocationStorage : WAAutoMigratingStorage
{
    WAMutableDictionary *_senderCache;
}

- (void).cxx_destruct;
- (void)addFinalLocationRecipientsWithUserJIDs:(id)arg1 inChatJID:(id)arg2 messageID:(id)arg3 expirationDate:(id)arg4;
- (void)addLocationRecipientsWithUserJIDs:(id)arg1 inChatJID:(id)arg2 messageID:(id)arg3 finalLocationExpirationDate:(id)arg4;
- (id)allLocationRecipientUserJIDs;
- (void)asyncAllMessageUniqueKeysForUserJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)asyncCheckFinalLiveLocationRecipientEligibilityForMessage:(id)arg1 userAndChat:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)asyncDisableSharingInChatJID:(id)arg1 forUserJID:(id)arg2 sequenceNumber:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)asyncEarliestFinalLiveLocationExpirationDate:(CDUnknownBlockType)arg1;
- (void)asyncLocationSendersInChatJID:(id)arg1 allowCachedResults:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)asyncRemoveLocationSenderUserJIDs:(id)arg1 inChatJID:(id)arg2;
- (long long)contextErrorHandlingOptions;
- (void)deleteDatabase;
- (id)endDateForUserInChat:(id)arg1;
- (void)eraseExpiredCachedLocations;
- (id)fetchRequestForFinalLocationRecipientsWhere:(id)arg1;
- (id)fetchRequestForLocationRecipientsWhere:(id)arg1;
- (id)fetchRequestForLocationRecipientsWithUserJIDs:(id)arg1 inChatJID:(id)arg2;
- (id)fetchRequestForLocationSendersWhere:(id)arg1;
- (id)fetchRequestForLocationSendersWithUserJIDs:(id)arg1 inChatJID:(id)arg2;
- (id)fetchRequestWithClass:(Class)arg1 predicate:(id)arg2;
- (id)init;
- (id)initWithModel:(id)arg1 storeURL:(id)arg2 logIdentifier:(id)arg3 maximumBackgroundContextCount:(unsigned long long)arg4 skipBackup:(_Bool)arg5;
- (_Bool)internalRemoveDataForFetchRequest:(id)arg1;
- (void)internalRemoveStopSharingLocationRequestInChatJID:(id)arg1;
- (id)locationRecipientChatToUserJIDMapForUsers:(id)arg1;
- (id)locationRecipientUserToChatJIDMap;
- (id)locationRecipientsWithUserJIDs:(id)arg1 inChatJID:(id)arg2;
- (id)locationSendersInChatJID:(id)arg1 allowCachedResults:(_Bool)arg2;
- (id)lookUpOrRemoveCacheEntryWithChatJID:(id)arg1;
- (id)managedObjectContext;
- (id)mutableLocationSendersWithUserJID:(id)arg1 chatJID:(id)arg2;
- (id)outstandingStopLocationSharingRequests;
- (void)removeAllSendersInGroupJID:(id)arg1;
- (void)removeExpiredChatJIDs:(id)arg1;
- (void)removeExpiredFinalLocationRecords;
- (void)removeFinalLocationRecipientUserJIDs:(id)arg1;
- (void)removeFinalLocationRecipientUserJIDs:(id)arg1 inChatJID:(id)arg2;
- (void)removeFinalLocationRecipientsInChatJID:(id)arg1 message:(id)arg2;
- (void)removeFinalLocationRecords:(id)arg1;
- (void)removeLocationRecipientUserJIDs:(id)arg1;
- (void)removeLocationRecipientUserJIDs:(id)arg1 inChatJID:(id)arg2;
- (void)removeStopSharingLocationRequestInChatJID:(id)arg1;
- (void)save;
- (id)selectDistinct:(id)arg1 fromFinalLocationRecipientsWhere:(id)arg2;
- (id)selectDistinct:(id)arg1 fromLocationRecipientsWhere:(id)arg2;
- (id)selectDistinct:(id)arg1 objectsOfClass:(Class)arg2 predicate:(id)arg3;
- (id)selectMutableFromLocationSendersWhere:(id)arg1;
- (id)selectMutableFromStopLocationSharingRequestWhere:(id)arg1;
- (id)selectMutableObjectsOfClass:(Class)arg1 withPredicate:(id)arg2;
- (id)selectReadOnlyFromFinalLocationRecipientsWhere:(id)arg1;
- (id)selectReadOnlyFromLocationRecipientsWhere:(id)arg1;
- (id)selectReadOnlyFromLocationSendersWhere:(id)arg1;
- (id)selectReadOnlyFromStopLocationSharingRequestWhere:(id)arg1;
- (id)selectReadOnlyObjectsOfClass:(Class)arg1 withPredicate:(id)arg2;
- (void)setEndDate:(id)arg1 lastUpdate:(id)arg2 messageUniqueKey:(id)arg3 sequenceNumber:(long long)arg4 forChatAndUser:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)setLocationMessage:(id)arg1 timestamp:(id)arg2 forUserJID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)setStopLocationSharingRequestOutstandingInChatJID:(id)arg1 retryUntil:(id)arg2;
- (_Bool)stopSharingLocationRequestIDIsValid:(id)arg1;
- (void)updateCacheWithSenders:(id)arg1 forChat:(id)arg2;

@end

