//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CALayer;

@interface WAMaskedTextButton : UIButton
{
    CALayer *_maskLayer;
}

+ (id)button;
- (void).cxx_destruct;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

