//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CLLocation, CLPlacemark, WAMapView, WAPlace;

@protocol WAMapViewDelegate <NSObject>

@optional
- (void)mapView:(WAMapView *)arg1 didSelectLocation:(CLLocation *)arg2;
- (void)mapView:(WAMapView *)arg1 didSelectPlace:(WAPlace *)arg2;
- (void)mapView:(WAMapView *)arg1 didSelectPlacemark:(CLPlacemark *)arg2 location:(CLLocation *)arg3;
- (void)mapViewDidCancelInfoPanel:(WAMapView *)arg1;
- (void)mapViewDidChangeButtonsHeight:(WAMapView *)arg1;
- (void)mapViewDidFinishCrossFadeAnimation;
- (void)mapViewDidLiftStaticPin:(WAMapView *)arg1;
- (void)mapViewDidReverseGeocodeCurrentLocation:(CLPlacemark *)arg1;
- (void)mapViewDidSelectInfoButton:(WAMapView *)arg1;
- (void)mapViewWillReverseGeocodeCurrentLocation;
@end

