//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel, WAActivityIndicatorView;

@interface WAMessageExternalVideoSlicePIPOverlayView : UIView
{
    struct CGSize _lastLayoutSize;
    UIImageView *_imageView;
    UILabel *_titleView;
    WAActivityIndicatorView *_spinner;
    long long _state;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) long long state; // @synthesize state=_state;

@end

