//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView, WAMediaPickerAlbumTableViewCell, WAMediaPickerAsset, WAQuickMediaPreviewViewController;
@protocol UIViewControllerPreviewing;

@protocol WAMediaPickerAlbumTableViewCellDelegate <NSObject>
- (_Bool)mediaPickerAlbumTableViewCell:(WAMediaPickerAlbumTableViewCell *)arg1 didReceiveLongPressAtIndex:(long long)arg2;
- (_Bool)mediaPickerAlbumTableViewCell:(WAMediaPickerAlbumTableViewCell *)arg1 didReceiveTapAtIndex:(long long)arg2;
- (void)previewingContext:(id <UIViewControllerPreviewing>)arg1 inTableViewCell:(WAMediaPickerAlbumTableViewCell *)arg2 commitViewController:(WAQuickMediaPreviewViewController *)arg3;
- (WAQuickMediaPreviewViewController *)previewingContext:(id <UIViewControllerPreviewing>)arg1 viewControllerForAsset:(WAMediaPickerAsset *)arg2 inTableViewCell:(WAMediaPickerAlbumTableViewCell *)arg3;
- (id <UIViewControllerPreviewing>)registerPreviewingForAlbumCell:(WAMediaPickerAlbumTableViewCell *)arg1 sourceView:(UIView *)arg2;
- (void)unregisterForPreviewingWithContext:(id <UIViewControllerPreviewing>)arg1;
@end

