//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSliceView.h"

@class WAMessagePaymentDetailsSlice;

@interface WAMessagePaymentDetailsSliceView : WAMessageContainerSliceView
{
}

- (void)drawRect:(struct CGRect)arg1;
- (void)reloadSliceAfterChange:(unsigned long long)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessagePaymentDetailsSlice *slice; // @dynamic slice;

@end

