//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class NSArray;

@interface WAMessageStickerAlbumSlice : WAMessageContainerSlice
{
    long long _messagesCount;
    double _heightNeeded;
    _Bool _isFromMe;
    _Bool _shouldBeTwoLines;
}

+ (Class)viewClass;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (void)internalFitToWidth:(double)arg1;
- (double)leftMargin;
- (double)leftMarginForIndex:(long long)arg1;
- (_Bool)shouldBeTwoLines;
- (_Bool)showsMedia;

// Remaining properties
@property(readonly, nonatomic) NSArray *childrenSlices; // @dynamic childrenSlices;

@end

