//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAMessageAttributedTextSliceViewContentView;

@protocol WAMessageAttributedTextSliceViewContentViewDelegate <NSObject>
- (void)messageAttributedTextSliceViewContentView:(WAMessageAttributedTextSliceViewContentView *)arg1 prepareToDrawWithBlock:(void (^)(WAMessageAttributedTextSlice *, NSArray *))arg2;
@end

