//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessagePaymentInviteSliceView.h"

#import "WAScrollTracking-Protocol.h"

@interface WAMessagePaymentInviteSliceView (MainAppLibrary) <WAScrollTracking>
- (void)setNeedsUpdateScrollOffsetEffects;
@end

