//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageExternalVideoSlice.h"

@class WAMessageAdReplyThumbnailImageLoaderDataSource, WAMessageImageLoader;

@interface WAMessageExternalAdReplyVideoSlice : WAMessageExternalVideoSlice
{
    WAMessageAdReplyThumbnailImageLoaderDataSource *_dataSource;
    WAMessageImageLoader *_imageLoader;
}

+ (long long)maximumNumberOfLines;
- (void).cxx_destruct;
- (_Bool)containsExternalVideoForMessage:(id)arg1;
- (id)displayURLForMessage:(id)arg1;
- (void)fetchImageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (_Bool)isFromExternalAdReply;
- (int)previewTypeForMessage:(id)arg1;
- (id)snippetWithMessage:(id)arg1;
- (id)sourceURLStringWithMessage:(id)arg1;
- (id)titleWithMessage:(id)arg1;
- (void)wa_fetchHighResImageWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

