//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageTextWithImageSliceView.h"

@class WAMessageProductListContextSlice;

@interface WAMessageProductListSliceView : WAMessageTextWithImageSliceView
{
}

+ (_Bool)pairsWithQuickActionButton;
- (void)fetchImageWithCompletionHandler:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessageProductListContextSlice *slice; // @dynamic slice;

@end

