//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageMediaSlice.h"

@interface WAMessageProductSlice : WAMessageMediaSlice
{
    _Bool _messageFromMe;
}

+ (Class)viewClass;
@property(nonatomic, getter=isMessageFromMe) _Bool messageFromMe; // @synthesize messageFromMe=_messageFromMe;

@end

