//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary, WAMessageRegularSendTask;

@interface WAMessageSendQueue : NSObject
{
    NSMutableArray *_sortedSendingTasks;
    NSMutableArray *_sortedUploadTasks;
    NSMutableDictionary *_messageIDToTask;
    WAMessageRegularSendTask *_pendingSendTask;
}

- (void).cxx_destruct;
- (void)addTasksForSending:(id)arg1;
- (void)addTasksForUploading:(id)arg1;
- (void)clearPendingTaskForSending;
@property(readonly, nonatomic) unsigned long long count;
- (id)dequeueTaskForMessageSend;
- (id)init;
- (id)nextTaskForMediaUploadWithMediaUploadAttemptIdentifier:(id)arg1;
@property(readonly, nonatomic) WAMessageRegularSendTask *pendingSendTask; // @synthesize pendingSendTask=_pendingSendTask;
- (id)removeSendTaskWithParentMessageID:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *runningUploadTasks;
- (id)sendTaskForMessageID:(id)arg1;

@end

