//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class WAMessageID;
@protocol WAMessagePaymentCollectRequestActionSliceDelegate;

@interface WAMessagePaymentCollectRequestActionSlice : WAMessageContainerSlice
{
    _Bool _divider;
    _Bool _buttonsEnabled;
    id <WAMessagePaymentCollectRequestActionSliceDelegate> _delegate;
    WAMessageID *_messageID;
}

+ (Class)viewClass;
- (void).cxx_destruct;
@property(nonatomic) _Bool buttonsEnabled; // @synthesize buttonsEnabled=_buttonsEnabled;
@property(nonatomic) __weak id <WAMessagePaymentCollectRequestActionSliceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool divider; // @synthesize divider=_divider;
- (void)handleTransactionDidUpdateNotification:(id)arg1;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (void)internalFitToWidth:(double)arg1;
@property(readonly, nonatomic) WAMessageID *messageID; // @synthesize messageID=_messageID;

@end

