//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAMediaPlayerTransportControlView;

@protocol WAMediaPlayerTransportControlViewDelegate <NSObject>
- (_Bool)canMediaPlayerTransportControlViewBeginScrubbing:(WAMediaPlayerTransportControlView *)arg1;
- (void)mediaPlayerTransportControlViewDidBeginScrubbing:(WAMediaPlayerTransportControlView *)arg1;
- (void)mediaPlayerTransportControlViewDidChangeCurrentTime:(WAMediaPlayerTransportControlView *)arg1;
- (void)mediaPlayerTransportControlViewDidEndScrubbing:(WAMediaPlayerTransportControlView *)arg1;
@end

