//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class WAMessageAudioSlice;

@interface WAMessageAudioDurationView : UIView
{
    WAMessageAudioSlice *_slice;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) WAMessageAudioSlice *slice; // @synthesize slice=_slice;

@end

