//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSliceView.h"

@class UIImageView, UIView, WAMessagePlaceholderSlice, WAMessagePlaceholderView;

@interface WAMessagePlaceholderSliceView : WAMessageContainerSliceView
{
    UIView *_backgroundView;
    UIImageView *_iconImageView;
    WAMessagePlaceholderView *_placeholderTextView;
}

+ (_Bool)isUserInteractionEnabled;
+ (_Bool)supportsPreviewing;
- (void).cxx_destruct;
- (unsigned long long)accessibilityTraits;
- (void)handleSingleTapAtPoint:(struct CGPoint)arg1 forMessage:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isDoubleTapGestureEnabled;
- (void)reconfigureOnMessageChange;
- (void)relayout;
- (void)reloadSliceAfterChange:(unsigned long long)arg1;
- (void)traitCollectionDidChange:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessagePlaceholderSlice *slice; // @dynamic slice;

@end

