//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class NSArray;

@interface WAMessageStickerSlice : WAMessageContainerSlice
{
    double _stickerWidth;
    double _statusHeight;
    _Bool _isFromMe;
}

+ (Class)viewClass;
- (struct CGSize)checkmarkSize;
- (id)initWithMessage:(id)arg1 metrics:(id)arg2;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (void)internalFitToWidth:(double)arg1;
- (_Bool)isLeftPosition;
- (double)sharedMargin;
- (_Bool)showsMedia;
- (struct CGSize)statusSize;
- (struct CGSize)stickerSize;
- (double)topMargin;

// Remaining properties
@property(readonly, nonatomic) NSArray *childrenSlices; // @dynamic childrenSlices;

@end

