//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIAccessibilityElement.h>

@interface WAMessageAccessibilityElement : UIAccessibilityElement
{
    id _wa_accessibilityContainer;
    struct CGRect _frameInContainerCoordinateSpace;
}

- (void).cxx_destruct;
- (struct CGRect)accessibilityFrame;
@property(nonatomic) struct CGRect frameInContainerCoordinateSpace; // @synthesize frameInContainerCoordinateSpace=_frameInContainerCoordinateSpace;
@property(nonatomic) __weak id wa_accessibilityContainer; // @synthesize wa_accessibilityContainer=_wa_accessibilityContainer;

@end

