//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAMediaCopyMessageHelper.h>

@interface WAMediaCopyMessageHelper (MainApp)
+ (void)storeOutgoingMedia:(id)arg1 forJID:(id)arg2 MIMEType:(id)arg3 completion:(CDUnknownBlockType)arg4;
@end

