//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class NSArray;

@interface WAMessageMediaAlbumSlice : WAMessageContainerSlice
{
}

+ (Class)viewClass;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (void)internalFitToWidth:(double)arg1;
- (_Bool)showsMedia;

// Remaining properties
@property(readonly, nonatomic) NSArray *childrenSlices; // @dynamic childrenSlices;

@end

