//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageAttributedTextSlice.h"

@class NSAttributedString;

@interface WAMessageGroupInviteExpiredTextSlice : WAMessageAttributedTextSlice
{
    NSAttributedString *_text;
    double _bottomPadding;
}

+ (Class)viewClass;
- (void).cxx_destruct;
@property(readonly, nonatomic) double bottomPadding; // @synthesize bottomPadding=_bottomPadding;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (void)internalFitToWidth:(double)arg1;
- (void)setHighlightedWords:(id)arg1;

@end

