//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSIndexPath, UIImage, WAMediaBrowserThumbnailCollectionViewCell;

@protocol WAMediaBrowserThumbnailCollectionViewCellDelegate <NSObject>
- (UIImage *)imageForMediaThumbnailThumbnailCollectionViewCell:(WAMediaBrowserThumbnailCollectionViewCell *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)thumbnailCollectionViewCell:(WAMediaBrowserThumbnailCollectionViewCell *)arg1 thumbnailAtIndexPath:(NSIndexPath *)arg2 completion:(void (^)(UIImage *))arg3;
@end

