//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageButtonsSliceView.h"

@class UIButton, WAMessageViewStickerPackButtonSlice;

@interface WAMessageViewStickerPackButtonSliceView : WAMessageButtonsSliceView
{
    UIButton *_viewStickerPackButton;
}

- (void).cxx_destruct;
- (id)buttonsForCurrentState;
- (void)configureSlice:(id)arg1 withCellData:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewStickerPack:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessageViewStickerPackButtonSlice *slice; // @dynamic slice;

@end

