//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSliceView.h"

@class UIImage, UIImageView, WAMessageSenderNameContentView, WAMessageSenderNameSlice;

@interface WAMessageSenderNameSliceView : WAMessageContainerSliceView
{
    UIImage *_bubbleImage;
    UIImage *_highlightedBubbleImage;
    UIImageView *_bubbleImageView;
    WAMessageSenderNameContentView *_contentView;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)reloadSliceAfterChange:(unsigned long long)arg1;
- (void)setHighlighted:(_Bool)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessageSenderNameSlice *slice; // @dynamic slice;

@end

