//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAGenericMediaManager.h"

#import "NSFetchedResultsControllerDelegate-Protocol.h"

@class NSCalendar, NSDateComponents, NSDateFormatter, NSString;

@interface WAMessageMediaManager : WAGenericMediaManager <NSFetchedResultsControllerDelegate>
{
    unsigned long long _cachedPhotoCount;
    unsigned long long _cachedVideoCount;
    NSCalendar *_sharedGregorianCalendar;
    NSDateComponents *_currentDateComponents;
    NSDateFormatter *_currentYearDateFormatter;
    NSDateFormatter *_anyYearDateFormatter;
}

- (void).cxx_destruct;
- (id)accessibilityValueAtIndexPath:(id)arg1;
- (id)currentDateComponents;
- (id)datedTitleForHeaderMediaSectionID:(id)arg1;
- (id)indexPathOfMessage:(id)arg1;
- (id)init;
- (id)internalSetThumbnailPath:(id)arg1 forObjectID:(id)arg2;
- (void)loadIfNeeded;
- (id)messageAtIndexPath:(id)arg1;
- (void)modifyNumberOfMessagesOfType:(int)arg1 by:(long long)arg2;
- (unsigned long long)numberOfMessagesOfType:(int)arg1;
- (unsigned long long)numberOfPhotos;
- (unsigned long long)numberOfVideos;
- (void)reload;
- (id)sharedGregorianCalendar;
- (void)startCachingThumbnailsAtIndexPaths:(id)arg1;
- (void)stopCachingThumbnailsAtIndexPaths:(id)arg1;
- (id)textAtIndexPath:(id)arg1;
- (id)thumbnailAtIndexPath:(id)arg1;
- (id)thumbnailForMessage:(id)arg1;
- (id)uniqueIdentifier;
- (void)updateDateFormatters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

