//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageButtonsSlice.h"

@interface WAMessageViewInviteButtonSlice : WAMessageButtonsSlice
{
    _Bool _showTopDivider;
}

+ (Class)viewClass;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
@property(readonly, nonatomic) _Bool showTopDivider; // @synthesize showTopDivider=_showTopDivider;

@end

