//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageTextWithImageSliceView.h"

@class WAMessageWebPageSlice;

@interface WAMessageWebPageSliceView : WAMessageTextWithImageSliceView
{
}

+ (_Bool)pairsWithQuickActionButton;
+ (_Bool)supportsPreviewing;
- (id)dataForPreviewingContext:(id)arg1 location:(struct CGPoint)arg2;

// Remaining properties
@property(readonly, nonatomic) WAMessageWebPageSlice *slice; // @dynamic slice;

@end

