//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageReplyContextSliceView.h"

@interface WAMessagePaymentInviteReplyContextSliceView : WAMessageReplyContextSliceView
{
}

- (void)fetchImageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)reloadSliceAfterChange:(unsigned long long)arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end

