//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSNumber, NSString, UIImageView, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;
@protocol WAMediaBrowserCollectionViewCellDelegate;

@interface WAMediaBrowserCollectionViewCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    _Bool _isInitialLayoutPass;
    UIImageView *_blurredImageView;
    UITapGestureRecognizer *_doubleTapGesture;
    UILongPressGestureRecognizer *_longPressGesture;
    _Bool _displaying;
    _Bool _ignoresLayoutSubviews;
    _Bool _scrubbing;
    _Bool _needsUpdateLayoutInsets;
    id <WAMediaBrowserCollectionViewCellDelegate> _delegate;
    id _cellObject;
    double _parallaxOffset;
    NSString *_accessibilityLabelForContent;
    double _presentedStartTime;
    unsigned long long _zoomCount;
    NSNumber *_startedTappingOnImageTime;
}

+ (_Bool)supportsDoubleTapGesture;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *accessibilityLabelForContent; // @synthesize accessibilityLabelForContent=_accessibilityLabelForContent;
- (void)applyLayoutAttributes:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
@property(readonly, nonatomic) _Bool canPopFromCurrentState;
@property(retain, nonatomic) id cellObject; // @synthesize cellObject=_cellObject;
@property(nonatomic) __weak id <WAMediaBrowserCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didChangeObject;
- (void)didChangeObjectAtStage:(long long)arg1;
- (void)didLayoutSubviews;
- (void)didMoveToWindow;
- (void)didUpdateParallaxOffset;
- (void)fullScreenContainer:(_Bool)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleDoubleTap:(id)arg1;
- (void)handleDoubleTapAtPoint:(struct CGPoint)arg1;
- (void)handleLongPress:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (_Bool)handleSingleTapAtPoint:(struct CGPoint)arg1;
@property(nonatomic) _Bool ignoresLayoutSubviews; // @synthesize ignoresLayoutSubviews=_ignoresLayoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isDisplaying) _Bool displaying; // @synthesize displaying=_displaying;
@property(nonatomic, getter=isScrubbing) _Bool scrubbing; // @synthesize scrubbing=_scrubbing;
- (void)layoutSubviews;
- (void)layoutSubviewsInCell;
- (void)mediaBrowser_goToMessage:(id)arg1;
@property(readonly, nonatomic) _Bool needsUpdateLayoutInsets; // @synthesize needsUpdateLayoutInsets=_needsUpdateLayoutInsets;
- (id)newInteractiveAnnotationViewWithContainerView:(id)arg1;
- (void)openAnnotation:(id)arg1 atPoint:(struct CGPoint)arg2 fromAnnotationView:(id)arg3;
@property(readonly, nonatomic) double parallaxOffset; // @synthesize parallaxOffset=_parallaxOffset;
- (void)prepareForReuse;
@property(nonatomic) long long presentationState;
@property(nonatomic) double presentedStartTime; // @synthesize presentedStartTime=_presentedStartTime;
- (void)setNeedsUpdateLayoutInsets;
@property(retain, nonatomic) NSNumber *startedTappingOnImageTime; // @synthesize startedTappingOnImageTime=_startedTappingOnImageTime;
@property(nonatomic) unsigned long long zoomCount; // @synthesize zoomCount=_zoomCount;
- (_Bool)shouldBypassTwoStageLoading;
- (_Bool)shouldConsiderTouchForTaps:(struct CGPoint)arg1;
- (_Bool)supportsFullScreenPresentation;
@property(readonly, nonatomic) UIView *viewForLongPressGesture;
@property(readonly, nonatomic) UIView *visibleContentView;
- (void)willChangeObjectToObject:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

