//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class MISSING_TYPE;

@interface WAMessageViewOnceSlice : WAMessageContainerSlice
{
    MISSING_TYPE *metadataSectionHeight;
    MISSING_TYPE *message;
    MISSING_TYPE *currentMessageStatus;
    MISSING_TYPE *mayShowProgressView;
    MISSING_TYPE *titleTextRenderer;
    MISSING_TYPE *fileSizeTextRenderer;
    MISSING_TYPE *titleTextRect;
    MISSING_TYPE *fileSizeTextRect;
}

+ (Class)viewClass;
- (void).cxx_destruct;
- (id)initWithMessages:(id)arg1 metrics:(id)arg2;
- (void)internalFitToWidth:(double)arg1;
@property(nonatomic, readonly) _Bool showsMedia;

@end

