//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, WAChatStorage, WAMediaPickerStats, WAMessage, WAMessageAttachments, WAMultiSendMediaItemQuality, WAProductDescriptor;

@interface WAMultiSendMediaItemSender : NSObject
{
    WAChatStorage *_chatDataStore;
    NSArray *_items;
    NSArray *_chatSessions;
    WAMediaPickerStats *_pickerStats;
    NSMutableArray *_errors;
    WAMessage *_message;
    _Bool _openedFromURL;
    WAMultiSendMediaItemQuality *_quality;
    WAMessageAttachments *_attachments;
    double _minimumSendInterval;
    WAProductDescriptor *_productDescriptor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WAMessageAttachments *attachments; // @synthesize attachments=_attachments;
- (id)initWithItems:(id)arg1 toChatSessions:(id)arg2 chatDataStore:(id)arg3 pickerStatistics:(id)arg4;
- (id)initWithItems:(id)arg1 toChatSessions:(id)arg2 pickerStatistics:(id)arg3;
@property(nonatomic, getter=isOpenedFromURL) _Bool openedFromURL; // @synthesize openedFromURL=_openedFromURL;
@property(nonatomic) double minimumSendInterval; // @synthesize minimumSendInterval=_minimumSendInterval;
@property(retain, nonatomic) WAProductDescriptor *productDescriptor; // @synthesize productDescriptor=_productDescriptor;
@property(retain, nonatomic) WAMultiSendMediaItemQuality *quality; // @synthesize quality=_quality;
- (void)sendItem:(id)arg1 atIndex:(unsigned long long)arg2 group:(id)arg3;
- (void)sendItem:(id)arg1 exportedContentURL:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sendNextItemStartingAt:(unsigned long long)arg1 group:(id)arg2;
- (void)sendSingleItemToSingleChatWithCompletion:(CDUnknownBlockType)arg1;
- (void)sendWithCompletion:(CDUnknownBlockType)arg1;
- (void)sharedSendWithCompletion:(CDUnknownBlockType)arg1;

@end

