//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, UIViewController, WAMediaPickerStats, WAMultiSendMediaItem;

@protocol WAMultiSendMediaSendProcessorDelegate <NSObject>
- (void)convertPlaceholderItemToActualItemDidFailedWithIndex:(long long)arg1;
- (void)convertPlaceholderItemToActualItemDidSuccessWithOldMediaItem:(WAMultiSendMediaItem *)arg1 toNewMediaItem:(WAMultiSendMediaItem *)arg2;
- (void)exportAndPrepareOldMediaItem:(WAMultiSendMediaItem *)arg1 toNewMediaItem:(WAMultiSendMediaItem *)arg2;
- (void)hasConvertedItemWhenCancelExport;
- (WAMediaPickerStats *)mediaPickerStats;
- (void)sendProcessAndExportFinishSuccessWithProcessedItems:(NSArray *)arg1 mediaPickerStats:(WAMediaPickerStats *)arg2;
- (void)sendProcessFinishSuccessWithProcessedItems:(NSArray *)arg1;
- (void)sendProcessFinishWithErrorMessage:(NSString *)arg1 completion:(void (^)(void))arg2;
- (_Bool)shouldShowProgressViewDuringMediaExport;
- (UIViewController *)showingProgressViewOnThisViewController;
- (void)userCancelledAllExport;
- (_Bool)wantSaveMediaToCameraRoll;
@end

