//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIView;

@interface WANonRotatingWindowViewController : UIViewController
{
    UIView *_nonRotatingView;
}

- (void).cxx_destruct;
- (id)initWithView:(id)arg1;
- (void)loadView;
- (void)viewDidLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

