//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIWindow.h>

@interface WANonRotatingWindow : UIWindow
{
}

+ (id)showWithView:(id)arg1;

@end

