//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAOwnDeviceManager.h>

#import "WADevicePairingSessionDelegate-Protocol.h"
#import "WAOwnCompanionStateManaging-Protocol.h"
#import "WAOwnDeviceAccountSyncManaging-Protocol.h"
#import "WAOwnDeviceManagingMain-Protocol.h"
#import "WAOwnDeviceStorageManagerDelegate-Protocol.h"

@class NSSet, NSString, WADevicePairingSession, WAOwnDeviceList, WAOwnDeviceNetworkRequestManager, WAOwnDeviceStorageManagerMain, WARemovedOwnDeviceStorageManager, WAUserSessionPreferences;
@protocol WAAppStateSyncDeletionHandling, WADateProvider, WAOwnCompanionStateManaging, WAOwnDeviceAccountSyncManaging, WAOwnDeviceManagerDeviceListDelegate, WAOwnDeviceManagerMainABProperties, WAOwnDeviceManagingMain, WAOwnDeviceSigning;

@interface WAOwnDeviceManagerMain : WAOwnDeviceManager <WAOwnCompanionStateManaging, WAOwnDeviceAccountSyncManaging, WAOwnDeviceManagingMain, WADevicePairingSessionDelegate, WAOwnDeviceStorageManagerDelegate>
{
    WARemovedOwnDeviceStorageManager *_removedDeviceStorageManager;
    WAOwnDeviceStorageManagerMain *_storageManager;
    WAOwnDeviceNetworkRequestManager *_networkManager;
    WAUserSessionPreferences *_userPreferences;
    id <WADateProvider> _dateProvider;
    WADevicePairingSession *_pairingSession;
    id <WAOwnDeviceManagerDeviceListDelegate> _deviceListDelegate;
    id <WAOwnDeviceManagerMainABProperties> _abProperties;
    id <WAOwnDeviceSigning> _deviceSigning;
    id <WAAppStateSyncDeletionHandling> _appStateDeletionHandler;
}

- (void).cxx_destruct;
- (id)addCompanionDeviceWithCode:(id)arg1 startTimestamp:(double)arg2 fromViewController:(id)arg3 completion:(CDUnknownBlockType)arg4;
@property(nonatomic) __weak id <WAAppStateSyncDeletionHandling> appStateDeletionHandler; // @synthesize appStateDeletionHandler=_appStateDeletionHandler;
- (void)cancelInProgressPairingSessions;
- (void)clearRecentlyRemovedDevices;
- (id)companionDevices;
@property(nonatomic) __weak id <WAOwnDeviceManagerDeviceListDelegate> deviceListDelegate;
- (void)devicePairingSession:(id)arg1 didRequestPairDeviceWithRef:(id)arg2 authKey:(id)arg3 identityKey:(id)arg4 deviceIdentity:(id)arg5 keyIndexList:(id)arg6 completion:(CDUnknownBlockType)arg7;
- (void)devicePairingSession:(id)arg1 didRequestRemoveAllCompanionDevicesWithCompletion:(CDUnknownBlockType)arg2;
- (_Bool)devicePairingSession:(id)arg1 didRequestStoreCompanionDevices:(id)arg2 withUpdatedKeyIndexList:(id)arg3;
- (void)devicePairingSessionDidComplete:(id)arg1;
- (id)devicePairingSessionDidRequestCurrentDeviceList:(id)arg1;
- (id)devicePairingSessionDidRequestNextKeyListForNewDevice:(id)arg1 retryTimestamp:(unsigned long long)arg2 error:(id *)arg3;
@property(nonatomic) __weak id <WAOwnDeviceSigning> deviceSigning; // @synthesize deviceSigning=_deviceSigning;
- (void)didReceiveOwnAccountSyncWithDeviceList:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool hasCompanions;
- (id)initWithKeyValueStore:(id)arg1 optInStateManager:(id)arg2 userPreferences:(id)arg3 abProperties:(id)arg4;
@property(readonly, nonatomic) id <WAOwnDeviceManagingMain> mainManager;
- (id)nextKeyListWithRetryTimestamp:(unsigned long long)arg1 addingDevice:(_Bool)arg2 error:(id *)arg3;
@property(readonly, nonatomic) id <WAOwnCompanionStateManaging> ownStateManaging;
- (void)performOnConnect;
- (id)recentlyRemovedCompanionDevice:(id)arg1;
- (id)recentlyRemovedCompanionDevices;
- (void)removeAllCompanionDevices:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)removeAllCompanionDevicesWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeCompanionWithJID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)removeDevicesForSignOut;
- (void)removeRecentlyRemovedCompanionDevices:(id)arg1 notify:(_Bool)arg2;
- (void)removeUnrecognizedDeviceJIDs:(id)arg1;
- (_Bool)shouldRecognizeDeviceWithJID:(id)arg1;
- (_Bool)shouldUpdateServerKeyIndexList;
- (void)storeInitialKeyIndexListWithRawID:(unsigned int)arg1 timestamp:(unsigned long long)arg2 keyIndex:(unsigned int)arg3 error:(id *)arg4;
- (void)submitLinkDeviceFieldStatsEventWithQRCode:(id)arg1 startTimestamp:(double)arg2 stage:(long long)arg3 errorCode:(long long)arg4;
@property(readonly, nonatomic) id <WAOwnDeviceAccountSyncManaging> syncManager;
- (void)updateCompanionDevice:(id)arg1 withLastSeenDate:(id)arg2 isActiveNow:(_Bool)arg3;
- (void)updateServerKeyIndexListIfNecessaryWithRetryTimestamp:(unsigned long long)arg1;

// Remaining properties
@property(readonly, nonatomic) unsigned long long companionCount;
@property(readonly, nonatomic) NSSet *companionDeviceJIDs;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) WAOwnDeviceList *deviceList;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

