//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WADeviceJID;

@protocol WAOwnDeviceManaging <NSObject>
- (void)removeCompanionWithJID:(WADeviceJID *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
@end

