//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WAContactGridViewControllerDataSource-Protocol.h"
#import "WAContactGridViewControllerDelegate-Protocol.h"

@class NSArray, NSDictionary, NSLayoutConstraint, NSMutableSet, NSSet, NSString, UIBarButtonItem, UISearchBar, UITableView, UIView, WABlocklistAlertManager, WACachedCopyMutableArray, WAChatJID, WAContactGridViewController, WAContactsSearchController, WAContactsSection, WAContactsStorage, WADropDownAlertView, WALabelAndButtonHeaderView, WANavigationBarTitleView, WAParticipantPickerConfiguration;
@protocol WAParticipantPickerViewControllerDelegate;

@interface WAParticipantPickerViewController : WAViewController <UISearchBarDelegate, WAContactGridViewControllerDataSource, WAContactGridViewControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_sections;
    WAContactsSearchController *_searchController;
    WAContactsSearchController *_invitableSearchController;
    WACachedCopyMutableArray *_selectedContacts;
    NSMutableSet *_selectedGroups;
    WAContactsSection *_searchResults;
    WAContactsSection *_invitableSearchResults;
    WAParticipantPickerConfiguration *_config;
    double _keyboardHeight;
    _Bool _needsRefreshOnContactsSync;
    long long _minContacts;
    long long _maxContacts;
    UIBarButtonItem *_toolbarButton;
    UIView *_noResultsView;
    WADropDownAlertView *_selectionLimitDropdownAlertView;
    NSLayoutConstraint *_noResultsViewBottomMargin;
    WAContactsSection *_groupSection;
    WALabelAndButtonHeaderView *_groupsInCommonSectionHeaderView;
    WABlocklistAlertManager *_blocklistAlertManager;
    WAContactsStorage *_contactsStorage;
    _Bool _resetContentOffsetOnSearchStart;
    _Bool _showAllGroupsInCommon;
    id <WAParticipantPickerViewControllerDelegate> _delegate;
    WAChatJID *_groupOrListJID;
    NSSet *_selectedJIDs;
    NSSet *_lockedJIDs;
    NSMutableSet *_pendingJIDs;
    NSArray *_allContacts;
    NSDictionary *_contactsDict;
    UISearchBar *_searchBar;
    UITableView *_tableView;
    WANavigationBarTitleView *_titleView;
    WAContactGridViewController *_contactGridViewController;
    NSArray *_actionRows;
    WAContactsSection *_actionsSection;
    NSSet *_adminJIDs;
}

+ (id)aboutTextForGroupInCommonWithContactNames:(id)arg1;
- (void).cxx_destruct;
- (id)aboutTextForGroupContact:(id)arg1;
@property(copy, nonatomic) NSArray *actionRows; // @synthesize actionRows=_actionRows;
@property(retain, nonatomic) WAContactsSection *actionsSection; // @synthesize actionsSection=_actionsSection;
- (void)addActionSectionToSections:(id)arg1;
@property(copy, nonatomic) NSSet *adminJIDs; // @synthesize adminJIDs=_adminJIDs;
@property(readonly, copy, nonatomic) NSArray *allContacts; // @synthesize allContacts=_allContacts;
- (id)allKnownParticipantsContactsFromGroupWithGroupJID:(id)arg1;
- (_Bool)canShowNoResultsView;
- (void)cancelAction:(id)arg1;
- (void)configureCell:(id)arg1 forContact:(id)arg2;
- (void)configureInviteCell:(id)arg1 forContact:(id)arg2 inTableView:(id)arg3 atIndexPath:(id)arg4;
- (void)configureTableViewRowHeight;
- (id)contactForCellIndexPath:(id)arg1;
@property(retain, nonatomic) WAContactGridViewController *contactGridViewController; // @synthesize contactGridViewController=_contactGridViewController;
- (id)contactGridViewController:(id)arg1 contactAtIndex:(unsigned long long)arg2;
- (void)contactGridViewController:(id)arg1 didTapCallButtonIsVideo:(_Bool)arg2;
- (void)contactGridViewController:(id)arg1 requestedToDeleteContactAtIndex:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long contactsCount;
@property(readonly, copy, nonatomic) NSDictionary *contactsDict; // @synthesize contactsDict=_contactsDict;
- (id)createContactsInThisGroupSection;
- (id)createGroupsInCommonSection;
- (id)currentDataSource;
- (id)dedupedContacts;
@property(nonatomic) __weak id <WAParticipantPickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deselectContacts:(id)arg1 updateTableView:(id)arg2 resetPreviousSelection:(_Bool)arg3;
- (void)deselectGroupsInCommonCellsForConsistency;
- (void)didSelectGroupInCommonCellAtIndexPath:(id)arg1;
- (void)didSelectIndividualCellAtIndexPath:(id)arg1 cell:(id)arg2;
- (void)doneAction:(id)arg1;
- (id)fetchCommonGroupsChatSessionsWithContact:(id)arg1;
@property(retain, nonatomic) WAChatJID *groupOrListJID; // @synthesize groupOrListJID=_groupOrListJID;
- (id)indexPathForContact:(id)arg1;
- (id)init;
- (id)initWithConfig:(id)arg1 contactsStorage:(id)arg2;
- (void)insertUnknownSelectedContacts:(id)arg1;
- (_Bool)isDisplayingAllDeviceContacts;
- (_Bool)isDisplayingGroupParticipants;
@property(readonly, nonatomic, getter=isDisplayingSearchResults) _Bool displayingSearchResults;
- (_Bool)isIndexPathAnActionCell:(id)arg1;
- (_Bool)isSingleContactSelectionMode;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)loadContactsIfNeeded;
- (void)loadView;
@property(copy, nonatomic) NSSet *lockedJIDs; // @synthesize lockedJIDs=_lockedJIDs;
- (id)makeContactGrid;
- (id)noResultsBackgroundView;
- (id)noResultsStackView;
- (unsigned long long)numberOfContactsInContactGridViewController:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) NSMutableSet *pendingJIDs; // @synthesize pendingJIDs=_pendingJIDs;
- (void)presentUnblockActionSheetForContact:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)processContactSelection:(id)arg1 withSelectedJIDs:(id)arg2;
- (void)reloadContacts;
- (void)reloadContactsAndData;
@property(nonatomic) _Bool resetContentOffsetOnSearchStart; // @synthesize resetContentOffsetOnSearchStart=_resetContentOffsetOnSearchStart;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (_Bool)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchContactsWithText:(id)arg1;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)sections;
- (void)selectAllButtonPressed:(id)arg1;
- (void)selectContacts:(id)arg1 updateTableView:(id)arg2;
@property(copy, nonatomic) NSArray *selectedContacts;
@property(copy, nonatomic) NSSet *selectedJIDs; // @synthesize selectedJIDs=_selectedJIDs;
- (id)selectedJIDsForContacts:(id)arg1;
- (unsigned long long)selectionStateForContact:(id)arg1 shouldSelect:(_Bool)arg2;
- (void)setCellSelectionStatusWithContact:(id)arg1 selectionState:(unsigned long long)arg2;
- (void)setContactGridHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSearchResultsContacts:(id)arg1 invitableContacts:(id)arg2 forSearchText:(id)arg3;
@property(nonatomic) _Bool showAllGroupsInCommon; // @synthesize showAllGroupsInCommon=_showAllGroupsInCommon;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) WANavigationBarTitleView *titleView; // @synthesize titleView=_titleView;
- (void)showAllGroupsInCommonAction;
- (void)showContactsSelectionLimitWarning;
- (void)showNoResultsView:(_Bool)arg1;
- (_Bool)showToolbar;
- (void)sortContactArray:(id)arg1;
- (void)syncManagerDidFinishSync:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (_Bool)updateContactSelection:(id)arg1 shouldClearSearch:(_Bool *)arg2 sourceView:(id)arg3;
- (void)updateInterfaceOnSelectionChange;
- (void)updateTableViewInsets;
- (void)updateTitleViewToCurrentInterfaceOrientation;
- (void)updateToolbarIfNecessary;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)wa_fontSizeDidChange;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

