//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImage, WAPaintCanvasTextureManager;

@protocol WAPaintCanvasTextureManagerImageDataSource <NSObject>
- (UIImage *)textureManager:(WAPaintCanvasTextureManager *)arg1 imageWithIdentifier:(NSString *)arg2 cropped:(_Bool)arg3;
@end

