//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAPaymentMerchantManagerFactory : NSObject
{
}

+ (id)merchantManagerWith:(id)arg1 paymentSettings:(id)arg2 persistentRequestManager:(id)arg3;
- (id)init;

@end

