//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAPaymentBaseHandlerErrorDelegate-Protocol.h"

@class NSArray, WAPaymentBaseTransaction, WAPaymentConfiguration, WAPaymentTransactionHandler;

@protocol WAPaymentTransactionHandlerDelegate <WAPaymentBaseHandlerErrorDelegate>
- (void)transactionHandler:(WAPaymentTransactionHandler *)arg1 didSucceedWithTransaction:(WAPaymentBaseTransaction *)arg2;
- (void)transactionHandlerWithHandler:(WAPaymentTransactionHandler *)arg1 didInviteContacts:(NSArray *)arg2 forConfiguration:(WAPaymentConfiguration *)arg3;
@end

