//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WAPaymentOnboardBannerCell;

@protocol WAPaymentOnboardBannerCellDelegate
- (void)paymentOnboardBannerTableViewCellDidTapDismiss:(WAPaymentOnboardBannerCell *)arg1;
@end

