//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAPasscodeView;

@protocol WAPasscodeViewDelegate <NSObject>
- (void)passcodeViewDidEnterPasscode:(WAPasscodeView *)arg1;

@optional
- (_Bool)passcodeViewCanResignFirstResponder:(WAPasscodeView *)arg1;
@end

