//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAPaymentParticipantPickerHandlerDelegate-Protocol.h"

@class UIViewController;

@protocol WAPaymentUPIParticipantPickerHandlerDelegate <WAPaymentParticipantPickerHandlerDelegate>
- (void)participantPickerDidSelectPaymentScanQRCode:(UIViewController *)arg1;
- (void)participantPickerDidSelectSendToHandle:(UIViewController *)arg1;
@end

