//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/GPBMessage.h>

@class NSMutableArray, NSString, WAPBHistorySyncPersistentState_Progress;

@interface WAPBHistorySyncPersistentState : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *companionJid; // @dynamic companionJid;
@property(retain, nonatomic) NSMutableArray *conversationsArray; // @dynamic conversationsArray;
@property(readonly, nonatomic) unsigned long long conversationsArray_Count; // @dynamic conversationsArray_Count;
@property(nonatomic) _Bool hasCompanionJid; // @dynamic hasCompanionJid;
@property(nonatomic) _Bool hasProgress; // @dynamic hasProgress;
@property(retain, nonatomic) WAPBHistorySyncPersistentState_Progress *progress; // @dynamic progress;
@property(retain, nonatomic) NSMutableArray *sessionsArray; // @dynamic sessionsArray;
@property(readonly, nonatomic) unsigned long long sessionsArray_Count; // @dynamic sessionsArray_Count;
@property(retain, nonatomic) NSMutableArray *statusConversationsArray; // @dynamic statusConversationsArray;
@property(readonly, nonatomic) unsigned long long statusConversationsArray_Count; // @dynamic statusConversationsArray_Count;

@end

