//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAPBWebMessageInfo.h>

@interface WAPBWebMessageInfo (WebClient)
- (void)setGenericNotification:(id)arg1;
- (void)setStubType:(int)arg1;
- (void)setStubType:(int)arg1 param:(id)arg2;
- (void)setStubType:(int)arg1 param:(id)arg2 param:(id)arg3;
- (void)setStubType:(int)arg1 paramArray:(id)arg2;
@end

