//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/GPBMessage.h>

@class NSString;

@interface WAPBCatalogCartMetadata : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *businessOwnerJid; // @dynamic businessOwnerJid;
@property(nonatomic) _Bool hasBusinessOwnerJid; // @dynamic hasBusinessOwnerJid;
@property(nonatomic) _Bool hasNote; // @dynamic hasNote;
@property(copy, nonatomic) NSString *note; // @dynamic note;

@end

