//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/GPBMessage.h>

@interface WAPBRapidDecaySet : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float decay01; // @dynamic decay01;
@property(nonatomic) float decay05; // @dynamic decay05;

@end

