//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/GPBMessage.h>

@class NSMutableArray, NSString;

@interface WAPBCatalogCart : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *businessOwnerJid; // @dynamic businessOwnerJid;
@property(nonatomic) _Bool hasBusinessOwnerJid; // @dynamic hasBusinessOwnerJid;
@property(retain, nonatomic) NSMutableArray *itemsArray; // @dynamic itemsArray;
@property(readonly, nonatomic) unsigned long long itemsArray_Count; // @dynamic itemsArray_Count;

@end

