//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/GPBMessage.h>

@class NSData;

@interface WAPBRegistrationToken : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *backupTokenData; // @dynamic backupTokenData;
@property(nonatomic) unsigned long long creationTimestamp; // @dynamic creationTimestamp;
@property(nonatomic) _Bool hasBackupTokenData; // @dynamic hasBackupTokenData;
@property(nonatomic) _Bool hasCreationTimestamp; // @dynamic hasCreationTimestamp;
@property(nonatomic) _Bool hasRecoveryTokenData; // @dynamic hasRecoveryTokenData;
@property(nonatomic) _Bool hasVersion; // @dynamic hasVersion;
@property(copy, nonatomic) NSData *recoveryTokenData; // @dynamic recoveryTokenData;
@property(nonatomic) int version; // @dynamic version;

@end

