//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/GPBMessage.h>

@interface WAPBSMBUpsellBannerState : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long expiryTimestamp; // @dynamic expiryTimestamp;
@property(nonatomic) _Bool hasExpiryTimestamp; // @dynamic hasExpiryTimestamp;
@property(nonatomic) _Bool hasImpressionDayCountInCurrentPeriod; // @dynamic hasImpressionDayCountInCurrentPeriod;
@property(nonatomic) _Bool hasImpressionDayCountTotal; // @dynamic hasImpressionDayCountTotal;
@property(nonatomic) _Bool hasLastImpressionTimestamp; // @dynamic hasLastImpressionTimestamp;
@property(nonatomic) _Bool hasTapCount; // @dynamic hasTapCount;
@property(nonatomic) _Bool hasUserDismissed; // @dynamic hasUserDismissed;
@property(nonatomic) long long impressionDayCountInCurrentPeriod; // @dynamic impressionDayCountInCurrentPeriod;
@property(nonatomic) long long impressionDayCountTotal; // @dynamic impressionDayCountTotal;
@property(nonatomic) long long lastImpressionTimestamp; // @dynamic lastImpressionTimestamp;
@property(nonatomic) long long tapCount; // @dynamic tapCount;
@property(nonatomic) _Bool userDismissed; // @dynamic userDismissed;

@end

