//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WAPhoneProxy : NSObject
{
    NSString *_phoneNumber;
    NSString *_localizedPhoneNumber;
    NSString *_label;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(copy, nonatomic) NSString *localizedPhoneNumber; // @synthesize localizedPhoneNumber=_localizedPhoneNumber;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;

@end

