//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITextField.h>

@class UIFont, WACountryCode, WAPhoneNumberTextFieldHelper;
@protocol WAPhoneNumberTextFieldDelegate;

@interface WAPhoneNumberTextField : UITextField
{
    WAPhoneNumberTextFieldHelper *_textFieldHelper;
    UIFont *_phoneNumberFont;
    WACountryCode *_countryCode;
    id <WAPhoneNumberTextFieldDelegate> _textFieldDelegate;
}

- (void).cxx_destruct;
- (void)accessibilityElementDidLoseFocus;
- (id)accessibilityLabel;
- (id)accessibilityValue;
- (void)awakeFromNib;
- (void)commonInit;
@property(retain, nonatomic) WACountryCode *countryCode; // @synthesize countryCode=_countryCode;
- (id)formattedFullOrLocalString:(id)arg1 removingCountryCode:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIFont *phoneNumberFont; // @synthesize phoneNumberFont=_phoneNumberFont;
- (void)reformatTextField;
- (void)setFrame:(struct CGRect)arg1;
- (void)setPlaceholder:(id)arg1;
- (void)setText:(id)arg1;
@property(nonatomic) __weak id <WAPhoneNumberTextFieldDelegate> textFieldDelegate; // @synthesize textFieldDelegate=_textFieldDelegate;

@end

