//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString;

@interface WAPhoneNumberTextFieldHelper : NSObject <UITextFieldDelegate>
{
}

+ (void)initialize;
+ (_Bool)isStringADecimalNumber:(id)arg1;
+ (id)stringByKeepingOnlyDecimalDigits:(id)arg1;
- (unsigned long long)endPositionOfPrefix:(id)arg1 inFormattedString:(id)arg2;
- (struct _NSRange)expandRange:(struct _NSRange)arg1 inTextFieldToIncludeNumber:(id)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

