//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMediaCollectionViewCell.h"

#import "WAMediaPickerAssetPresenting-Protocol.h"

@class NSString, WAMediaPickerAsset;

@interface WAPhotoLibraryCollectionViewCell : WAMediaCollectionViewCell <WAMediaPickerAssetPresenting>
{
    int _pendingRequestID;
    _Bool _showsCheckmarkWhenSelected;
    long long _index;
    NSString *_assetIdentifier;
    WAMediaPickerAsset *_mediaPickerAsset;
    struct CGSize _maximumThumbnailSizeInPixels;
}

- (void).cxx_destruct;
- (void)addAssetDownloadProgressNotifications;
@property(readonly, nonatomic) NSString *assetIdentifier; // @synthesize assetIdentifier=_assetIdentifier;
- (void)configureProgressBar;
@property(nonatomic) long long index; // @synthesize index=_index;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGSize maximumThumbnailSizeInPixels; // @synthesize maximumThumbnailSizeInPixels=_maximumThumbnailSizeInPixels;
@property(retain, nonatomic) WAMediaPickerAsset *mediaPickerAsset; // @synthesize mediaPickerAsset=_mediaPickerAsset;
- (void)mediaPickerAssetDidDownloadProgressFinished:(id)arg1;
- (void)mediaPickerAssetDidUpdateDownloadProgress:(id)arg1;
- (void)removeAssetDownloadProgressNotifications;
@property(nonatomic) _Bool showsCheckmarkWhenSelected; // @synthesize showsCheckmarkWhenSelected=_showsCheckmarkWhenSelected;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

