//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WADeletionBatch.h"

@class WAChatSession;

@interface WAPrepareRevokeDeletionBatch : WADeletionBatch
{
    WAChatSession *_chatSession;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WAChatSession *chatSession; // @synthesize chatSession=_chatSession;
- (void)evaluate:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)initWithCapacity:(unsigned long long)arg1 chatSession:(id)arg2;

@end

