//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WANetworkUsageManager.h>

@class NSURL;

@interface WAPrimaryNetworkUsageManager : WANetworkUsageManager
{
    NSURL *_fileURL;
}

- (void).cxx_destruct;
- (id)initWithSynchronizeInterval:(double)arg1 fileURL:(id)arg2;
- (id)internalCreate;
- (id)internalLoad;
- (void)internalSave:(id)arg1;
- (_Bool)mergeFromKeyValueStore:(id)arg1;
- (void)migrateFromDictionary:(id)arg1;
- (void)migrateFromUserDefaults:(id)arg1;

@end

