//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface WAProgressView : UIView
{
    UIView *_progressView;
    UIColor *_progressColor;
    double _progress;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initializeSubviews;
- (void)layoutSubviews;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIColor *progressColor; // @synthesize progressColor=_progressColor;

@end

