//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSSet;

@protocol WAPrivacySettingsProviding
- (_Bool)isPolicyV2;
- (NSSet *)loadGroupAddBlocklistUserJIDsAndReturnError:(id *)arg1;
- (void)loadPrivacySettingsIfNeeded;
- (void)setNeedsGroupsBlacklistDownstreamSync;
- (void)update:(unsigned long long)arg1 with:(unsigned long long)arg2;
- (void)updateGroupAddBlocklistWith:(NSSet *)arg1;
- (unsigned long long)valueFor:(unsigned long long)arg1;
@end

