//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, WAProblemInputController;

@protocol WAProblemInputControllerDelegate <NSObject>
- (void)problemInputController:(WAProblemInputController *)arg1 didCancelWithText:(NSString *)arg2 imageAttachments:(NSArray *)arg3;
- (void)problemInputController:(WAProblemInputController *)arg1 didFinishWithText:(NSString *)arg2 logsAttachment:(NSString *)arg3 imageAttachments:(NSArray *)arg4;
@end

