//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAPrivacySettingsProviding-Protocol.h"
#import "WASyncedContactListProvidingMainApp-Protocol.h"

@class NSArray, NSString, WASyncedContactList;

@interface WAPrivacyPolicy : NSObject <WASyncedContactListProvidingMainApp, WAPrivacySettingsProviding>
{
    unsigned long long _privacySetting[4];
    long long _pendingRequestID[4];
    _Bool _needRefetch;
    unsigned long long _previousPrivacySetting[4];
    WASyncedContactList *_groupsBlacklist;
    NSString *_currentHash;
    NSString *_temporaryHash;
    _Bool _settingGroupPrivacyValue;
    _Bool _hashMismatchedOnSet;
    _Bool _fetchingBlacklist;
}

+ (unsigned long long)settingValueForXMPPString:(id)arg1;
+ (id)stringForSetting:(unsigned long long)arg1;
+ (id)xmppStringForSettingCategory:(unsigned long long)arg1;
+ (id)xmppStringForSettingValue:(unsigned long long)arg1;
- (void).cxx_destruct;
- (id)blacklistHash;
- (void)fetchJIDsForSyncedContactList:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSArray *groupsBlacklist;
- (void)ignoreResultsOfPendingRequests;
- (id)init;
- (_Bool)isPolicyV2;
@property(nonatomic) _Bool listInSync;
- (id)loadGroupAddBlocklistUserJIDsAndReturnError:(id *)arg1;
- (void)loadPrivacySettingsIfNeeded;
- (id)pathToPendingContactsStoreForSyncedContactList:(id)arg1;
- (void)permanentlySaveJIDs:(id)arg1 forSyncedContactList:(id)arg2;
- (id)permanentlySavedJIDsForSyncedContactList:(id)arg1;
- (void)postPrivacySettingUpdateUpstream:(_Bool)arg1 error:(id)arg2;
- (void)resetPolicy;
- (void)resetValues;
- (void)setAndPostPrivacySettingCategory:(unsigned long long)arg1 value:(unsigned long long)arg2 error:(id)arg3;
- (void)setNeedsGroupsBlacklistDownstreamSync;
- (void)setPrivacy:(unsigned long long)arg1 forCategory:(unsigned long long)arg2 blacklist:(id)arg3;
- (unsigned long long)settingForCategory:(unsigned long long)arg1;
- (void)syncedContactList:(id)arg1 didRequestSendContacts:(id)arg2 pendingContacts:(id)arg3 webClientRequestID:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)syncedContactListDidUpdate:(id)arg1;
- (void)update:(unsigned long long)arg1 with:(unsigned long long)arg2;
- (void)updateGroupAddBlocklistWith:(id)arg1;
- (unsigned long long)valueFor:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

