//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WAPttSlider;

@protocol WAPttSliderDelegate
- (_Bool)pttSliderShouldUseLargeThumbImage:(WAPttSlider *)arg1;
@end

