//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAPTTMessageHelper.h>

@interface WAPTTMessageHelper (MainApp)
+ (id)stringRepresentationForChatCellForMessage:(id)arg1 withSenderName:(id)arg2;
+ (id)stringRepresentationForChatForMessage:(id)arg1;
+ (id)stringRepresentationForNotificationForMessage:(id)arg1;
@end

