//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WAQRCodeController;

@protocol WAQRCodeControllerDelegate <NSObject>
- (_Bool)qrCodeController:(WAQRCodeController *)arg1 shouldAcceptCode:(NSString *)arg2;
@end

