//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "WALinkLabelDelegate-Protocol.h"

@class NSString, UIButton, WAContactQRCodeContactCardView, WALinkLabel, WAQRCodeContactCardViewConfiguration;

@interface WAQRViewController : WAViewController <WALinkLabelDelegate>
{
    _Bool _openedControlCenter;
    _Bool _isBrightnessReset;
    WAQRCodeContactCardViewConfiguration *_config;
    WAContactQRCodeContactCardView *_qrCardView;
    WALinkLabel *_infoLabel;
    UIButton *_revokeButton;
    double _originalBrightness;
    NSString *_caption;
    NSString *_activityViewHeading;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *activityViewHeading; // @synthesize activityViewHeading=_activityViewHeading;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
@property(copy, nonatomic) NSString *caption; // @synthesize caption=_caption;
- (void)commonInit;
@property(retain, nonatomic) WAQRCodeContactCardViewConfiguration *config; // @synthesize config=_config;
- (_Bool)enableStatusSelectionInForwardActivity;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
@property(retain, nonatomic) WALinkLabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)installLayoutConstraints;
@property(nonatomic) _Bool isBrightnessReset; // @synthesize isBrightnessReset=_isBrightnessReset;
@property(nonatomic) double originalBrightness; // @synthesize originalBrightness=_originalBrightness;
- (void)prepareSharingView;
- (void)prepareSharingViewCaption;
@property(retain, nonatomic) WAContactQRCodeContactCardView *qrCardView; // @synthesize qrCardView=_qrCardView;
@property(retain, nonatomic) UIButton *revokeButton; // @synthesize revokeButton=_revokeButton;
- (void)revokeCode:(id)arg1;
- (void)revokeQRNotificationDidPresent:(id)arg1;
- (void)setupUIComponents;
- (id)sharedImage;
- (void)showActivityControllerFromBarButtonItem:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

