//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, NSSet, NSString, WAStorage;

@protocol WARankingStorageDelegate
- (NSString *)debugStringForKey:(NSData *)arg1;
- (NSSet *)rankingStorage:(WAStorage *)arg1 needsLinksForMetricSetWithKey:(NSData *)arg2;
- (NSData *)rankingStorage:(WAStorage *)arg1 needsNewKeyForMetricSetWithKey:(NSData *)arg2;
@end

