//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAMessage, WAPBHydratedTemplateButton, WAPBMessage_ButtonsMessage_Button;

@protocol WAReplyButtonsCellViewModelDelegate <NSObject>
- (void)replyButtonCellDidSelectButtonMessageWithButtonData:(WAPBMessage_ButtonsMessage_Button *)arg1 forMessage:(WAMessage *)arg2;
- (void)replyButtonsCellDidSelectHSMWithButtonData:(WAPBHydratedTemplateButton *)arg1 buttonIndex:(unsigned int)arg2 forMessage:(WAMessage *)arg3;
@end

