//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileManager, NSNotificationCenter, NSString, WADeviceJID, WAPhoneNumber, WAProcess, WASignalManager, WAUUID, WAUserJID;

@interface WARegistrationManagerDependencyProvider : NSObject
{
    WASignalManager *_signalManager;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WAUUID *WAUUID;
- (id)certificateDetailsFromData:(id)arg1 error:(inout id *)arg2;
- (id)certificateFromData:(id)arg1 error:(inout id *)arg2;
@property(readonly, nonatomic) WAProcess *currentProcess;
- (id)dateWithTimeIntervalSinceDeviceNow:(double)arg1;
@property(readonly, nonatomic) WADeviceJID *deviceJID;
- (id)deviceNow;
@property(readonly, nonatomic) _Bool disableICloudKeychainRegistrationToken;
- (id)domainFrontingProviderStore;
@property(readonly, nonatomic) double domainProbeCacheInterval;
@property(readonly, nonatomic) double domainProbeRetryInterval;
- (id)fetcherWithURLString:(id)arg1 pinnedCert:(_Bool)arg2;
@property(readonly, nonatomic) NSFileManager *fileManager;
- (id)initWithSignalManagerSignalManager:(id)arg1;
- (id)newRegistrationToken;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
@property(readonly, nonatomic) WAPhoneNumber *phoneNumber;
@property(readonly, nonatomic) WAPhoneNumber *rawPhoneNumber;
@property(readonly, nonatomic) double registrationTokenCleanupInterval;
@property(readonly, nonatomic) double registrationTokenExpiryInterval;
@property(readonly, nonatomic) NSString *registrationTokenFilePath;
@property(readonly, nonatomic) double sendRecoveryTokenRetryTimeout;
- (id)urlBuilderForPhoneNumber:(id)arg1 tosVersion:(id)arg2;
@property(readonly, nonatomic) WAUserJID *userJID;
@property(readonly, nonatomic) NSString *v0RecoveryTokenFilePath;

@end

