//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WAMDOptInStateManager, WAPersistentKeyValueStore;
@protocol WADateProvider;

@interface WARemovedOwnDeviceStorageManager : NSObject
{
    WAPersistentKeyValueStore *_kvStore;
    id <WADateProvider> _dateProvider;
    WAMDOptInStateManager *_optInStateManager;
}

- (void).cxx_destruct;
- (void)addCompanionDevices:(id)arg1;
- (id)fetchAllCompanionDevicesForAccountUserJID:(id)arg1;
- (id)fetchCompanionDeviceForDeviceJID:(id)arg1;
- (id)initWithKeyValueStore:(id)arg1 dateProvider:(id)arg2 optInStateManager:(id)arg3;
- (_Bool)removeAllCompanionDevices;
- (void)removeCompanionDevices:(id)arg1;
- (_Bool)removeDevicesForSignOut;

@end

