//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, UIViewController, WARegistrationSession;
@protocol WARegistrationViewController;

@protocol WARegistrationTwoFacFailDelegate <NSObject>
- (void)registrationController:(UIViewController<WARegistrationViewController> *)arg1 didFailTwoFacWithSession:(WARegistrationSession *)arg2 response:(NSDictionary *)arg3;
@end

