//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSURL, WAPhoneNumber;

@interface WARegistrationURLBuilder : NSObject
{
    WAPhoneNumber *_phoneNumber;
    _Bool _encryptQueryParams;
    NSURL *_proxyURL;
    NSArray *_baseParams;
}

+ (id)codeRequestURL;
+ (id)encodedWAUUID:(id)arg1;
+ (id)registrationDomainProbeURL;
+ (id)registrationURL;
+ (id)sameDeviceCheckURL;
+ (id)twoFactorAuthenticationURL;
- (void).cxx_destruct;
- (void)disableProxying;
- (void)enableProxyingWithProxyURL:(id)arg1;
- (id)initWithPhoneNumber:(id)arg1 language:(id)arg2 locale:(id)arg3 fbUUID:(id)arg4 waUUID:(id)arg5 chatPrivateKey:(id)arg6 e2eKeyBundle:(id)arg7 smbClientSignedVNameCertData:(id)arg8 tosVersion:(id)arg9;
- (id)registrationRequestURLWithVerificationCode:(id)arg1 entryMethod:(int)arg2;
- (id)sameDeviceCheckRequestURLWithOfflineExposures:(id)arg1 offlineMetrics:(id)arg2;
- (id)twoFactorResetViaEmailRequestURL;
- (id)twoFactorResetWithWipeTokenRequestURL:(id)arg1;
- (id)twoFactorVerifyRequestURLWithCode:(id)arg1;
- (id)verificationCodeRequestURLWithMethod:(id)arg1 mcc:(id)arg2 mnc:(id)arg3 jailbroken:(_Bool)arg4;

@end

