//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "UITabBarControllerDelegate-Protocol.h"
#import "WAChatDatabaseMigrationViewControllerDelegate-Protocol.h"
#import "WAContactAlertViewControllerDelegate-Protocol.h"
#import "WAGroupInviteJoinControllerDelegate-Protocol.h"
#import "WANavigationDeepLinkHandler-Protocol.h"
#import "WAPaymentsInviteControllerDelegate-Protocol.h"
#import "WARepairDatabaseControllerDelegate-Protocol.h"
#import "WARestoreBackupViewControllerDelegate-Protocol.h"
#import "WASMBExploreBusinessToolsViewControllerDelegate-Protocol.h"
#import "WATOSViewControllerDelegate-Protocol.h"
#import "WAVerificationBaseControllerDelegate-Protocol.h"
#import "WAWindowController-Protocol.h"

@class NSArray, NSMutableArray, NSString, NSTimer, UILabel, UIView, UIViewController, WAAlertViewPresenter, WACallStorage, WAChatManager, WAChatStorage, WACloudBackupManager, WAContactsStorage, WAGroupInviteJoinController, WAPaymentsInviteController, WAReferenceCountToken, WASignalManager, WASplitViewController, WAStatusSessionManager, WATabBarController, WATaskManager, WATimelockViewController, WAWindow;
@protocol UISplitViewControllerDelegate><WASplitViewManaging, WARootViewControllerDelegate;

@interface WARootViewController : WAViewController <WARestoreBackupViewControllerDelegate, UITabBarControllerDelegate, WAVerificationBaseControllerDelegate, WAChatDatabaseMigrationViewControllerDelegate, WAGroupInviteJoinControllerDelegate, WAPaymentsInviteControllerDelegate, WARepairDatabaseControllerDelegate, WATOSViewControllerDelegate, WASMBExploreBusinessToolsViewControllerDelegate, WAWindowController, WAContactAlertViewControllerDelegate, WANavigationDeepLinkHandler>
{
    CDUnknownBlockType _deferredAction;
    NSArray *_defferedActionAllowedStates;
    _Bool _deferredActionWillOpenChat;
    _Bool _needsPerformHelperTasks;
    _Bool _hasPerformedHelperTasksAtLeastOnce;
    _Bool _hasPresentedHelperScreens;
    long long _reauthenticationTypeOnRegistrationScreen;
    _Bool _reauthenticationSkipLogOutAlert;
    _Bool _reauthenticationAutomaticallyPrefill;
    _Bool _shouldAttemptLoadDatabase;
    WASplitViewController *_splitViewController;
    id <UISplitViewControllerDelegate><WASplitViewManaging> _splitViewControllerDelegate;
    unsigned long long _nextState;
    _Bool _smbShowedVNameFlow;
    WAReferenceCountToken *_quietTimeToken;
    _Bool _smbShowBusinessToolsOnOnboardingCompletion;
    unsigned long long _smbExploreCompletionOption;
    WAGroupInviteJoinController *_groupInviteJoinController;
    WAPaymentsInviteController *_paymentsInviteController;
    UIView *_fakeStatusBarView;
    UILabel *_inCallStatusBarLabel;
    NSTimer *_inCallStatusBarUpdateTimer;
    _Bool _isPerformingStateTransition;
    NSMutableArray *_pendingStateChanges;
    WAAlertViewPresenter *_noLongerRegisteredAlert;
    _Bool _buildExpired;
    _Bool _callStatusBarHidden;
    WAWindow *_parentWindow;
    unsigned long long _currentState;
    WAChatManager *_chatManager;
    WACallStorage *_callStorage;
    WAChatStorage *_chatStorage;
    WAContactsStorage *_contactsStorage;
    WACloudBackupManager *_cloudBackupManager;
    WASignalManager *_signalManager;
    WAStatusSessionManager *_statusSessionManager;
    WATaskManager *_taskManager;
    id <WARootViewControllerDelegate> _delegate;
    WATabBarController *_tabBarController;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)accessibilityDarkerSystemColorsStatusDidChange:(id)arg1;
- (void)addReAuthButtonIfPossibleToAlertPresenter:(id)arg1 viewController:(id)arg2 forReauthenticationType:(long long)arg3;
- (void)adjustApplicationWindowForCallStatusBar;
- (void)adjustApplicationWindowForCallStatusBarAfterTransition;
- (void)callDidEnd:(id)arg1;
@property(readonly, nonatomic) WACallStorage *callStorage; // @synthesize callStorage=_callStorage;
@property(readonly, nonatomic) WAChatManager *chatManager; // @synthesize chatManager=_chatManager;
- (void)chatManagerDidChangeTimelockState:(id)arg1;
@property(readonly, nonatomic) WAChatStorage *chatStorage; // @synthesize chatStorage=_chatStorage;
- (id)childViewControllerForStatusBarStyle;
- (void)clearStateRestorationData;
@property(readonly, nonatomic) WACloudBackupManager *cloudBackupManager; // @synthesize cloudBackupManager=_cloudBackupManager;
- (void)contactAlertViewController:(id)arg1 didAddContactWithUserJID:(id)arg2 pushName:(id)arg3;
- (void)contactAlertViewController:(id)arg1 sendMessage:(id)arg2 JID:(id)arg3 pushName:(id)arg4;
- (void)contactAlertViewControllerDidAppear:(id)arg1;
- (void)contactAlertViewControllerDidCancel:(id)arg1;
- (void)contactAlertViewControllerRequestedViewDismissalWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)contactAlertViewControllerShouldAppearForExistingContact;
@property(readonly, nonatomic) WAContactsStorage *contactsStorage; // @synthesize contactsStorage=_contactsStorage;
- (void)criticallyLowStorageDidOccur:(id)arg1;
@property(readonly, nonatomic) unsigned long long currentState; // @synthesize currentState=_currentState;
@property(nonatomic) __weak id <WARootViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didBeginTransitionFromState:(unsigned long long)arg1;
- (void)didEndTransitionFromState:(unsigned long long)arg1;
- (void)didReceiveNotificationRequiringCallStatusBarUpdate:(id)arg1;
- (void)dismissGroupInviteUIWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissPaymentsInviteUIWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)doesStateAllowApplicationShortcuts:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long expectedCurrentState;
- (void)expireBuild;
- (void)exploreBusinessToolsViewController:(id)arg1 willCompleteWithOption:(unsigned long long)arg2;
- (void)groupInviteJoinControllerDidFinish:(id)arg1;
- (_Bool)groupInviteUIPresented;
- (void)handleDeepLinkAction:(unsigned long long)arg1;
- (_Bool)hasDeferredAction;
- (id)init;
@property(readonly, nonatomic, getter=isBuildExpired) _Bool buildExpired; // @synthesize buildExpired=_buildExpired;
@property(nonatomic, getter=isCallStatusBarHidden) _Bool callStatusBarHidden; // @synthesize callStatusBarHidden=_callStatusBarHidden;
- (_Bool)isCallStatusBarHiddenForWindow:(id)arg1;
- (_Bool)isStateSticky:(unsigned long long)arg1;
- (_Bool)isStateTerminal:(unsigned long long)arg1;
- (_Bool)isUserRegistered;
- (id)loadAndDiscardRestorableState;
- (void)loadDatabaseIfNeeded;
- (void)loadView;
- (void)migrationViewControllerDidFinish:(id)arg1;
- (void)navigateToPaymentsWithLink:(id)arg1;
- (unsigned long long)nextState;
@property(nonatomic) __weak WAWindow *parentWindow; // @synthesize parentWindow=_parentWindow;
- (void)paymentsInviteController:(id)arg1 didCancelValidatingLink:(id)arg2;
- (void)paymentsInviteController:(id)arg1 didFailToValidateInviteLink:(id)arg2 withError:(id)arg3;
- (void)paymentsInviteController:(id)arg1 didSuccessfullyValidateInviteLink:(id)arg2 shouldNaviagteToPayments:(_Bool)arg3;
- (void)performAfterFinishLaunchingWithCallStorage:(id)arg1 chatStorage:(id)arg2 contactsStorage:(id)arg3 chatManager:(id)arg4 cloudBackupManager:(id)arg5 signalManager:(id)arg6 statusSessionManager:(id)arg7 taskManager:(id)arg8 afterUpgrading:(_Bool)arg9;
- (void)performHelperTasksIfNeeded;
- (void)performInitialChecks;
- (void)prefillLastKnownNumberInViewController:(id)arg1;
- (_Bool)presentAppReviewPromptIfNecessary;
- (void)presentHelperScreen;
- (void)presentNoLongerRegisteredAlertWithReauthenticationType:(long long)arg1;
- (_Bool)presentRestoreHistoryAlert;
- (void)presentRestoreHistoryICloudAlert;
- (void)presentViewControllerModally:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)presentViewControllerModallyOnActive:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)processApplicationShortcutAction:(id)arg1;
- (void)processGroupInviteCode:(id)arg1 presentHandler:(CDUnknownBlockType)arg2;
- (void)processPaymentsInviteUrl:(id)arg1 presentHandler:(CDUnknownBlockType)arg2;
- (void)processPendingStateChanges;
- (void)reauthenticateWithReauthenticationType:(long long)arg1;
- (void)repairDatabaseViewControllerDidFail:(id)arg1;
- (void)repairDatabaseViewControllerDidFinish:(id)arg1;
- (void)reset;
- (void)resetSMBShowedVNameFlow;
- (void)restoreBackupViewControllerDidFinish:(id)arg1;
- (void)restoreBackupViewControllerDidRestore:(id)arg1;
- (void)runDeferredActionIfPossible;
- (void)saveRestorableState;
- (void)setColors;
- (void)setDeferredAction:(CDUnknownBlockType)arg1 runIfActive:(_Bool)arg2;
- (void)setDeferredAction:(CDUnknownBlockType)arg1 runIfActive:(_Bool)arg2 allowedStates:(id)arg3;
- (void)setNeedsOpenChatWithBlock:(CDUnknownBlockType)arg1;
- (void)setNeedsOpenHubWithDeepLinkUrl:(id)arg1;
- (void)setNeedsOpenPaymentAccountDetailsForAccountWithId:(id)arg1;
- (void)setNeedsOpenPaymentSettings;
- (void)setNeedsOpenPaymentTransactionDetails:(id)arg1;
- (void)setNeedsOpenSignUpWithDeepLinkUrl:(id)arg1;
- (void)setNeedsOpenValidateInviteLinkWithDeepLinkUrl:(id)arg1;
- (void)setNeedsPerformApplicationShortcutAction:(id)arg1;
- (void)setNeedsPerformHelperTasks;
- (void)setNeedsPreRegAlert;
- (void)setNeedsPrefillPhoneNumberAfterLogOut;
- (void)setNeedsPresentAccountReportsScreen;
- (void)setNeedsPresentNotificationSettings;
- (void)setNeedsPresentSoftbanWarningPrompt;
- (void)setNeedsPresentTosUpdatePromptWithEffectiveDateString:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setNeedsPresentWebClientSettings;
- (void)setNeedsShowCallHistoryTab;
- (void)setNeedsSkipLogOutAlert;
- (void)setNextState:(unsigned long long)arg1;
- (void)showTerminalErrorWithAlertMessage:(id)arg1;
- (void)showTerminalErrorWithCannotStartAlert;
- (void)showTerminalErrorWithChatHistoryReinstallAlert;
- (void)showTerminalErrorWithPhoneDateInaccurateAlert;
- (void)showTerminalErrorWithUnsupportedDeviceAlert;
- (void)showViewController:(id)arg1 usingTransition:(id)arg2 blockAfterPresent:(CDUnknownBlockType)arg3 blockAfterCompletion:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) WASignalManager *signalManager; // @synthesize signalManager=_signalManager;
- (void)smbVerifiedNameCertUpdateDidFail:(id)arg1;
- (void)startAnimatingCallStatusBar;
- (void)startRestoreAfterRepair;
- (void)statusBarTapped:(id)arg1;
@property(readonly, nonatomic) WAStatusSessionManager *statusSessionManager; // @synthesize statusSessionManager=_statusSessionManager;
@property(readonly, nonatomic) WATabBarController *tabBarController; // @synthesize tabBarController=_tabBarController;
@property(readonly, nonatomic) WATaskManager *taskManager; // @synthesize taskManager=_taskManager;
@property(readonly, nonatomic) WATimelockViewController *timelockViewController;
- (id)topMostVisibleViewController;
- (void)tosParametersDidChange:(id)arg1;
- (void)tosViewControllerDidAccept:(id)arg1;
- (void)tosViewControllerDidDismiss:(id)arg1;
- (id)transitionFromState:(unsigned long long)arg1 toState:(unsigned long long)arg2;
- (void)transitionToNextState;
- (void)transitionToNextStateViaUserInteraction;
- (void)transitionToState:(unsigned long long)arg1;
- (void)updateInCallStatusBarTimer:(id)arg1;
- (void)updateOfflineAssignABProperties;
- (void)updateStatusBarBackgroundViewSize;
- (void)verificationControllerDidCancel:(id)arg1;
- (void)verificationControllerDidCompleteRegistration:(id)arg1 migratedFromOtherApp:(_Bool)arg2;
- (void)verificationControllerDidDismissWelcomeScreen:(id)arg1;
- (void)verificationControllerDidSucceed:(id)arg1;
- (id)viewControllerForState:(unsigned long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
@property(readonly, nonatomic) UIViewController *visibleChildViewController;
- (void)wa_applicationDidBecomeActive;
- (void)wa_applicationDidEnterBackground;
- (void)wa_applicationWillEnterForeground;
- (void)willTransitionToState:(unsigned long long)arg1;
- (void)window:(id)arg1 didAddSubview:(id)arg2;
- (void)window:(id)arg1 willRemoveSubview:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

