//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WAChatJID, WAPersistentKeyValueStore;

@interface WARoomsManager : NSObject
{
    WAPersistentKeyValueStore *_keyValueStore;
    NSString *_redirectToken;
    WAChatJID *_redirectJID;
}

+ (_Bool)roomsEnabled;
- (void).cxx_destruct;
- (id)consumeJIDForRedirectToken:(id)arg1;
- (void)enterRoomsFlowFromViewController:(id)arg1 entryPoint:(unsigned long long)arg2;
- (void)enterRoomsFlowFromViewController:(id)arg1 entryPoint:(unsigned long long)arg2 chatJID:(id)arg3;
- (id)generateAndPersistRedirectTokenForJID:(id)arg1;
- (id)initWithKeyValueStore:(id)arg1;

@end

