//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImage, UIView;

@protocol WASavedContentBrowserChildNoItemsViewDataSource <NSObject>
@property(readonly, nonatomic) UIView *noItemsView;
- (NSString *)noItemsViewHeading;
- (UIImage *)noItemsViewImage;
- (NSString *)noItemsViewSubheading;
@end

