//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WATableViewController.h>

@class NSArray;
@protocol UIViewControllerPreviewingDelegate, WASavedContentSearchResultsTableViewControllerConfigurationDelegate;

@interface WASavedContentSearchResultsTableViewController : WATableViewController
{
    NSArray *_items;
    id <WASavedContentSearchResultsTableViewControllerConfigurationDelegate> _configurationDelegate;
    id <UIViewControllerPreviewingDelegate> _previewingDelegate;
}

- (void).cxx_destruct;
- (void)applicationDidChangeStatusBarOrientation:(id)arg1;
@property(nonatomic) __weak id <WASavedContentSearchResultsTableViewControllerConfigurationDelegate> configurationDelegate; // @synthesize configurationDelegate=_configurationDelegate;
- (id)init;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <UIViewControllerPreviewingDelegate> previewingDelegate; // @synthesize previewingDelegate=_previewingDelegate;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

