//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface WASafeModeHelper : NSObject
{
    MISSING_TYPE *userSessionPreferences;
    MISSING_TYPE *fileManager;
}

- (void).cxx_destruct;
- (void)clearFullDiskError;
- (id)init;
@property(nonatomic, readonly) _Bool shouldHandleLowStorage;

@end

