//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FMDatabase, NSArray, NSNumber, NSString, WASearchEngine, WAStorage;

@protocol WASearchEngineDelegate <NSObject>
- (void)searchEngine:(WASearchEngine *)arg1 didFailToIndexObject:(id)arg2 externalDocID:(NSNumber *)arg3;
- (void)searchEngine:(WASearchEngine *)arg1 didIndexObject:(id)arg2 externalDocID:(NSNumber *)arg3;
- (id)searchEngine:(WASearchEngine *)arg1 executeInsertTo:(FMDatabase *)arg2 object:(id)arg3 contents:(NSArray *)arg4;
- (_Bool)searchEngine:(WASearchEngine *)arg1 executeMetadataInsertTo:(FMDatabase *)arg2 internalDocID:(long long)arg3 userInfo:(id)arg4;
- (long long)searchEngine:(WASearchEngine *)arg1 externalDocIDForObject:(id)arg2;
- (long long)searchEngine:(WASearchEngine *)arg1 indexLevelForObject:(id)arg2;
- (void)searchEngine:(WASearchEngine *)arg1 indexableContentForObject:(id)arg2 completion:(void (^)(NSArray *))arg3;
- (_Bool)searchEngine:(WASearchEngine *)arg1 internalQueryForMaximumDocID:(id *)arg2 storage:(WAStorage *)arg3;
- (NSArray *)searchEngineColumnsForFullTextSearch:(WASearchEngine *)arg1;
- (void)searchEngineDidDeleteDatabase:(WASearchEngine *)arg1;
- (void)searchEngineDidPerformQuery:(WASearchEngine *)arg1;
- (_Bool)searchEngineExcludesMatchInfo:(WASearchEngine *)arg1;
- (NSArray *)searchEngineExtraMetadataColumns:(WASearchEngine *)arg1;
- (NSArray *)searchEngineMetadataFieldsToSelect:(WASearchEngine *)arg1;
- (NSArray *)searchEngineNewlyAddedMetadataColumns:(WASearchEngine *)arg1;
- (NSString *)searchEngineSearchResultOrderColumn:(WASearchEngine *)arg1;
- (void)searchEngineWillDeleteDatabase:(WASearchEngine *)arg1;
@end

