//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, NSString, NSURL, WASearchEngineObjectIndexer;
@protocol OS_dispatch_queue, WASearchEngineDelegate, WASearchEngineTokenizer;

@interface WASearchEngine : NSObject
{
    long long _lastRowID;
    id <WASearchEngineTokenizer> _tokenizer;
    _Bool _indexingEnabled;
    id <WASearchEngineDelegate> _delegate;
    NSURL *_directoryURL;
    NSString *_filename;
    FMDatabaseQueue *_dbQueue;
    NSObject<OS_dispatch_queue> *_privateQueue;
    WASearchEngineObjectIndexer *_objectIndexer;
}

- (void).cxx_destruct;
- (_Bool)addColumnNamed:(id)arg1 withType:(id)arg2 toMetadataTableInDatabase:(id)arg3;
- (_Bool)addMetadataColumnsIfNeededToDatabase:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (id)buildSQLQueryToCreateTable:(id)arg1 fullTextTokenizer:(id)arg2 columns:(id)arg3;
- (void)closeDatabase;
- (_Bool)createFullTextSearchTableInDatabase:(id)arg1;
- (_Bool)createMetadataTableInDatabase:(id)arg1;
- (id)databaseFilePath;
@property(readonly, nonatomic) FMDatabaseQueue *dbQueue; // @synthesize dbQueue=_dbQueue;
- (void)dealloc;
@property(nonatomic) __weak id <WASearchEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteDatabase;
@property(readonly, nonatomic) NSURL *directoryURL; // @synthesize directoryURL=_directoryURL;
- (id)docIDsMatchingSearchTerm:(id)arg1 restrictions:(id)arg2 offset:(unsigned long long)arg3 limit:(unsigned long long)arg4 invalidationBlock:(CDUnknownBlockType)arg5;
- (void)enableSecureDeleteInDatabase:(id)arg1;
- (void)enableWALModeInDatabase:(id)arg1;
- (id)fileURL;
@property(readonly, copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
- (id)groupedResultsMatchingSearchTerm:(id)arg1 column:(id)arg2 ordered:(_Bool)arg3 limit:(id)arg4 restrictions:(id)arg5 invalidationBlock:(CDUnknownBlockType)arg6;
- (id)indexContentForObjects:(id)arg1;
- (_Bool)indexObjects:(id)arg1 expectedDatabaseQueue:(id)arg2;
- (id)initWithDeletableDirectoryURL:(id)arg1 filename:(id)arg2;
- (void)internalCloseDatabase;
- (void)internalDeleteDatabase;
- (_Bool)internalIndexObjects:(id)arg1;
- (id)internalInsertTo:(id)arg1 object:(id)arg2 contents:(id)arg3;
- (void)internalOpenDatabaseWithStorage:(id)arg1;
- (void)loadObjectIndexer:(CDUnknownBlockType)arg1;
- (void)markSearchDatabaseAsCorrupted;
- (unsigned long long)numberOfIndexedObjects;
- (id)numberOfObjectsMatchingSearchTerm:(id)arg1 restrictions:(id)arg2 invalidationBlock:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) WASearchEngineObjectIndexer *objectIndexer; // @synthesize objectIndexer=_objectIndexer;
- (void)openDatabaseWithStorage:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *privateQueue; // @synthesize privateQueue=_privateQueue;
- (void)registerTokenizerForDB:(id)arg1;
- (void)removeDocIDs:(id)arg1;
- (void)setSearchScore:(float)arg1 forDocID:(id)arg2;
- (_Bool)shouldAddColumnNamed:(id)arg1 toMetadataTableInDatabase:(id)arg2;
- (unsigned long long)sizeOfDatabase;
- (void)waitForCompletion;

@end

