//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WASearchResultsNonvisualAttachmentView-Protocol.h"

@class NSString, UIImageView, WASearchResultsAudioPlayerView, WAUserJID;

@interface WASearchResultsAudioAttachmentView : UIView <WASearchResultsNonvisualAttachmentView>
{
    WAUserJID *_authorJID;
    UIImageView *_audioThumbnailView;
    UIImageView *_profilePictureView;
    UIImageView *_microphoneView;
    WASearchResultsAudioPlayerView *_playerView;
    NSString *_accessibilityLabel;
}

- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)configureWithMessage:(id)arg1 dataItem:(id)arg2 searchTokens:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)needsTwoPassLayout;
- (void)pauseAudioPlayer;
- (void)setHighlighted:(_Bool)arg1;
- (void)voiceOverStatusChanged:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

