//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WASearchResultsNonvisualAttachmentView-Protocol.h"

@class NSArray, NSString, UIImageView, WASearchResultsNonvisualAttachmentTextStackView;

@interface WASearchResultsContactAttachmentView : UIView <WASearchResultsNonvisualAttachmentView>
{
    WASearchResultsNonvisualAttachmentTextStackView *_textStackView;
    UIView *_contactImageStackView;
    UIImageView *_imageView;
    NSArray *_contacts;
}

- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)configureWithMessage:(id)arg1 dataItem:(id)arg2 searchTokens:(id)arg3;
- (id)contextString;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadProfilePictures;
- (_Bool)needsTwoPassLayout;
- (void)setHighlighted:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

