//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "WAIconTextCellSeparatorSupport-Protocol.h"

@class UIView, WASearchResultsIconTextView;

@interface WASearchResultsAuthorTableViewCell : UITableViewCell <WAIconTextCellSeparatorSupport>
{
    WASearchResultsIconTextView *_iconTextView;
    UIView *topSeparator;
    UIView *bottomSeparator;
}

- (void).cxx_destruct;
- (unsigned long long)accessibilityTraits;
@property(retain, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator;
- (void)configureWithTopSeparator:(_Bool)arg1 authorName:(id)arg2;
- (id)initWithReuseIdentifier:(id)arg1;
@property(retain, nonatomic) UIView *topSeparator; // @synthesize topSeparator;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

