//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WABloksContextImpl.h"

@protocol WAShopsPrivacyNoticeDelegate;

@interface WAShopsTOSContext : WABloksContextImpl
{
    id <WAShopsPrivacyNoticeDelegate> _privacyNoticeHandler;
}

- (void).cxx_destruct;
- (id)initWithAppID:(id)arg1 dataFetcher:(id)arg2 shouldUseMosaicPipeline:(_Bool)arg3 imageDownloaderProvider:(id)arg4 imageDownloader:(id)arg5 navigationHandler:(id)arg6 privacyHandler:(id)arg7;
@property(nonatomic) __weak id <WAShopsPrivacyNoticeDelegate> privacyNoticeHandler; // @synthesize privacyNoticeHandler=_privacyNoticeHandler;

@end

