//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAShopsURLHandler : NSObject
{
}

+ (id)getFlexLinkResult:(id)arg1 withURL:(id)arg2;
+ (_Bool)handlePDPURL:(id)arg1;
+ (_Bool)handleStorefrontURL:(id)arg1;
+ (_Bool)handleURL:(id)arg1;
+ (id)paramsForStorefrontURL:(id)arg1;

@end

