//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "CLLocationManagerDelegate-Protocol.h"
#import "MKMapViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchControllerDelegate-Protocol.h"
#import "UISearchResultsUpdating-Protocol.h"
#import "WACardNavigationControllerDelegate-Protocol.h"
#import "WALiveLocationMenuTableViewControllerDelegate-Protocol.h"
#import "WALiveLocationTableViewControllerDelegate-Protocol.h"
#import "WALocationSearchDelegate-Protocol.h"
#import "WAMapViewDelegate-Protocol.h"
#import "WAShareLocationTableViewDelegate-Protocol.h"

@class CLLocation, CLLocationManager, NSArray, NSDate, NSString, UIBarButtonItem, UIButton, UISearchController, UIView, WACardNavigationController, WAChatSession, WADialogViewController, WAFriendLocationAnnotation, WALiveLocationShareSettings, WALocationManagerAuthRequester, WALocationSearch, WAMapTypeSegmentedControl, WANavigationBarTitleView, WAShareLocationMapView, WAShareLocationTableViewController, WAShareLocationView, WATimer, WamEventLocationPicker;
@protocol WAShareLocationControllerDelegate><WALiveLocationSender;

@interface WAShareLocationController : WAViewController <CLLocationManagerDelegate, MKMapViewDelegate, UISearchBarDelegate, UISearchControllerDelegate, UISearchResultsUpdating, WACardNavigationControllerDelegate, WALiveLocationMenuTableViewControllerDelegate, WALiveLocationTableViewControllerDelegate, WALocationSearchDelegate, WAMapViewDelegate, WAShareLocationTableViewDelegate>
{
    WamEventLocationPicker *_fieldStats;
    double _elapsedTime;
    double _controllerLoadedTime;
    CLLocationManager *_locationManager;
    _Bool _goodLocationReceived;
    WATimer *_staleTimer;
    CLLocation *_lastUpdatedLocation;
    _Bool _isFallBack;
    _Bool _zoomToPlacesWhenMapExpands;
    WACardNavigationController *_cardNavigationController;
    WAShareLocationTableViewController *_tableViewController;
    WALiveLocationShareSettings *_liveLocationSettings;
    WALocationSearch *_locationSearch;
    _Bool _inPinDragMode;
    WAFriendLocationAnnotation *_meAnnotation;
    _Bool _wantsMeAnnotation;
    WAChatSession *_chatSession;
    UIView *_mentionsSelectorContainer;
    WAShareLocationView *_rootView;
    WADialogViewController *_newLiveLocationUserExperienceDialogViewController;
    WADialogViewController *_newCurrentLocationUserExperienceDialogViewController;
    _Bool _canSearch;
    _Bool _isSearchActive;
    _Bool _havePerformedInitialSearch;
    NSArray *_anyOrientationConstraints;
    NSArray *_portraitConstraints;
    NSArray *_landscapeConstraints;
    UISearchController *_searchController;
    WANavigationBarTitleView *_titleView;
    long long _entrypoint;
    _Bool _wasInPinDragModeBeforeEnteringLandscapeMode;
    _Bool _keyboardIsVisible;
    NSDate *_lastGeocodedDate;
    _Bool _showLiveLocationCardImmediately;
    _Bool _removeLiveLocationCell;
    id <WAShareLocationControllerDelegate><WALiveLocationSender> _delegate;
    unsigned long long _context;
    UIView *_viewMapContainer;
    WAShareLocationMapView *_mapView;
    UIView *_horizontalMapDivider;
    UIView *_verticalMapDivider;
    UIButton *_turnOnPreciseLocationButton;
    WAMapTypeSegmentedControl *_scMapType;
    UIBarButtonItem *_barButtonCancel;
    UIBarButtonItem *_barButtonRefresh;
    WALocationManagerAuthRequester *_locationAuthRequester;
    WALocationManagerAuthRequester *_liveLocationAuthRequester;
}

+ (id)newLocationUserExperienceViewControllerWithTitle:(id)arg1 bodyText:(id)arg2 image:(id)arg3 identifier:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (id)newNewCurrentLocationUserExperienceViewControllerWithCompletion:(CDUnknownBlockType)arg1;
+ (id)newNewLiveLocationUserExperienceViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)activateLandscapeConstraints:(_Bool)arg1;
- (void)activatePortraitConstraints:(_Bool)arg1;
- (void)addMeAnnotationIfPossible;
@property(retain, nonatomic) UIBarButtonItem *barButtonCancel; // @synthesize barButtonCancel=_barButtonCancel;
@property(retain, nonatomic) UIBarButtonItem *barButtonRefresh; // @synthesize barButtonRefresh=_barButtonRefresh;
- (_Bool)canShareLiveLocation;
- (void)cancelAction:(id)arg1;
- (void)cancelController;
- (void)cardNavigationController:(id)arg1 opaqueFrameDidChange:(struct CGRect)arg2;
- (void)cardNavigationControllerDidPopLastViewController:(id)arg1;
- (void)checkStateOfLocationServices;
- (void)collapseTableView:(id)arg1;
- (void)configureLocationSearch;
@property(readonly, nonatomic) unsigned long long context; // @synthesize context=_context;
- (id)customSearchController;
- (void)dealloc;
@property(readonly, nonatomic) __weak id <WAShareLocationControllerDelegate><WALiveLocationSender> delegate; // @synthesize delegate=_delegate;
- (void)didPresentSearchController:(id)arg1;
- (void)didReceiveBackgroundLocationAuthorization:(_Bool)arg1;
- (void)didTapTurnOnPreciseLocationButton:(id)arg1;
- (void)enterPinDragMode;
- (void)exitPinDragMode;
- (void)finishControllerWithWAPlace:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) UIView *horizontalMapDivider; // @synthesize horizontalMapDivider=_horizontalMapDivider;
- (id)initWithContext:(unsigned long long)arg1 delegate:(id)arg2 chatSession:(id)arg3 entrypoint:(long long)arg4;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)landscapeMode;
@property(retain, nonatomic) WALocationManagerAuthRequester *liveLocationAuthRequester; // @synthesize liveLocationAuthRequester=_liveLocationAuthRequester;
- (void)liveLocationDidCompleteWithSend:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)liveLocationMenuDidEnableTraffic:(_Bool)arg1;
- (void)liveLocationMenuMapTypeDidChange:(unsigned long long)arg1;
- (void)liveLocationMenuWillDismiss;
- (id)liveLocationTableViewControllerIfTopmost;
@property(retain, nonatomic) WALocationManagerAuthRequester *locationAuthRequester; // @synthesize locationAuthRequester=_locationAuthRequester;
- (void)locationSearchAggregateTimeAndCommitFieldStats;
- (void)locationSearchCommitFieldStats;
- (void)locationSearchDidCompleteWithAdditions:(id)arg1 removals:(id)arg2 previousCount:(unsigned long long)arg3 moreAvailable:(_Bool)arg4;
- (void)locationSearchDidSelectSearchHistoryEntry:(id)arg1;
- (id)locationSearchFieldStats;
- (CDStruct_d53ed6ef)locationSearchRegion;
- (void)locationSearchSetAttribution:(unsigned long long)arg1;
- (void)mapTypeChangedAction:(id)arg1;
@property(retain, nonatomic) WAShareLocationMapView *mapView; // @synthesize mapView=_mapView;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (void)mapView:(id)arg1 didDeselectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 didSelectLocation:(id)arg2;
- (void)mapView:(id)arg1 didSelectPlace:(id)arg2;
- (void)mapView:(id)arg1 didSelectPlacemark:(id)arg2 location:(id)arg3;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapViewDidCancelInfoPanel:(id)arg1;
- (void)mapViewDidChangeButtonsHeight:(id)arg1;
- (void)mapViewDidFinishCrossFadeAnimation;
- (void)mapViewDidLiftStaticPin:(id)arg1;
- (void)mapViewDidReverseGeocodeCurrentLocation:(id)arg1;
- (void)mapViewDidSelectInfoButton:(id)arg1;
- (void)mapViewWillReverseGeocodeCurrentLocation;
- (void)presentCannotShareAlert;
- (void)presentFailedToGetLocationAlert;
- (void)processLocationError:(id)arg1;
- (void)processUpdatedLocation:(id)arg1;
- (void)refreshAction:(id)arg1;
@property(nonatomic) _Bool removeLiveLocationCell; // @synthesize removeLiveLocationCell=_removeLiveLocationCell;
@property(retain, nonatomic) WAMapTypeSegmentedControl *scMapType; // @synthesize scMapType=_scMapType;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchUsingBestKnownLocation;
- (void)sendStaticLocation;
- (void)setAccuracyStr:(id)arg1;
- (void)setAppleAttribution;
- (void)setAttribution:(id)arg1;
- (void)setFoursquareAttribution;
@property(nonatomic) _Bool showLiveLocationCardImmediately; // @synthesize showLiveLocationCardImmediately=_showLiveLocationCardImmediately;
@property(retain, nonatomic) UIButton *turnOnPreciseLocationButton; // @synthesize turnOnPreciseLocationButton=_turnOnPreciseLocationButton;
@property(retain, nonatomic) UIView *verticalMapDivider; // @synthesize verticalMapDivider=_verticalMapDivider;
@property(retain, nonatomic) UIView *viewMapContainer; // @synthesize viewMapContainer=_viewMapContainer;
- (void)shareLocationDidEndDecelerating;
- (void)shareLocationDidEndDragging;
- (void)shareLocationDidSelectAccessoryForPlaceAtIndex:(long long)arg1;
- (void)shareLocationDidSelectAttribution:(id)arg1;
- (void)shareLocationDidSelectPlaceAtIndex:(long long)arg1;
- (void)shareLocationDidSelectSendCurrentLocation;
- (void)shareLocationDidSelectSendLiveLocation;
- (void)shareLocationLoadMoreResults;
- (id)shareLocationPlaces;
- (id)shareLocationSearchQuery;
- (_Bool)shareLocationShouldAutoExpand;
- (_Bool)shareLocationTableIsCollapsed;
- (void)shareLocationWillBeginDragging;
- (void)showDetailsForWAPlace:(id)arg1;
- (void)showLiveLocationCardAnimated:(_Bool)arg1;
- (void)showNewCurrentLocationUserExperienceIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)showNewLiveLocationUserExperienceIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)showingLiveLocationCard;
- (void)startLocationUpdatesIfNecessary;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateConstraintsForCurrentOrientation;
- (void)updateLayoutForCurrentOrientation;
- (void)updateNavigationShowingLiveLocationCard:(_Bool)arg1;
- (void)updatePinDragMode;
- (void)updatePreciseLocationButtonVisibility;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)updateStaticPinPosition;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (double)visibleRadius;
- (void)wa_applicationDidEnterBackground;
- (void)wa_applicationWillEnterForeground;
- (void)wa_fontSizeDidChange;
- (void)wa_tintColorDidChange;
- (void)willDismissSearchController:(id)arg1;
- (void)willPresentSearchController:(id)arg1;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (double)yOrigin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

