//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAMessageSliceLayoutManagerProvider-Protocol.h"

@class NSArray, NSLayoutManager, NSSet, NSString, NSTextContainer, NSTextStorage;

@interface WASimpleAttributedTextRenderer : NSObject <WAMessageSliceLayoutManagerProvider>
{
    NSTextContainer *_textContainer;
    NSLayoutManager *_layoutManager;
    NSTextStorage *_textStorage;
    struct CGRect _textRect;
    NSSet *_highlightedWords;
    NSArray *_highlightedRects;
    struct CGSize _textContainerSize;
    NSString *_rawText;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGSize containerSize;
- (void)drawInCurrentContextAtPoint:(struct CGPoint)arg1;
- (void)fillRects:(id)arg1 atPoint:(struct CGPoint)arg2;
- (id)initWithAttributedString:(id)arg1 containerSize:(struct CGSize)arg2 maxNumberOfLines:(unsigned long long)arg3;
- (void)performLayoutBlock:(CDUnknownBlockType)arg1;
- (void)setHighlightedWords:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) struct CGRect usedRect;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

