//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WASMBUpsellBannerTableViewCell;

@protocol WASMBUpsellBannerTableViewCellDelegate <NSObject>
- (void)smbUpsellBannerTableViewCellDidTapDismiss:(WASMBUpsellBannerTableViewCell *)arg1;
@end

