//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WAStarredMessageCellFooterView : UIView
{
    UIView *_separator;
    double _leftInset;
}

+ (double)preferredHeight;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) double leftInset; // @synthesize leftInset=_leftInset;

@end

