//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, UILabel, UIView;

@interface WAStickerSearchCategoryCell : UICollectionViewCell
{
    _Bool _currentCategory;
    UILabel *_label;
    UIView *_backgroundCircleView;
}

+ (id)labelFont;
- (void).cxx_destruct;
- (id)accessibilityHint;
- (unsigned long long)accessibilityTraits;
@property(retain, nonatomic) UIView *backgroundCircleView; // @synthesize backgroundCircleView=_backgroundCircleView;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isAccessibilityElement;
@property(nonatomic, getter=isCurrentCategory) _Bool currentCategory; // @synthesize currentCategory=_currentCategory;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(copy, nonatomic) NSString *labelText;
- (void)layoutSubviews;
- (void)setLabelTintColorIfNecessary;

@end

