//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel;
@protocol WAStatusListNUXCellDelegate;

@interface WAStatusListNUXCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_exitButton;
    UIButton *_privacyButton;
    id <WAStatusListNUXCellDelegate> _delegate;
}

+ (id)cellWithReuseIdentifier:(id)arg1;
- (void).cxx_destruct;
- (void)addAutolayoutConstraints;
@property(nonatomic) __weak id <WAStatusListNUXCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)exitButtonPressed;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)prepareForReuse;
- (void)privacyButtonPressed;
- (void)reloadFonts;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;

@end

