//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"
#import "WAStreamingMediaLoaderDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, WAChatStorage, WAMMSTaskSessionV4, WANetworkUsageManager, WANetworkUsageMetricsManager, WAStreamingMediaFileMapStore, WAStreamingMediaLoaderManagerQueue;
@protocol WAStreamingMediaLoaderManagerDownloadDelegate;

@interface WAStreamingMediaLoaderManager : NSObject <NSURLSessionDelegate, WAStreamingMediaLoaderDelegate>
{
    NSMutableDictionary *_loaders;
    _Atomic unsigned int _suspensionCounter;
    _Atomic unsigned int _suspendedReasons;
    WAStreamingMediaLoaderManagerQueue *_queue;
    NSMutableArray *_keysForSuspendedLoaders;
    WAMMSTaskSessionV4 *_mmsTaskSession;
    WAChatStorage *_chatStorage;
    WANetworkUsageManager *_networkUsageManager;
    WANetworkUsageMetricsManager *_networkUsageMetricsManager;
    NSMutableDictionary *_identifiersForObjectID;
    WAStreamingMediaFileMapStore *_fileMapStore;
    id <WAStreamingMediaLoaderManagerDownloadDelegate> _downloadDelegate;
    unsigned long long _maxConcurrentDownloads;
}

+ (id)mediaURLForMessage:(id)arg1;
- (void).cxx_destruct;
- (void)aggressiveAutoPrefetchStreamingMediaInMessage:(id)arg1;
- (void)aggressiveUserPrefetchStreamingMediaInMessage:(id)arg1;
- (void)autoDownloadStreamingMediaInMessage:(id)arg1;
- (void)beginSuspendingDownloadsForReason:(unsigned long long)arg1;
- (int)bytesToGoForMessage:(id)arg1;
- (long long)bytesToGoForMessages:(id)arg1;
- (void)cancelAllDownloads;
- (void)cancelAllMediaDownloadsForMessage:(id)arg1;
- (void)cancelMediaDownloadForMessage:(id)arg1 userInitiated:(_Bool)arg2;
- (void)cancelMediaDownloadForMessage:(id)arg1 userInitiated:(_Bool)arg2 onlyIfWaiting:(_Bool)arg3;
- (_Bool)cancelMediaDownloadForPlaintextHash:(id)arg1;
- (void)cancelMediaDownloadForPlaintextHash:(id)arg1 uniqueKey:(id)arg2 userInitiated:(_Bool)arg3 onlyIfWaiting:(_Bool)arg4 objectID:(id)arg5;
- (void)cancelMediaDownloadFromMessageDeletionNotification;
- (void)cleanUpForStreamingMediaLoader:(id)arg1;
- (id)createMessageInfoForMessage:(id)arg1 withMappedValuesForDeletion:(_Bool)arg2;
- (void)didCompleteForMessage:(id)arg1 withFileURL:(id)arg2 presentAlert:(_Bool)arg3;
- (void)didFailToLoadInStreamingMediaLoader:(id)arg1 error:(id)arg2;
- (void)didFetchThumbnailThatNeedsReloadingInStreamingMediaLoader:(id)arg1;
- (void)didFinishLoadingInStreamingMediaLoader:(id)arg1;
- (void)didUpdateDownloadProgressOfStreamingMediaLoader:(id)arg1 bytesDownloaded:(unsigned long long)arg2;
@property(nonatomic) __weak id <WAStreamingMediaLoaderManagerDownloadDelegate> downloadDelegate; // @synthesize downloadDelegate=_downloadDelegate;
- (void)endSuspendingDownloadsForReason:(unsigned long long)arg1;
- (void)enqueueRunningAutoDownload;
- (id)existingLoaderForMessageKey:(id)arg1;
- (_Bool)fetchForLoaderMessageInfo:(id)arg1 fileURL:(out id *)arg2 fileMap:(out id *)arg3;
@property(readonly, nonatomic) WAStreamingMediaFileMapStore *fileMapStore; // @synthesize fileMapStore=_fileMapStore;
- (void)handleDownloadForMessageInfo:(id)arg1 withMode:(unsigned long long)arg2;
- (id)initWithMMSTaskSession:(id)arg1 chatStorage:(id)arg2 localKeyValueStore:(id)arg3 networkUsageManager:(id)arg4 networkUsageMetricsManager:(id)arg5;
- (_Bool)isDownloadingMediaInMessage:(id)arg1;
@property(readonly, nonatomic) unsigned long long maxConcurrentDownloads; // @synthesize maxConcurrentDownloads=_maxConcurrentDownloads;
- (void)mergeContentExtensionDownloadAfterCompletionForMessageInfo:(id)arg1 withTemporaryMediaPath:(id)arg2 fileInfo:(id)arg3;
- (void)mergeContentExtensionDownloadForMessage:(id)arg1 withTemporaryMediaPath:(id)arg2 fileInfo:(id)arg3;
- (void)mergeFilesForMessageInfo:(id)arg1 notificationExtensionMediaURL:(id)arg2 fileInfo:(id)arg3;
- (id)newOrExistingLoaderForMessageInfo:(id)arg1 reason:(id)arg2;
- (id)objectIDsToRemoveFromMessages:(id)arg1;
- (id)playbackAssetForMessage:(id)arg1;
- (id)playbackAssetForMessageFNF:(id)arg1;
- (void)prefetchStreamingMediaInMessage:(id)arg1;
- (void)preparePlaybackLoaderForMessage:(id)arg1;
- (id)progressForLoaderMessageInfo:(id)arg1;
- (float)progressOfMediaDownloadForMessage:(id)arg1;
- (void)removeLoaderForKey:(id)arg1;
- (void)resumeQueuedDownloads;
- (unsigned long long)runningLoaderCount;
- (_Bool)shouldPresentAlertViewForStreamingMediaLoader:(id)arg1;
- (_Bool)shouldSuspendExistingLoader:(id)arg1;
- (_Bool)shouldSuspendNewLoaderForMode:(unsigned long long)arg1;
- (void)startDownloadForMessageInfo:(id)arg1 withMode:(unsigned long long)arg2 queuedDate:(id)arg3;
- (_Bool)startNextQueuedDownload;
- (void)streamingMediaLoader:(id)arg1 populatedDownloadEvents:(id)arg2;
- (void)streamingMediaLoaderDidBeginPlayback:(id)arg1;
- (void)streamingMediaLoaderDidRequestAdd:(id)arg1;
- (void)streamingMediaLoaderDidRequestRemove:(id)arg1;
- (_Bool)streamingMediaLoaderDidRequestSave:(id)arg1 forFileMap:(id)arg2;
- (void)streamingMediaLoaderDidVerifyFileSize:(id)arg1 fileSize:(unsigned long long)arg2;
@property(readonly) _Bool suspended;
@property(readonly) unsigned long long suspendedReasons;
- (id)thumbnailForMessageInfo:(id)arg1;
- (void)updateDownloadProgressForMessage:(id)arg1;
- (void)userDownloadStreamingMediaInMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

