//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAMessageBubbleTableViewCell.h"

@class UIImageView, WAStarredMessageCellFooterView, WAStarredMessageCellHeaderView;

@interface WAStarredMessageTableViewCell : WAMessageBubbleTableViewCell
{
    WAStarredMessageCellFooterView *_footerView;
    WAStarredMessageCellHeaderView *_headerView;
    UIImageView *_rightAccessoryView;
    double _rightAccessoryViewMargin;
}

+ (double)preferredFooterHeightForCellData:(id)arg1;
+ (double)preferredHeaderHeightForCellData:(id)arg1;
- (void).cxx_destruct;
- (void)hideFooter;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setCellData:(id)arg1 viewControllerSize:(struct CGSize)arg2 showFooter:(_Bool)arg3;
- (void)setEditing:(_Bool)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setFooterForCellData:(id)arg1;
- (void)setHeaderForCellData:(id)arg1;
- (void)setRightAccessoryView;

@end

