//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, WAStandardDecayRankingMetric;

@interface WAStatusRankingCachedState : NSObject
{
    WAStandardDecayRankingMetric *_incomingMessageNormalizationMetric;
    WAStandardDecayRankingMetric *_incomingMediaNormalizationMetric;
    WAStandardDecayRankingMetric *_incomingCallNormalizationMetric;
    WAStandardDecayRankingMetric *_outgoingMessageNormalizationMetric;
    WAStandardDecayRankingMetric *_outgoingMediaNormalizationMetric;
    WAStandardDecayRankingMetric *_outgoingCallNormalizationMetric;
    WAStandardDecayRankingMetric *_incomingGroupMessageNormalizationMetric;
    WAStandardDecayRankingMetric *_incomingGroupMediaNormalizationMetric;
    WAStandardDecayRankingMetric *_outgoingGroupMessageNormalizationMetric;
    WAStandardDecayRankingMetric *_outgoingGroupMediaNormalizationMetric;
    NSMutableDictionary *_cachedGroupSignals;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *cachedGroupSignals; // @synthesize cachedGroupSignals=_cachedGroupSignals;
@property(retain, nonatomic) WAStandardDecayRankingMetric *incomingCallNormalizationMetric; // @synthesize incomingCallNormalizationMetric=_incomingCallNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *incomingGroupMediaNormalizationMetric; // @synthesize incomingGroupMediaNormalizationMetric=_incomingGroupMediaNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *incomingGroupMessageNormalizationMetric; // @synthesize incomingGroupMessageNormalizationMetric=_incomingGroupMessageNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *incomingMediaNormalizationMetric; // @synthesize incomingMediaNormalizationMetric=_incomingMediaNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *incomingMessageNormalizationMetric; // @synthesize incomingMessageNormalizationMetric=_incomingMessageNormalizationMetric;
- (id)initWithAggregateMetricSet:(id)arg1;
@property(retain, nonatomic) WAStandardDecayRankingMetric *outgoingCallNormalizationMetric; // @synthesize outgoingCallNormalizationMetric=_outgoingCallNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *outgoingGroupMediaNormalizationMetric; // @synthesize outgoingGroupMediaNormalizationMetric=_outgoingGroupMediaNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *outgoingGroupMessageNormalizationMetric; // @synthesize outgoingGroupMessageNormalizationMetric=_outgoingGroupMessageNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *outgoingMediaNormalizationMetric; // @synthesize outgoingMediaNormalizationMetric=_outgoingMediaNormalizationMetric;
@property(retain, nonatomic) WAStandardDecayRankingMetric *outgoingMessageNormalizationMetric; // @synthesize outgoingMessageNormalizationMetric=_outgoingMessageNormalizationMetric;

@end

