//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UIImage, UIImageView, WAVolumeArcView;
@protocol WAStatusVolumeViewDelegate;

@interface WAStatusVolumeView : UIView
{
    NSTimer *_timer;
    WAVolumeArcView *_arcView;
    UIView *_containerView;
    UIView *_innerContainerView;
    long long _showCount;
    UIImageView *_speakerIconView;
    UIImageView *_waveImageView1;
    UIImageView *_waveImageView2;
    UIImageView *_waveImageView3;
    UIImage *_muteImage;
    UIImage *_unmutedImage;
    UIImage *_noAudioImage;
    _Bool _showsNoAudioIndicator;
    id <WAStatusVolumeViewDelegate> _delegate;
    long long _state;
}

- (void).cxx_destruct;
- (void)beginShowingVolumeView;
- (void)cancelTimer;
- (void)changeVolumeByAmount:(float)arg1 snapToGrid:(_Bool)arg2;
@property(readonly, nonatomic) float currentVolume;
@property(nonatomic) __weak id <WAStatusVolumeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endShowingVolumeView;
- (void)handleTimerFired:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isVisible) _Bool visible;
- (void)onVolumeDownButtonDown:(id)arg1;
- (void)onVolumeDownButtonUp:(id)arg1;
- (void)onVolumeUpButtonDown:(id)arg1;
- (void)onVolumeUpButtonUp:(id)arg1;
- (void)scheduleTimer;
- (void)scheduleTimerAfterDelay;
@property(nonatomic) _Bool showsNoAudioIndicator; // @synthesize showsNoAudioIndicator=_showsNoAudioIndicator;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)setVisible:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateProgressView;
- (void)updateSpeakerIconAndWaves;
- (void)volumeDidChange:(id)arg1;

@end

