//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAStatusListNUXCell;

@protocol WAStatusListNUXCellDelegate <NSObject>
- (void)statusListNUXCellDidRequestDismiss:(WAStatusListNUXCell *)arg1;
- (void)statusListNUXCellDidRequestPresentPrivacyScreen:(WAStatusListNUXCell *)arg1;
@end

