//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSIndexPath, WAStickerCategoriesFlowLayout;

@protocol WAStickerCategoriesFlowLayoutDelegate
- (_Bool)stickerCategoriesFlowLayout:(WAStickerCategoriesFlowLayout *)arg1 shouldStartEmotionContractionWithIndexPath:(NSIndexPath *)arg2;
- (_Bool)stickerCategoriesFlowLayout:(WAStickerCategoriesFlowLayout *)arg1 shouldStartEmotionExpansionWithIndexPath:(NSIndexPath *)arg2;
- (_Bool)stickerCategoriesFlowLayoutEmotionCategoryAvailable:(WAStickerCategoriesFlowLayout *)arg1;
- (struct CGRect)stickerCategoriesFlowLayoutExpandedDecorationFrame:(WAStickerCategoriesFlowLayout *)arg1;
- (void)stickerCategoriesFlowLayoutFinalizedUpdates:(WAStickerCategoriesFlowLayout *)arg1;
- (struct CGRect)stickerCategoriesFlowLayoutNonExpandedDecorationFrame:(WAStickerCategoriesFlowLayout *)arg1;
- (_Bool)stickerCategoriesFlowLayoutShouldShowDecoration:(WAStickerCategoriesFlowLayout *)arg1;
- (struct CGPoint)stickerCategoriesFlowLayoutTriggeringCenter:(WAStickerCategoriesFlowLayout *)arg1;
- (NSIndexPath *)stickerCategoriesFlowLayoutTriggeringIndexPath:(WAStickerCategoriesFlowLayout *)arg1;
@end

