//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface WAStatusScrollView : UIScrollView
{
    double _initialZoomScale;
}

@property(nonatomic) double initialZoomScale; // @synthesize initialZoomScale=_initialZoomScale;
- (void)setContentOffset:(struct CGPoint)arg1;

@end

