//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel, WAStatusLinkPreviewContent;

@interface WAStatusLinkPreviewDisplayView : UIView
{
    UIImageView *_imageView;
    UILabel *_contentLabel;
    UILabel *_webURLLabel;
    double _preferredImageHeight;
    UIView *_containerView;
    WAStatusLinkPreviewContent *_content;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WAStatusLinkPreviewContent *content; // @synthesize content=_content;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)reloadFont;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

