//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WACircularImageButton.h>

@interface WAStickyCircularImageButton : WACircularImageButton
{
}

- (void)setHighlighted:(_Bool)arg1;

@end

