//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAStatusInformativeItemView.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSLayoutManager, NSString, NSTextContainer, NSTextStorage, UITapGestureRecognizer;

@interface WAStatusLearnMoreItemView : WAStatusInformativeItemView <UIGestureRecognizerDelegate>
{
    struct CGSize _lastViewSize;
    UITapGestureRecognizer *_gestureRecognizer;
    NSTextStorage *_textStorage;
    NSTextContainer *_textContainer;
    NSLayoutManager *_layoutManager;
    struct _NSRange _readMoreRange;
}

- (void).cxx_destruct;
- (id)attributedText;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleTapOnLabel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)labelText;
- (void)layoutSubviews;
- (id)learnMoreURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

