//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSFetchedResultsControllerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "WAGimmickPickerViewConfiguring-Protocol.h"
#import "WAStickerCategoriesFlowLayoutDelegate-Protocol.h"
#import "WAStickerEventCategoryManagerDelegate-Protocol.h"

@class NSArray, NSIndexPath, NSMutableDictionary, NSString, UICollectionView, UIColor, UINotificationFeedbackGenerator, WAFetchedResultsController, WAStickerSearchRankingController;
@protocol WAStickerPickerManagerDelegate><UIScrollViewDelegate;

@interface WAStickerPickerManager : NSObject <NSFetchedResultsControllerDelegate, WAStickerEventCategoryManagerDelegate, WAGimmickPickerViewConfiguring, UICollectionViewDelegate, UICollectionViewDataSource, WAStickerCategoriesFlowLayoutDelegate>
{
    NSMutableDictionary *_categoryManagerMap;
    WAFetchedResultsController *_categoryFetchedResultsController;
    NSMutableDictionary *_contentCollectionViewMap;
    UICollectionView *_categoryCollectionView;
    NSIndexPath *_currentCategory;
    NSMutableDictionary *_backgroundViewMap;
    _Bool _canChangeLayout;
    _Bool _emotionCategoriesExpanded;
    unsigned long long _emotionCategoriesChangedCount;
    _Bool _loadingMoreStickers;
    NSArray *_downloadingStickerPacks;
    _Bool _changeShouldResetCurrentCategory;
    NSString *_unpresentedStickerPackId;
    long long _stickerCollectionViewType;
    UINotificationFeedbackGenerator *_confirmationHapticGenerator;
    double _stickerLastSelectTime;
    unsigned long long _stickerSendStatus;
    _Bool _includeSuggestions;
    _Bool _skipShowingSuggestions;
    id <WAStickerPickerManagerDelegate><UIScrollViewDelegate> _delegate;
    WAStickerSearchRankingController *_stickerRankingController;
    NSArray *_emojisForStickerSuggestions;
}

+ (id)imageForStickerCategoryEmotionPicker:(long long)arg1;
+ (id)imageForStickerCategoryFixedItemPicker:(long long)arg1;
+ (id)pagingCollectionViewCellReuseIdentifier;
+ (unsigned long long)stickerEmotionForStickerCategoryEmotionItemPicker:(long long)arg1;
+ (unsigned long long)stickerEmotionForStickerCategoryEmotionItemSearch:(long long)arg1;
+ (id)textForStickerCategoryEmotionSearch:(long long)arg1;
+ (id)textForStickerCategoryFixedItemSearch:(long long)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIColor *GIFButtonTintColor;
@property(readonly, nonatomic) NSString *accessibilityLabelForLeftButton;
@property(readonly, nonatomic) NSString *accessibilityLabelForRightButton;
- (id)allCategoryManager;
@property(readonly, nonatomic) _Bool canChangeLayout;
- (void)cancelStickerPackDownloadAction:(id)arg1;
- (id)categoryCollectionViewCellForItemAtIndexPath:(id)arg1;
- (void)categoryCollectionViewDidSelectItemAtIndexPath:(id)arg1;
- (long long)categoryCollectionViewNumberOfItemsInSection:(long long)arg1;
- (id)categoryFRCIndexPathForStickerPackIndex:(long long)arg1;
- (id)categoryFetchedResultsController;
- (long long)categoryFixedItemPickerAtIndex:(long long)arg1;
- (id)categoryForCollectionView:(id)arg1;
- (_Bool)categoryIsEmotion:(id)arg1;
- (id)categoryManagerBasedOnEmojis:(id)arg1 ranked:(_Bool)arg2;
- (id)categoryManagerForCategory:(id)arg1;
- (id)categoryManagerForEmotion:(unsigned long long)arg1;
- (id)categoryManagerForFixedItemPicker:(long long)arg1;
- (id)categoryManagerForFixedItemSearch:(long long)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionViewLayoutForCategoryCollectionView;
@property(readonly, nonatomic) NSString *configurationIdentifier;
- (void)configureContentCollectionView:(id)arg1;
- (id)contentBackgroundViewForCategory:(id)arg1;
- (id)contentCollectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)contentCollectionView:(id)arg1 didLongPressAtIndexPath:(id)arg2;
- (void)contentCollectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)contentCollectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)contentCollectionViewBackgroundViewForCategory:(id)arg1;
- (void)contentCollectionViewDidEndDisplaying:(id)arg1;
- (void)contractEmotionCategories;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
@property(readonly, nonatomic) NSIndexPath *currentCategory;
- (id)currentStickerPack;
- (void)dealloc;
- (id)defaultCategory;
@property(nonatomic) __weak id <WAStickerPickerManagerDelegate><UIScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didSelectSticker:(id)arg1 inCell:(id)arg2 fromCategory:(id)arg3;
- (void)downloadProgress:(id)arg1;
- (id)downloadProgressView;
- (void)downloadStateDidUpdate:(id)arg1;
@property(copy, nonatomic, setter=setEmojisForStickerSuggestions:) NSArray *emojisForStickerSuggestions; // @synthesize emojisForStickerSuggestions=_emojisForStickerSuggestions;
- (_Bool)emotionCategoriesEnabled;
- (void)expandEmotionCategories;
- (void)hideSuggestionsTab;
- (long long)indexForCategoryFixedItemPicker:(long long)arg1;
- (id)initWithCategoryCollectionView:(id)arg1 contentCollectionViewMap:(id)arg2 stickerCollectionViewType:(long long)arg3;
- (double)interRowSpacingForCollectionView:(id)arg1 itemSize:(double)arg2 itemSpacing:(double)arg3 topMargin:(double)arg4;
- (struct CGSize)labelSizeForIndexPath:(id)arg1;
- (id)loadingView;
- (void)markCategoryAsSeenByUserForIndexPath:(id)arg1;
@property(readonly, nonatomic) long long numberOfCategorySections;
- (long long)numberOfItemsInEmotionsSection;
- (long long)numberOfItemsInFixedSection;
- (long long)numberOfItemsInPagingCollectionViewSection:(long long)arg1;
- (long long)numberOfSectionsInCategoryCollectionView;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)numberOfSectionsInContentCollectionView:(id)arg1;
@property(readonly, nonatomic) long long numberOfSectionsInPagingCollectionView;
- (void)openStickerStoreFromPlaceholderView:(id)arg1;
- (id)placeholderLabel;
- (id)placeholderViewForStickerCategoryFixedItemPicker:(long long)arg1;
- (id)placeholderViewWithImage:(id)arg1 text:(id)arg2;
- (id)recentCategoryManager;
- (void)reloadCategorySectionFixedContentCollectionViews;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setCurrentCategory:(id)arg1;
- (void)setCurrentCategoryAndUpdateFetchedResultsControllers:(id)arg1;
- (void)setStickerCategoryForStickerPack:(id)arg1;
@property(retain, nonatomic) WAStickerSearchRankingController *stickerRankingController; // @synthesize stickerRankingController=_stickerRankingController;
@property(readonly, nonatomic) _Bool shouldShowLeftButton;
@property(readonly, nonatomic) _Bool shouldShowRightButton;
@property(readonly, nonatomic) _Bool shouldShowRightButtonUpdateIndicator;
- (void)showCategoryAtIndexPath:(id)arg1;
- (void)showFirstStickerPack;
- (void)showStarredCategoryOnViewDidAppear:(_Bool)arg1;
- (void)showSuggestionsTab;
- (id)starredCategoryManager;
@property(readonly, nonatomic) UIColor *stickerButtonTintColor;
- (_Bool)stickerCategoriesFlowLayout:(id)arg1 shouldStartEmotionContractionWithIndexPath:(id)arg2;
- (_Bool)stickerCategoriesFlowLayout:(id)arg1 shouldStartEmotionExpansionWithIndexPath:(id)arg2;
- (_Bool)stickerCategoriesFlowLayoutEmotionCategoryAvailable:(id)arg1;
- (struct CGRect)stickerCategoriesFlowLayoutExpandedDecorationFrame:(id)arg1;
- (void)stickerCategoriesFlowLayoutFinalizedUpdates:(id)arg1;
- (struct CGRect)stickerCategoriesFlowLayoutNonExpandedDecorationFrame:(id)arg1;
- (_Bool)stickerCategoriesFlowLayoutShouldShowDecoration:(id)arg1;
- (struct CGPoint)stickerCategoriesFlowLayoutTriggeringCenter:(id)arg1;
- (id)stickerCategoriesFlowLayoutTriggeringIndexPath:(id)arg1;
- (void)stickerEventCategoryManagerUpdatedStickers:(id)arg1;
- (id)stickerPackCategoryManagerForIndex:(long long)arg1;
- (void)submitStickerSendFromContextualSuggestionsFieldStatsEventForCategory:(id)arg1 indexPath:(id)arg2;
- (void)updateCell:(id)arg1 atIndexPath:(id)arg2 inContentCollectionView:(id)arg3 withImage:(id)arg4 forSticker:(id)arg5;
- (void)updateDownloadingStickerPacks:(id)arg1;
- (_Bool)userScrolledToCategory:(id)arg1;
- (void)viewDidAppear;
- (void)viewWillDisappear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

