//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAStoreKit : NSObject
{
}

+ (void)logEvent:(long long)arg1;

@end

