//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface WAStoredMediaGallerySection : NSObject
{
    NSMutableArray *_mutableMessages;
    NSString *_name;
}

- (void).cxx_destruct;
- (id)initWithName:(id)arg1 messages:(id)arg2;
@property(copy, nonatomic) NSArray *messages;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)removeIndex:(long long)arg1;

@end

