//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSString, WAChatJID;
@protocol WAServerDate;

@protocol WAStopLocationSharingRequest <NSObject>
@property(readonly, nonatomic) WAChatJID *chatJID;
@property(readonly, copy, nonatomic) NSString *requestID;
@property(readonly, copy, nonatomic) NSDate<WAServerDate> *retryEndDate;
@end

