//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WAFetchedResultsController;

@interface WAStatusListSectionInfo : NSObject
{
    NSString *_title;
    WAFetchedResultsController *_statusResultsController;
}

- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1;
@property(retain, nonatomic) WAFetchedResultsController *statusResultsController; // @synthesize statusResultsController=_statusResultsController;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

@end

