//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@interface WAStickerSearchPageCollectionView : UICollectionView
{
}

- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;

@end

