//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WAHTTPFetcher;

@interface WASupportFAQSearchHelper : NSObject
{
    WAHTTPFetcher *_searchFetcher;
}

- (void).cxx_destruct;
- (void)cancelPendingSearch;
@property(readonly, nonatomic) _Bool isSearching;
- (void)searchFAQ:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

