//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAPercentDrivenInteractiveTransition.h>

@interface WASwipeFromMessageInfoToChatInteractiveTransition : WAPercentDrivenInteractiveTransition
{
}

- (void)cancelInteractiveTransition;

@end

