//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WASyncedContactListProviding-Protocol.h"

@class NSSet, NSString, WASyncedContactList;

@protocol WASyncedContactListProvidingMainApp <WASyncedContactListProviding>
- (void)fetchJIDsForSyncedContactList:(WASyncedContactList *)arg1 completion:(void (^)(NSError *, NSArray *, _Bool))arg2;
- (void)permanentlySaveJIDs:(NSSet *)arg1 forSyncedContactList:(WASyncedContactList *)arg2;
- (void)syncedContactList:(WASyncedContactList *)arg1 didRequestSendContacts:(NSSet *)arg2 pendingContacts:(NSSet *)arg3 webClientRequestID:(NSString *)arg4 completion:(void (^)(NSError *, _Bool))arg5;
- (void)syncedContactListDidUpdate:(WASyncedContactList *)arg1;
@end

