//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface WASyncStateHolder : NSObject
{
    NSMutableDictionary *_contextDevicesQueries;
    CDUnknownBlockType _delayUsyncForOfflinePopServerProperty;
    _Bool _isMessageContextRequestInFlight;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool delayUsyncForOfflinePopServerProperty;
- (_Bool)hasDevicesQuerySyncCompletionsWithContext:(unsigned long long)arg1;
- (_Bool)hasDevicesQuerySyncUserJIDsWithContext:(unsigned long long)arg1;
- (id)init;
- (id)initWithDelayUsyncForOfflinePopServerProperty:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool isMessageContextRequestInFlight; // @synthesize isMessageContextRequestInFlight=_isMessageContextRequestInFlight;
- (void)removeDevicesQueryCompletionsWhileFailingEachWithContext:(unsigned long long)arg1;
- (id)removeDevicesQueryWithContext:(unsigned long long)arg1;
- (void)updateDevicesQueryWithContext:(unsigned long long)arg1 userJIDs:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

