//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol WATableViewSupplementaryViewDelegate;

@protocol WATableViewSupplementaryViewContainer
@property(nonatomic) __weak id <WATableViewSupplementaryViewDelegate> delegate;
@property(nonatomic) _Bool eligibleToExpand;
@property(nonatomic, getter=isExpanded) _Bool expanded;
- (void)reloadSupplementaryActions:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setNeedsUpdateDetailLabels;
@property(readonly, nonatomic) double supplementaryContentHeight;
@end

