//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITabBar.h>

@protocol WATabBarDelegate;

@interface WATabBar : UITabBar
{
}

- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

// Remaining properties
@property(nonatomic) __weak id <WATabBarDelegate> delegate; // @dynamic delegate;

@end

