//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString, WATableViewSupplementaryAction;

@protocol WATableViewSupplementaryViewDelegate
- (NSString *)detailStringForAction:(WATableViewSupplementaryAction *)arg1;
- (_Bool)shouldUseArchiveUI;
- (struct WASupplementaryActionLayout)supplementaryActionLayout;
- (NSArray *)supplementaryActions;
@end

