//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WATarFile;

@interface WATarSearch : NSObject
{
    unsigned long long _cachedFileSize;
    WATarFile *_file;
    CDUnknownBlockType _validator;
    CDUnknownBlockType _contentMetadataProvider;
    CDUnknownBlockType _validFileIndexForFileIndex;
}

- (void).cxx_destruct;
- (id)checkFileAtOffset:(unsigned long long)arg1;
@property(copy, nonatomic) CDUnknownBlockType contentMetadataProvider; // @synthesize contentMetadataProvider=_contentMetadataProvider;
@property(nonatomic) __weak WATarFile *file; // @synthesize file=_file;
- (id)initWithFile:(id)arg1;
- (unsigned long long)seekToFindIndexWithCancellationBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType validFileIndexForFileIndex; // @synthesize validFileIndexForFileIndex=_validFileIndexForFileIndex;
@property(copy, nonatomic) CDUnknownBlockType validator; // @synthesize validator=_validator;

@end

