//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UISearchBar.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WATableViewSupplementaryViewContainer-Protocol.h"

@class NSString, UIColor, UIView, WATableViewSupplementaryTableView;
@protocol WATableViewSupplementaryViewDelegate;

@interface WATableViewSupplementarySearchBarView : UISearchBar <UIGestureRecognizerDelegate, WATableViewSupplementaryViewContainer>
{
    WATableViewSupplementaryTableView *_tableView;
    UIColor *_expandedBackgroundColor;
    UIColor *_contractedBackgroundColor;
    UIView *_backgroundView;
    _Bool _needsUpdateDetailLabels;
    _Bool _expanded;
    _Bool _eligibleToExpand;
}

- (void).cxx_destruct;
- (void)didMoveToWindow;
@property(nonatomic) _Bool eligibleToExpand; // @synthesize eligibleToExpand=_eligibleToExpand;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)init;
@property(nonatomic, getter=isExpanded) _Bool expanded; // @synthesize expanded=_expanded;
- (void)layoutSubviews;
- (void)preiOS11LayoutSubviewsHacks;
- (void)reloadSupplementaryActions:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setNeedsUpdateDetailLabels;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) double supplementaryContentHeight;
- (void)updateDetailLabelsIfNeeded;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <WATableViewSupplementaryViewDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

