//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSLayoutConstraint, UILabel;

@interface WATextInputFooterView : UIView
{
    NSLayoutConstraint *_leftMargin;
    NSLayoutConstraint *_rightMargin;
    NSArray *_topMargins;
    NSArray *_bottomMargins;
    UILabel *_leftLabel;
    UILabel *_rightLabel;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(readonly, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;

@end

