//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "WALinkLabelDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIButton, UIScrollView, UIView, UIVisualEffectView, WAGradientView, WALinkLabel;

@interface WATOSViewControllerPage1 : WAViewController <WALinkLabelDelegate>
{
    UIButton *_closeButton;
    NSLayoutConstraint *_closeButtonTop;
    NSLayoutConstraint *_contentViewHeight;
    UIScrollView *_scrollView;
    WALinkLabel *_pageBodyLabel;
    UIView *_footerView;
    UIVisualEffectView *_footerBackgroundView;
    UIButton *_footerButton;
    WAGradientView *_bottomGradient;
    unsigned long long _stage;
}

- (void).cxx_destruct;
@property(nonatomic) __weak WAGradientView *bottomGradient; // @synthesize bottomGradient=_bottomGradient;
- (void)closeAction:(id)arg1;
@property(nonatomic) __weak UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak NSLayoutConstraint *closeButtonTop; // @synthesize closeButtonTop=_closeButtonTop;
- (void)configureFonts;
@property(nonatomic) __weak NSLayoutConstraint *contentViewHeight; // @synthesize contentViewHeight=_contentViewHeight;
@property(nonatomic) __weak UIVisualEffectView *footerBackgroundView; // @synthesize footerBackgroundView=_footerBackgroundView;
@property(nonatomic) __weak UIButton *footerButton; // @synthesize footerButton=_footerButton;
@property(nonatomic) __weak UIView *footerView; // @synthesize footerView=_footerView;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (void)nextAction:(id)arg1;
@property(nonatomic) __weak WALinkLabel *pageBodyLabel; // @synthesize pageBodyLabel=_pageBodyLabel;
- (void)reconfigureUI;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) unsigned long long stage; // @synthesize stage=_stage;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)wa_applicationDidBecomeActive;
- (void)wa_applicationWillEnterForeground;
- (void)wa_fontSizeDidChange;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

