//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;
@protocol WAServerDate;

@interface WATwoFactorFileValues : NSObject
{
    _Bool _hasRecoveryEmail;
    _Bool _needsSync;
    _Bool _needsStatusCheck;
    _Bool _isCodeMigratedToKeychain;
    int _nagIndex;
    NSDate<WAServerDate> *_verifiedDate;
    NSString *_keychainIdentifier;
    NSString *_fileCode;
}

+ (id)clearedValues;
+ (id)valuesWithContentsOfFile:(id)arg1;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(copy, nonatomic) NSString *fileCode; // @synthesize fileCode=_fileCode;
@property(nonatomic) _Bool hasRecoveryEmail; // @synthesize hasRecoveryEmail=_hasRecoveryEmail;
- (id)initWithValuesDictionary:(id)arg1;
@property(nonatomic) _Bool isCodeMigratedToKeychain; // @synthesize isCodeMigratedToKeychain=_isCodeMigratedToKeychain;
@property(copy, nonatomic) NSString *keychainIdentifier; // @synthesize keychainIdentifier=_keychainIdentifier;
@property(nonatomic) int nagIndex; // @synthesize nagIndex=_nagIndex;
@property(nonatomic) _Bool needsStatusCheck; // @synthesize needsStatusCheck=_needsStatusCheck;
@property(nonatomic) _Bool needsSync; // @synthesize needsSync=_needsSync;
@property(retain, nonatomic) NSDate<WAServerDate> *verifiedDate; // @synthesize verifiedDate=_verifiedDate;
- (void)writeToFile:(id)arg1;

@end

