//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WATwoFactorCodeViewControllerConfiguration : NSObject
{
    NSString *_helperLabelText;
    NSString *_leftNavigationButtonTitle;
    NSString *_rightNavigationButtonTitle;
    NSString *_backNavigationButtonTitle;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *backNavigationButtonTitle; // @synthesize backNavigationButtonTitle=_backNavigationButtonTitle;
@property(copy, nonatomic) NSString *helperLabelText; // @synthesize helperLabelText=_helperLabelText;
@property(copy, nonatomic) NSString *leftNavigationButtonTitle; // @synthesize leftNavigationButtonTitle=_leftNavigationButtonTitle;
@property(copy, nonatomic) NSString *rightNavigationButtonTitle; // @synthesize rightNavigationButtonTitle=_rightNavigationButtonTitle;

@end

