//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

#import "WALinkLabelDelegate-Protocol.h"
#import "WAPasscodeViewDelegate-Protocol.h"

@class NSString, WALinkLabel, WAOverlayView, WAPasscodeView;

@interface WATwoFactorCodeBaseViewController : WAViewController <WAPasscodeViewDelegate, WALinkLabelDelegate>
{
    NSString *_helperLabelText;
    NSString *_leftBarButtonTitle;
    NSString *_rightBarButtonTitle;
    NSString *_backBarButtonTitle;
    WAOverlayView *_overlayView;
    double _keyboardHeight;
    WALinkLabel *_labelHelperText;
    WAPasscodeView *_passcodeView;
}

- (void).cxx_destruct;
- (void)activatePasscodeFieldIfNecessary;
- (void)handleCodeEntered:(id)arg1;
- (void)handleLeftNavigationButtonTapped;
- (void)handleOpenURL:(id)arg1;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (void)hideOverlayWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (double)keyboardHeight;
@property(retain, nonatomic) WALinkLabel *labelHelperText; // @synthesize labelHelperText=_labelHelperText;
- (void)leftBarButtonItemTapped:(id)arg1;
- (_Bool)overlayDisplayed;
@property(retain, nonatomic) WAPasscodeView *passcodeView; // @synthesize passcodeView=_passcodeView;
- (void)passcodeViewDidEnterPasscode:(id)arg1;
- (void)resetPasscodeField;
- (void)rightBarButtonItemTapped:(id)arg1;
- (void)setPasscodeEditingEnabled:(_Bool)arg1;
- (void)shakePasscodeField;
- (void)showOverlayWithMessage:(id)arg1;
- (struct CGRect)subclassAvailableContentBounds;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)wa_fontSizeDidChange;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

