//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAUnifiedSyncPersistentRequestManager.h"

@interface WAUnifiedSyncPersistentRequestManager (MainAppLibrary)
- (void)registerHandlersForPersistentRequestManager:(id)arg1;
- (id)sharedObjectKeyForPersistentRequestManager:(id)arg1;
@end

