//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WASynchronousBackupOperation.h"

@class NSNumber, NSString;

@interface WAUntarFileOperation : WASynchronousBackupOperation
{
    _Bool _succeeded;
    _Bool _containsOtherAssets;
    NSString *_destination;
    unsigned long long _extracted;
    unsigned long long _total;
    CDUnknownBlockType _encryptionKeyProvider;
    _Bool _atomic;
    _Bool _ignoreMissingFile;
    NSString *_path;
    NSNumber *_lastCompletedOffset;
    NSNumber *_suggestedExtractionOffset;
}

+ (unsigned long long)getVerifiedTarFileHandleForiCloudPath:(id)arg1 encryptionKey:(id)arg2 verifiedHandle:(id *)arg3 cancellationBlock:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
@property _Bool atomic; // @synthesize atomic=_atomic;
- (unsigned long long)completedSteps;
@property _Bool ignoreMissingFile; // @synthesize ignoreMissingFile=_ignoreMissingFile;
- (id)initWithPath:(id)arg1 destination:(id)arg2 containsOtherAssets:(_Bool)arg3 encryptionKeyProvider:(CDUnknownBlockType)arg4;
@property(copy) NSNumber *lastCompletedOffset; // @synthesize lastCompletedOffset=_lastCompletedOffset;
@property(readonly, copy) NSString *path; // @synthesize path=_path;
- (void)run;
@property(copy) NSNumber *suggestedExtractionOffset; // @synthesize suggestedExtractionOffset=_suggestedExtractionOffset;
- (_Bool)succeeded;
- (unsigned long long)totalSteps;

@end

