//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WAUpgradeCallback <NSObject>
+ (void)wa_didUpgradeFrom:(NSString *)arg1 to:(NSString *)arg2;
@end

