//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAUserJID.h>

@interface WAUserJID (BizOptOutInfo)
- (id)bizOptOutInfoForOrigin:(unsigned long long)arg1;
@end

