//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WAVerificationBaseController.h"

#import "WAProfileBaseViewControllerDelegate-Protocol.h"

@class NSString;

@interface WAVerificationProfileController : WAVerificationBaseController <WAProfileBaseViewControllerDelegate>
{
}

- (id)init;
- (void)profileViewControllerDidFinish:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

