//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAVerificationHelper : NSObject
{
}

+ (id)alertTextForFailedRegRequest;
+ (id)alertTextForFailedRegRequestOther;
+ (id)alertTextForFailedRegRequestWifi;
+ (void)cancelPhoneNumberChange;
+ (id)createPassInputControllerWithDelegate:(id)arg1 session:(id)arg2;
+ (id)createTwoFactorCodeViewControllerWithSession:(id)arg1 response:(id)arg2 smsVerificationCodeUsed:(id)arg3 delegate:(id)arg4;
+ (id)invalidCharactersInPushName:(id)arg1;
+ (_Bool)isProfilePhotoValid;
+ (_Bool)isPushNameValid;
+ (_Bool)isUserProfileValid;
+ (void)saveAccountWithPhoneNumber:(id)arg1 deviceJID:(id)arg2;
+ (void)savePhoneNumberChangeWithSession:(id)arg1 deviceJID:(id)arg2 contactJIDs:(id)arg3;
+ (void)validateProfileAndSettingsOnUpgrade;
+ (void)waiveProfilePhotoRequirement;

@end

