//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAVoiceCallInteractionBlockingView;

@protocol WAVoiceCallInteractionBlockingViewDelegate <NSObject>
- (void)voiceCallInteractionBlockingViewDidUnlock:(WAVoiceCallInteractionBlockingView *)arg1;
@end

