//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAStaticTableViewController.h>

@class MISSING_TYPE;

@interface WAWallpaperArchiveTableViewController : WAStaticTableViewController
{
    MISSING_TYPE *isCustom;
}

- (id)initWithCoder:(id)arg1;
- (id)initWithInsetGrouped;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (id)initWithStyle:(long long)arg1 isCustom:(_Bool)arg2;
- (void)setUpTableView;

@end

