//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WANavigationController.h>

#import "UINavigationControllerDelegate-Protocol.h"
#import "WAQRCodeScannerViewControllerDelegate-Protocol.h"
#import "WAWebClientNetworkStatusViewControllerDelegate-Protocol.h"

@class NSString;
@protocol WAAddCompanionReference;

@interface WAWebClientAuthorizationFlowViewController : WANavigationController <UINavigationControllerDelegate, WAWebClientNetworkStatusViewControllerDelegate, WAQRCodeScannerViewControllerDelegate>
{
    long long _retryCount;
    CDUnknownBlockType _dismissalBlock;
    id <WAAddCompanionReference> _addReference;
    _Bool _pairingInProgress;
}

+ (id)flowWithXMPPConnection:(id)arg1 dismissalBlock:(CDUnknownBlockType)arg2;
+ (void)presentFromViewController:(id)arg1 xmppConnection:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)presentFromViewController:(id)arg1 xmppConnection:(id)arg2 requireAuthentication:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
- (id)initWithRootViewController:(id)arg1 dismissalBlock:(CDUnknownBlockType)arg2;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)networkStatusViewController:(id)arg1 didContinueWithMode:(unsigned long long)arg2;
- (void)qrCodeScannerViewController:(id)arg1 didFinishWithCode:(id)arg2;
- (_Bool)qrCodeScannerViewController:(id)arg1 shouldAcceptCode:(id)arg2;
- (void)qrCodeScannerViewControllerDidCancel:(id)arg1;
- (void)safeDismiss;
- (void)showGeneralErrorMessageForFailureResultInViewController:(id)arg1 webClientSessionResult:(long long)arg2 reason:(long long)arg3;
- (void)showNoConnectionErrorMessageForFailureResultInViewController:(id)arg1 reason:(long long)arg2;
- (void)showSignInErrorMessageForFailureResultInViewController:(id)arg1 reason:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

