//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString, WAWebClientSession;

@interface WAWebClientPersistentLoginRequest : NSObject
{
    NSString *_webRef;
    NSString *_browserID;
    NSString *_clientToken;
    NSString *_syncType;
    NSString *_syncKind;
    WAWebClientSession *_session;
    NSData *_serverChallenge;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *browserID; // @synthesize browserID=_browserID;
@property(readonly, copy, nonatomic) NSString *clientToken; // @synthesize clientToken=_clientToken;
- (id)description;
- (id)initWithStanzaElement:(id)arg1;
@property(copy, nonatomic) NSData *serverChallenge; // @synthesize serverChallenge=_serverChallenge;
@property(readonly, nonatomic) WAWebClientSession *session; // @synthesize session=_session;
@property(readonly, copy, nonatomic) NSString *syncKind; // @synthesize syncKind=_syncKind;
@property(readonly, copy, nonatomic) NSString *syncType; // @synthesize syncType=_syncType;
@property(readonly, copy, nonatomic) NSString *webRef; // @synthesize webRef=_webRef;

@end

