//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Core/WAErrorReceiptPersistentRequest.h>

@interface WAXMPPStructureUnavailableReceiptRequest : WAErrorReceiptPersistentRequest
{
}

+ (long long)version;
- (id)initWithMessageID:(id)arg1 reason:(unsigned long long)arg2 subType:(id)arg3;
- (id)initWithMessageID:(id)arg1 reason:(unsigned long long)arg2 subType:(id)arg3 buttonIndex:(long long)arg4;

@end

