//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WAFoundation/WAViewController.h>

@class MISSING_TYPE;

@interface WAXPlatformAppUpdateRequiredViewController : WAViewController
{
    MISSING_TYPE *updateButton;
    MISSING_TYPE *cancelUpdateButton;
    MISSING_TYPE *contentDescriptionView;
}

- (void).cxx_destruct;
- (void)didTapCancelButtonWithSender:(id)arg1;
- (void)didTapUpdateButtonWithSender:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) _Bool shouldAutorotate;
- (void)viewDidLoad;

@end

