//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "XMPPUnifiedSyncItemBase.h"

@interface XMPPUnifiedSyncItemSidelist : XMPPUnifiedSyncItemBase
{
    _Bool _deleted;
}

@property(nonatomic) _Bool deleted; // @synthesize deleted=_deleted;
- (id)serialize;

@end

