//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString, WAUserJID;
@protocol WAServerDate;

@interface XMPPStatus : NSObject
{
    WAUserJID *_userJID;
    NSString *_aboutText;
    NSDate<WAServerDate> *_timestamp;
    unsigned long long _errorCode;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *aboutText; // @synthesize aboutText=_aboutText;
@property(readonly, nonatomic) unsigned long long errorCode; // @synthesize errorCode=_errorCode;
- (id)initWithUserJID:(id)arg1 aboutText:(id)arg2 timestamp:(id)arg3;
- (id)initWithUserJID:(id)arg1 errorCode:(unsigned long long)arg2;
@property(readonly, nonatomic) NSDate<WAServerDate> *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) WAUserJID *userJID; // @synthesize userJID=_userJID;

@end

