//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WAUserJID, XMPPUnifiedSyncItemBusiness, XMPPUnifiedSyncItemContact, XMPPUnifiedSyncItemDevices, XMPPUnifiedSyncItemPayments, XMPPUnifiedSyncItemSidelist, XMPPUnifiedSyncItemStatus;

@interface XMPPUnifiedSyncUserRequest : NSObject
{
    WAUserJID *_jid;
    XMPPUnifiedSyncItemBusiness *_businessItem;
    XMPPUnifiedSyncItemContact *_contactItem;
    XMPPUnifiedSyncItemDevices *_devicesItem;
    XMPPUnifiedSyncItemPayments *_paymentsItem;
    XMPPUnifiedSyncItemSidelist *_sidelistItem;
    XMPPUnifiedSyncItemStatus *_statusItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) XMPPUnifiedSyncItemBusiness *businessItem; // @synthesize businessItem=_businessItem;
@property(retain, nonatomic) XMPPUnifiedSyncItemContact *contactItem; // @synthesize contactItem=_contactItem;
@property(retain, nonatomic) XMPPUnifiedSyncItemDevices *devicesItem; // @synthesize devicesItem=_devicesItem;
@property(retain, nonatomic) WAUserJID *jid; // @synthesize jid=_jid;
@property(retain, nonatomic) XMPPUnifiedSyncItemPayments *paymentsItem; // @synthesize paymentsItem=_paymentsItem;
- (id)serialize;
@property(retain, nonatomic) XMPPUnifiedSyncItemSidelist *sidelistItem; // @synthesize sidelistItem=_sidelistItem;
@property(retain, nonatomic) XMPPUnifiedSyncItemStatus *statusItem; // @synthesize statusItem=_statusItem;

@end

