//
//     Generated by classdumpios 1.0.2 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XMPPDeepLinkValid : NSObject
{
    unsigned long long _status;
    NSString *_url;
}

- (void).cxx_destruct;
- (id)initWithStatus:(id)arg1 url:(id)arg2;
@property(readonly, nonatomic) unsigned long long status; // @synthesize status=_status;
@property(readonly, copy, nonatomic) NSString *url; // @synthesize url=_url;

@end

